### ISSUE TITLE
running chlid process within node sandbox

### ISSUE THREAD

**Issue by akhiljay** [codesandbox/codesandbox-client#1848]
# ❔ Question
Trying to run a child process within code sandbox using the code below

const spawn = require("child_process").spawn;

but keep getting the error
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn akamai ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

are child process allowed within the sandbox?

**Comment by lbogdan** [comment]
Hey @akhiljay , I'm guessing you already solved this, considering you opened #1852 , so I'm just gonna close it.
