### ISSUE TITLE
Hot reloading fails: TypeError: Cannot read property 'Ctor' of undefined

### ISSUE THREAD

**Issue by tony19** [codesandbox/codesandbox-client#2058]
# 🐛 bug report

## Description of the problem
A previously working Codesandbox is now crashing with:
<details>
<summary><code>Cannot read property 'Ctor' of undefined</code></summary>
<pre>sandbox.115b0c69.js:1 TypeError: Cannot read property 'Ctor' of undefined
    at VueComponent.eval (eval at de (sandbox.115b0c69.js:1), <anonymous>:88:19)
    at invokeWithErrorHandling (VM3644 vue.common.dev.js:1859)
    at callHook (VM3644 vue.common.dev.js:4210)
    at VueComponent.Vue._init (VM3644 vue.common.dev.js:4988)
    at new VueComponent (VM3644 vue.common.dev.js:5137)
    at createComponentInstanceForVnode (VM3644 vue.common.dev.js:3286)
    at init (VM3644 vue.common.dev.js:3117)
    at createComponent (VM3644 vue.common.dev.js:5963)
    at createElm (VM3644 vue.common.dev.js:5910)
    at VueComponent.patch [as __patch__] (VM3644 vue.common.dev.js:6460)
    at VueComponent.Vue._update (VM3644 vue.common.dev.js:3936)
    at VueComponent.updateComponent (VM3644 vue.common.dev.js:4057)
    at Watcher.get (VM3644 vue.common.dev.js:4468)
    at new Watcher (VM3644 vue.common.dev.js:4457)
    at mountComponent (VM3644 vue.common.dev.js:4064)
    at VueComponent.Vue.$mount (VM3644 vue.common.dev.js:9034)
    at VueComponent.Vue.$mount (VM3644 vue.common.dev.js:11919)
    at mount (vue-test-utils.js:6187)
    at shallowMount (vue-test-utils.js:6218)
    at Object.eval (MyComponent.spec.js? [sm]:11)
    at vendors~sandbox.b6b2495b.chunk.js:310
    at new Promise (<anonymous>)
    at t.callAsyncFn (vendors~sandbox.b6b2495b.chunk.js:310)
    at sandbox.115b0c69.js:1
    at g (common-sandbox.52624a55.chunk.js:15)
    at Generator._invoke (common-sandbox.52624a55.chunk.js:15)
    at Generator.e.<computed> [as next] (common-sandbox.52624a55.chunk.js:15)
    at o (common-sandbox.52624a55.chunk.js:15)
    at u (common-sandbox.52624a55.chunk.js:15)
    at common-sandbox.52624a55.chunk.js:15
    at new Promise (<anonymous>)
    at common-sandbox.52624a55.chunk.js:15
    at sandbox.115b0c69.js:1
    at sandbox.115b0c69.js:1
    at g (common-sandbox.52624a55.chunk.js:15)
    at Generator._invoke (common-sandbox.52624a55.chunk.js:15)
    at Generator.e.<computed> [as next] (common-sandbox.52624a55.chunk.js:15)
    at o (common-sandbox.52624a55.chunk.js:15)
    at u (common-sandbox.52624a55.chunk.js:15)
    at common-sandbox.52624a55.chunk.js:15
    at new Promise (<anonymous>)
    at common-sandbox.52624a55.chunk.js:15
    at sandbox.115b0c69.js:1
    at sandbox.115b0c69.js:1
    at g (common-sandbox.52624a55.chunk.js:15)
    at Generator._invoke (common-sandbox.52624a55.chunk.js:15)
    at Generator.e.<computed> [as next] (common-sandbox.52624a55.chunk.js:15)
    at o (common-sandbox.52624a55.chunk.js:15)
    at u (common-sandbox.52624a55.chunk.js:15)
    at common-sandbox.52624a55.chunk.js:15</pre>
</details>
<img width="670" alt="screenshot of error" src="https://user-images.githubusercontent.com/26580/59450938-f504f400-8dcf-11e9-8ec4-4df246ddc1d5.png">

*Related:* #1329

## How has this issue affected you? What are you trying to accomplish?

This prevents me from running unit tests in Codesandbox.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | `PROD-1559903240-93ff18a72`
| Browser          | Chrome `Version 74.0.3729.169 (Official Build) (64-bit)`
| Operating System | macOS Mojave `10.14.5`

**Comment by idmick** [comment]
I'm experiencing the same issue when I try to run my unit tests. I also saw the same problem in other Vue Codesandboxes.

Link to my sandbox: [link](https://codesandbox.io/s/vue-template-hcvh0)
Link to another Vue sandbox: [link](https://codesandbox.io/s/2j0qlx423n)

**Comment by sybrendotinga** [comment]
I have the same problem: https://codesandbox.io/s/vue-emit-test-case-pwq4i?fontsize=14&previewwindow=tests

Whilst debugging I have found dozens of other Vue Sandboxes that also don't work.
Using Chrome 76. But also Firefox 68.

**Comment by ChristophWalter** [comment]
I got the same error: https://codesandbox.io/s/vuetify-with-vue-testing-library-bhu8f?previewwindow=tests

**Comment by henryachen** [comment]
Same error too:
https://codesandbox.io/s/tribe-fullstack-project-4ccgf

**Comment by JFGHT** [comment]
Still not fixed.

**Comment by Tyow1** [comment]
I've really been enjoying using codesandbox. Went to go try some unit testing, got these errors, quite frustrating. Been looking around for other IDEs with good Vue interaction and have come up empty handed..

**Comment by lbogdan** [comment]
Hello everyone, 🙂

Is this still an issue for you? I just tested all the sandboxes from the OP and comments, and they all worked for me. The tests ones give some errors (which seem to be related to the tests themselves), but not the original "Cannot read property 'Ctor' of undefined" one.

**Comment by sybrendotinga** [comment]
> Hello everyone, 🙂
> 
> Is this still an issue for you? I just tested all the sandboxes from the OP and comments, and they all work for me. The tests ones give some errors (which seem to be related to the tests themselves), but not the original **_Cannot read property 'Ctor' of undefined_** one.
> 
> @JFGHT If it's still an issue for you, can you please point us to a sandbox experiencing this?

Works for me! Thanks for checking!

**Comment by JFGHT** [comment]
> Hello everyone, 
> 
> Is this still an issue for you? I just tested all the sandboxes from the OP and comments, and they all work for me. The tests ones give some errors (which seem to be related to the tests themselves), but not the original **_Cannot read property 'Ctor' of undefined_** one.
> 
> @JFGHT If it's still an issue for you, can you please point us to a sandbox experiencing this?

It's working now, thanks :).

**Comment by derberg** [comment]
I have 3 sandboxes that worked before and do not work now for several days already.
- Versions of dependencies did not change
- They work perfectly fine when I start them on my local machine

- https://codesandbox.io/s/github/derberg/asyncapi-react-in-action
- https://codesandbox.io/s/github/derberg/documentation-component-showcase
- https://codesandbox.io/s/github/derberg/dc-demo-all-render-engines

**Comment by tony19** [comment]
The bug seems to have resurfaced, as seen in the original sandbox link and newly created Vue sandboxes with similar unit tests.

**Comment by elbojoloco** [comment]
Is there any update on this? I can't write any vue tests for my single file components because of this error. All the other suggestions online are "clean up node_modules", but that's not possible in a sandbox.

**Comment by anzuj** [comment]
> Hello everyone, 🙂
> 
> Is this still an issue for you? I just tested all the sandboxes from the OP and comments, and they all work for me. The tests ones give some errors (which seem to be related to the tests themselves), but not the original **_Cannot read property 'Ctor' of undefined_** one.
> 

@ibogdan I'm experiencing the same when trying to run unit tests in my single file component sandbox [here ](https://codesandbox.io/s/jest-testing-b7j9u?file=/package.json) 

If I may add, this page: https://codesandbox.io/docs/tests could use an update as well since there are quite some caveats to modifying your repository. For example my Vue CLI project did not render Jest tests at all until I manually included "@vue/test-utils" under dependancies in the real [repo](https://github.com/anzuj/jest-test/blob/simplified/package.json) I instead have "@vue/cli-plugin-unit-jest". So some guidelines of a standard package.json for Vue/React projects would save a lot of time for people trying to import their github projects for demonstration purposes.
Also "vue-template-compiler"  had to be moved from devDependancies to dependancies

**Comment by anzuj** [comment]
Maybe it helps someone, but in [this repo](https://codesandbox.io/s/vue-jest-workshop-forked-8s3zn?file=/src/tests/feature/counter.spec.js) you can see **romans.spec.js** test processes fine since it just tests JS logic, but **counter.spec.js** that tries to shallowMmount a Counter.vue fails with the same 'Ctor' error.

**Comment by SeriousHorncat** [comment]
I can second what the other recent posts are saying.  This is incredibly frustrating not being able to have unit tests run with the project.

@lbogdan I am also getting this error now.  [Sandbox with Issue occurring](https://codesandbox.io/s/cgds-cpam-evaluation-sdsgf?file=/tests/unit/AnalysisCard.spec.js). It looks like versioning issues but unable to resolve them due being unsure how the package.json is being processed for VueJS.

**Comment by tony19** [comment]
Still unresolved

**Comment by MichaelViveros** [comment]
I found a work-around by defining my component in the test file as mentioned in https://stackoverflow.com/questions/63150352/vue-test-utils-unable-to-mount-imported-vue.

**Comment by tony19** [comment]
Still unresolved

**Comment by florianschepp** [comment]
Got it as well

**Comment by gdimitropoulos** [comment]
is there any solution to this problem ?

**Comment by str1x** [comment]
try dynamic import for components in tests
`import { shallowMount } from "@vue/test-utils";
const Game = async () => (await import("/src/Game.vue")).default;

describe("Game", () => {
  it("mounts", async () => {
    const wrapper = shallowMount(await Game());

    expect(wrapper.exists()).toBe(true);
  });
});`

**Comment by joshua-farmlink** [comment]
This issue started appearing for me a few weeks ago, in any Vue 2 templates.
```
TypeError: Cannot read properties of undefined (reading 'Ctor')
    at eval (https://0gti42.csb.app/node_modules/vue-hot-reload-api.js?25cdd719:223:16)
    at Object.eval [as reload] (https://0gti42.csb.app/node_modules/vue-hot-reload-api.js?25cdd719:119:7)
    at eval (https://0gti42.csb.app/src/components/Movies.vue:34:12)
    at $csb$eval (https://0gti42.csb.app/src/components/Movies.vue:39:3)
    at H (https://codesandbox.io/static/js/sandbox.204e2cfc5.js:1:99766)
    at K.evaluate (https://codesandbox.io/static/js/sandbox.204e2cfc5.js:1:112485)
    at https://codesandbox.io/static/js/sandbox.204e2cfc5.js:1:122257
    at Array.forEach (<anonymous>)
    at ge.evaluateModule (https://codesandbox.io/static/js/sandbox.204e2cfc5.js:1:122244)
    at https://codesandbox.io/static/js/sandbox.204e2cfc5.js:1:317554
    at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.7424373eb.chunk.js:1:4328)
    at Generator._invoke (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.7424373eb.chunk.js:1:4081)
    at forEach.t.<computed> [as next] (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.7424373eb.chunk.js:1:4685)
    at e (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.7424373eb.chunk.js:1:206)
    at a (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.7424373eb.chunk.js:1:417)
Something went wrong during Vue component hot-reload. Full reload required. 
```

**Comment by kikoshoung** [comment]
Same issue here: https://codesandbox.io/s/3y37yt?file=/src/App.vue&utm_medium=sandpack.
Is there any official solution for this?

`vendors~sandbox-startup.dfd50334d.chunk.js:1 TypeError: Cannot read properties of undefined (reading 'Ctor')
    at eval (vue-hot-reload-api.js?25cdd719:151:14)
    at Object.eval [as rerender] (vue-hot-reload-api.js?25cdd719:119:7)
    at $csb$eval (App.vue?47f6f59c:8:71)
    at J (sandbox.dbefb700f.js:1:163993)
    at K.evaluate (sandbox.dbefb700f.js:1:176712)
    at sandbox.dbefb700f.js:1:186484
    at Array.forEach (<anonymous>)
    at ve.evaluateModule (sandbox.dbefb700f.js:1:186471)
    at sandbox.dbefb700f.js:1:391751
    at c (vendors~sandbox~sandbox-startup.2827e9577.chunk.js:1:4318)
    at Generator._invoke (vendors~sandbox~sandbox-startup.2827e9577.chunk.js:1:4071)
    at forEach.t.<computed> [as next] (vendors~sandbox~sandbox-startup.2827e9577.chunk.js:1:4675)
    at e (vendors~sandbox~sandbox-startup.2827e9577.chunk.js:1:196)
    at a (vendors~sandbox~sandbox-startup.2827e9577.chunk.js:1:407)
Something went wrong during Vue component hot-reload. Full reload required.`

**Comment by q479902964** [comment]
> Same issue with Vue2 templates: https://codesandbox.io/s/3y37yt?file=/src/App.vue&utm_medium=sandpack. In App.vue, HMR only works with style part, template and script don‘t. Is there any official solution for this?
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'Ctor')
>     at eval (https://2w52gr.csb.app/node_modules/vue-hot-reload-api.js?25cdd719:151:14)
>     at Object.eval [as rerender] (https://2w52gr.csb.app/node_modules/vue-hot-reload-api.js?25cdd719:119:7)
>     at $csb$eval (https://2w52gr.csb.app/src/App.vue?47f6f59c:8:71)
>     at H (https://codesandbox.io/static/js/sandbox.c736ef00e.js:1:100045)
>     at K.evaluate (https://codesandbox.io/static/js/sandbox.c736ef00e.js:1:112764)
>     at https://codesandbox.io/static/js/sandbox.c736ef00e.js:1:122536
>     at Array.forEach (<anonymous>)
>     at ge.evaluateModule (https://codesandbox.io/static/js/sandbox.c736ef00e.js:1:122523)
>     at https://codesandbox.io/static/js/sandbox.c736ef00e.js:1:322189
>     at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.7424373eb.chunk.js:1:4328)
>     at Generator._invoke (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.7424373eb.chunk.js:1:4081)
>     at forEach.t.<computed> [as next] (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.7424373eb.chunk.js:1:4685)
>     at e (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.7424373eb.chunk.js:1:206)
>     at a (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.7424373eb.chunk.js:1:417)
> 
> Something went wrong during Vue component hot-reload. Full reload required.
> ```

I also encountered the same problem.
Is there any official solution for this?

**Comment by arcturus011** [comment]
i found a solution.  https://github.com/codesandbox/codesandbox-client/pull/8127
