### ISSUE TITLE
💥 Crash Report: Signing out from patron page fails

### ISSUE THREAD

**Issue by oskarabc** [codesandbox/codesandbox-client#2333]
<h1>💥 Crash Report</h1>
Can't signout without CodeSadbox appearing.

<h2>What were you trying to accomplish when the crash occurred?</h2>
Signing out.

<h3>Link to sandbox: [link]() (optional)</h3>
From https://codesandbox.io/patron

<h3>Crash Details</h3>

<details>
<summary>Environment</summary>

| Browser |  Version  | Operating System |
| ------- | --------- | ---------------- |
| chrome | 76.0.3809 | OS X 10.14.6           |

</details>

<details>
<summary>Error Message</summary>

```bash
TypeError: Cannot read property 'subscription' of undefined
TypeError: Cannot read property 'subscription' of undefined
    at https://codesandbox.io/static/js/page-patron.9ba3b493.chunk.js:1:13080
    at https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1214583
    at https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1214408
    at ye (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1242334)
    at e.track (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1247285)
    at h (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1214385)
    at u (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1214563)
    at Li (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:2002166)
    at ps (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:2009250)
    at fs (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:2009069)

    in u
    in r
    in inject-with-store-signals(Object)
    in div
    in t
    in elements__Details
    in div
    in t
    in elements__Container
    in u
    in r
    in inject-with-store(Object)
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in Unknown
    in div
    in t
    in elements__Content
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in Unknown
    in n
    in r
    in inject-with-signals(n)
    in n
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in u
    in t
    in withRouter(undefined)
    in DragDropContext(withRouter(undefined))
    in r
    in inject-with-signals(DragDropContext(withRouter(undefined)))
    in t
    in t
    in l
    in t
    in t
```

</details>

**Comment by bazzjuh** [comment]
.

**Comment by oskarabc** [comment]
After a test seems to work now.
