### ISSUE TITLE
💥 Crash Report: <Short Description of Crash Circumstances>

### ISSUE THREAD

**Issue by MessyNerd** [codesandbox/codesandbox-client#2337]
<h1>💥 Crash Report</h1>

<h2>What were you trying to accomplish when the crash occurred?</h2>

<h3>Link to sandbox: [link]() (optional)</h3>

<h3>Crash Details</h3>

<details>
<summary>Environment</summary>

| Browser |  Version  | Operating System |
| ------- | --------- | ---------------- |
| chrome | 76.0.3809 | OS X 10.14.4           |

</details>

<details>
<summary>Error Message</summary>

```bash
TypeError: Cannot read property 'generated' of undefined
TypeError: Cannot read property 'generated' of undefined
    at Object.getEntries (https://codesandbox.io/static/js/default~app~embed~sandbox.fc61db8f.chunk.js:1:11757)
    at a (https://codesandbox.io/static/js/app.cdd3f472.js:438:738119)
    at Object.mainModule (https://codesandbox.io/static/js/app.cdd3f472.js:438:135209)
    at Object.get (https://codesandbox.io/static/js/vendors~app.72f27e25.chunk.js:1:25749)
    at ye (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1242334)
    at e.computeValue (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1240411)
    at e.trackAndCompute (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1240237)
    at e.get (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1239283)
    at e.read (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1274134)
    at Object.get (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1275601)

    in n
    in r
    in inject-with-store(n)
    in div
    in t
    in elements__Opener
    in div
    in n
    in DropTarget(n)
    in r
    in inject-with-signals-store(DropTarget(n))
    in n
    in r
    in inject-with-signals-store(n)
    in div
    in files
    in div
    in div
    in t
    in elements__Container
    in u
    in r
    in inject-with-store(Object)
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in n
    in r
    in inject-with-signals-store(n)
    in n
    in r
    in inject-with-signals-store(n)
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in u
    in t
    in withRouter(undefined)
    in DragDropContext(withRouter(undefined))
    in r
    in inject-with-signals(DragDropContext(withRouter(undefined)))
    in t
    in t
    in l
    in t
    in t
```

</details>

**Comment by SaraVieira** [comment]
Closed for lack of information :(
