### ISSUE TITLE
💥 Crash Report: <Short Description of Crash Circumstances>

### ISSUE THREAD

**Issue by rashidpathiyil** [codesandbox/codesandbox-client#2358]
<h1>💥 Crash Report</h1>

<h2>What were you trying to accomplish when the crash occurred?</h2>

<h3>Link to sandbox: [link]() (optional)</h3>

<h3>Crash Details</h3>

<details>
<summary>Environment</summary>

| Browser |  Version  | Operating System |
| ------- | --------- | ---------------- |
| chrome | 76.0.3809 | Windows 10           |

</details>

<details>
<summary>Error Message</summary>

```bash
TypeError: Cannot read property 'integrations' of null
TypeError: Cannot read property 'integrations' of null
    at https://codesandbox.io/static/js/app.4cccea31.js:438:674974
    at https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1214583
    at https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1214408
    at ye (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1242334)
    at e.track (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1247285)
    at h (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1214385)
    at u (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1214563)
    at Li (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:2002166)
    at ps (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:2009250)
    at fs (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:2009069)
    at ds (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:2008788)
    at Ka (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:2048758)
    at Fa (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:2030981)
    at Na (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:2028001)
    at Ra (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:2026561)
    at https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1988462
    at https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:2063308
    at co (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1988191)
    at po (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1988408)
    at ho (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1988343)
    at Da (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:2026888)
    at We (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1248919)
    at Ve (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1248499)
    at Le (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1244986)
    at re (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1235948)
    at ne (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1235898)
    at r (https://codesandbox.io/static/js/common.182e17e0.chunk.js:1:1235568)
    at https://codesandbox.io/static/js/vendors~app.72f27e25.chunk.js:1:869042
    at Ee (https://codesandbox.io/static/js/vendors~app.72f27e25.chunk.js:1:869299)
    at Object.r (https://codesandbox.io/static/js/vendors~app.72f27e25.chunk.js:1:869475)
    at t.value (https://codesandbox.io/static/js/vendors~app.72f27e25.chunk.js:1:26559)
    at t.value (https://codesandbox.io/static/js/vendors~app.72f27e25.chunk.js:1:27588)
    at Object.set (https://codesandbox.io/static/js/vendors~app.72f27e25.chunk.js:1:581289)
    at Object.n [as function] (https://codesandbox.io/static/js/vendors~app.72f27e25.chunk.js:1:579338)
    at e.value (https://codesandbox.io/static/js/vendors~app.72f27e25.chunk.js:1:714430)
    at https://codesandbox.io/static/js/vendors~app.72f27e25.chunk.js:1:706215
    at https://codesandbox.io/static/js/vendors~app.72f27e25.chunk.js:1:717120
    at t (https://codesandbox.io/static/js/vendors~app.72f27e25.chunk.js:1:705443)
    at https://codesandbox.io/static/js/vendors~app.72f27e25.chunk.js:1:705741
    at https://codesandbox.io/static/js/vendors~app.72f27e25.chunk.js:1:714611

    in u
    in r
    in inject-with-store-signals(Object)
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in n
    in r
    in inject-with-signals-store(n)
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in u
    in t
    in withRouter(undefined)
    in DragDropContext(withRouter(undefined))
    in r
    in inject-with-signals(DragDropContext(withRouter(undefined)))
    in t
    in t
    in l
    in t
    in t
```

</details>

**Comment by SaraVieira** [comment]
Closed for lack of information :(

**Comment by SaraVieira** [comment]
Also duplicate
