### ISSUE TITLE
💥 Crash Report: <Please Add a Short Description of Crash Circumstances>

### ISSUE THREAD

**Issue by msterzhang** [codesandbox/codesandbox-client#2407]
<h1>💥 Crash Report</h1>

<h2>What were you trying to accomplish when the crash occurred?</h2>

> Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

<h3>Link to sandbox: [link]() (optional)</h3>

<h3>Crash Details</h3>

<details>
<summary>Environment</summary>

| Browser |  Version  | Operating System |
| ------- | --------- | ---------------- |
| chrome | 76.0.3809 | Windows 10           |

**Route:**
https://codesandbox.io/s/example-hello-world-53ybw

</details>

<details>
<summary>Error Message</summary>

```bash
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at HTMLDivElement.removeChild (<anonymous>)
    at zs (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2081850)
    at Is (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2080045)
    at Ps (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2080088)
    at zs (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2081772)
    at https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2100603
    at https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2123790
    at co (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2048673)
    at Ua (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2098406)
    at Ra (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2087043)
    at https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2048944
    at https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2123790
    at co (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2048673)
    at po (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2048890)
    at ho (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2048825)
    at Ie (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2116867)
    at Pn (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2038783)
    at https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2038393
    at HTMLDocument.r (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:122867)

    in elements__IconArea
    in div
    in t
    in elements__EntryContainer
    in n
    in div
    in t
    in styled.div
    in div
    in u
    in r
    in inject-with-reaction-store-signals(Object)
    in div
    in t
    in elements__ChildContainer
    in div
    in t
    in n
    in div
    in files
    in div
    in div
    in t
    in elements__Container
    in u
    in r
    in inject-with-reaction-store(Object)
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in n
    in r
    in inject-with-reaction-signals-store(n)
    in n
    in r
    in inject-with-reaction-signals-store(n)
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in u
    in t
    in withRouter(undefined)
    in DragDropContext(withRouter(undefined))
    in r
    in inject-with-reaction-signals(DragDropContext(withRouter(undefined)))
    in t
    in t
    in l
    in t
    in t
```

</details>

**Comment by SaraVieira** [comment]
Hey

Can you please tell us how you got to this error?
