### ISSUE TITLE
💥 Crash Report: <Please Add a Short Description of Crash Circumstances>

### ISSUE THREAD

**Issue by LisaCee** [codesandbox/codesandbox-client#2422]
<h1>💥 Crash Report</h1>

<h2>What were you trying to accomplish when the crash occurred?</h2>
Import a repo from gitub to codeSandbox

> Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

<h3>Link to sandbox: [link]() (optional)</h3>
N/A

<h3>Crash Details</h3>

<details>
<summary>Environment</summary>

| Browser |  Version  | Operating System |
| ------- | --------- | ---------------- |
| chrome | 76.0.3809 | Windows 10           |

**Route:**
https://codesandbox.io/s/github/Artist-Portfolio/FrontEnd

</details>

<details>
<summary>Error Message</summary>

```bash
TypeError: Cannot read property 'integrations' of null
TypeError: Cannot read property 'integrations' of null
    at https://codesandbox.io/static/js/app.b6409584.js:438:670114
    at https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:1271503
    at https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:1271328
    at ye (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:1299254)
    at e.track (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:1304205)
    at h (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:1271305)
    at u (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:1271483)
    at Li (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2062648)
    at ps (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2069732)
    at fs (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2069551)
    at ds (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2069270)
    at Ka (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2109240)
    at Fa (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2091463)
    at Na (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2088483)
    at Ra (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2087043)
    at https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2048944
    at https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2123790
    at co (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2048673)
    at po (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2048890)
    at ho (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2048825)
    at Da (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:2087370)
    at We (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:1305839)
    at qe (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:1305419)
    at Le (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:1301906)
    at re (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:1292868)
    at ne (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:1292818)
    at r (https://codesandbox.io/static/js/common.03f0c3a4.chunk.js:1:1292488)
    at https://codesandbox.io/static/js/vendors~app.458f42b0.chunk.js:1:827895
    at Ee (https://codesandbox.io/static/js/vendors~app.458f42b0.chunk.js:1:828152)
    at Object.r (https://codesandbox.io/static/js/vendors~app.458f42b0.chunk.js:1:828328)
    at t.value (https://codesandbox.io/static/js/vendors~app.458f42b0.chunk.js:1:26559)
    at t.value (https://codesandbox.io/static/js/vendors~app.458f42b0.chunk.js:1:27588)
    at Object.set (https://codesandbox.io/static/js/vendors~app.458f42b0.chunk.js:1:581699)
    at Object.n [as function] (https://codesandbox.io/static/js/vendors~app.458f42b0.chunk.js:1:579748)
    at e.value (https://codesandbox.io/static/js/vendors~app.458f42b0.chunk.js:1:674721)
    at https://codesandbox.io/static/js/vendors~app.458f42b0.chunk.js:1:666506
    at https://codesandbox.io/static/js/vendors~app.458f42b0.chunk.js:1:677411
    at t (https://codesandbox.io/static/js/vendors~app.458f42b0.chunk.js:1:665734)
    at https://codesandbox.io/static/js/vendors~app.458f42b0.chunk.js:1:666032
    at https://codesandbox.io/static/js/vendors~app.458f42b0.chunk.js:1:674902

    in u
    in r
    in inject-with-reaction-store-signals(Object)
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in n
    in r
    in inject-with-reaction-signals-store(n)
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in u
    in t
    in withRouter(undefined)
    in DragDropContext(withRouter(undefined))
    in r
    in inject-with-reaction-signals(DragDropContext(withRouter(undefined)))
    in t
    in t
    in l
    in t
    in t
```

</details>

**Comment by Saeris** [comment]
So I was unable to reproduce this crash visiting the sandbox linked in the report. Could you please provide some additional details as to how you encountered this crash?

**Comment by LisaCee** [comment]
Sorry, this crash may have been due to network issues that hadn't fully shown themselves at the time.  Thanks for the follow up.
