### ISSUE TITLE
💥 Crash Report: <Please Add a Short Description of Crash Circumstances>

### ISSUE THREAD

**Issue by penouc** [codesandbox/codesandbox-client#2458]
<h1>💥 Crash Report</h1>

<h2>What were you trying to accomplish when the crash occurred?</h2>

> Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

<h3>Link to sandbox: [link]() (optional)</h3>

<h3>Crash Details</h3>

<details>
<summary>Environment</summary>

| Browser |  Version  | Operating System |
| ------- | --------- | ---------------- |
| chrome | 76.0.3809 | OS X 10.14.6           |

**Route:**
https://codesandbox.io/dashboard/recent

</details>

<details>
<summary>Error Message</summary>

```bash
TypeError: Cannot read property 'sandboxes' of undefined
TypeError: Cannot read property 'sandboxes' of undefined
    at Object.children (https://codesandbox.io/static/js/app.615494a2.js:438:223493)
    at n (https://codesandbox.io/static/js/vendors~app.ab650e77.chunk.js:1:753765)
    at t.render (https://codesandbox.io/static/js/vendors~app.ab650e77.chunk.js:1:753863)
    at vs (https://codesandbox.io/static/js/common.753a9000.chunk.js:1:2061093)
    at ms (https://codesandbox.io/static/js/common.753a9000.chunk.js:1:2060886)
    at Ka (https://codesandbox.io/static/js/common.753a9000.chunk.js:1:2095282)
    at Fa (https://codesandbox.io/static/js/common.753a9000.chunk.js:1:2079648)
    at Na (https://codesandbox.io/static/js/common.753a9000.chunk.js:1:2076668)
    at Ra (https://codesandbox.io/static/js/common.753a9000.chunk.js:1:2075228)
    at https://codesandbox.io/static/js/common.753a9000.chunk.js:1:2037129

    in t
    in Unknown
    in r
    in t
    in t
    in Unknown
    in t
    in withRouter()
    in div
    in t
    in elements__Content
    in div
    in div
    in t
    in elements__Container
    in n
    in r
    in t
    in withRouter(r)
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in r
    in t
    in withRouter(r)
    in DragDropContext(withRouter(r))
    in t
    in t
    in l
    in t
```

</details>

**Comment by MichaelDeBoey** [comment]
Closed by #2460
