### ISSUE TITLE
💥 Crash Report: <Please Add a Short Description of Crash Circumstances>

### ISSUE THREAD

**Issue by Barik85** [codesandbox/codesandbox-client#2467]
<h1>💥 Crash Report</h1>

<h2>Login with github after changing password on github account</h2>

> Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

<h3>Link to sandbox: [https://codesandbox.io/dashboard/recent]() (optional)</h3>

<h3>After refresh page everything is ok!</h3>

<details>
<summary>Environment</summary>

| Browser |  Version  | Operating System |
| ------- | --------- | ---------------- |
| chrome | 76.0.3809 | OS X 10.14.6           |

**Route:**
https://codesandbox.io/dashboard/recent

</details>

<details>
<summary>Error Message</summary>

```bash
TypeError: Cannot read property 'sandboxes' of undefined
TypeError: Cannot read property 'sandboxes' of undefined
    at Object.children (https://codesandbox.io/static/js/app.c16e8532.js:438:220782)
    at n (https://codesandbox.io/static/js/vendors~app.ab650e77.chunk.js:1:753765)
    at t.render (https://codesandbox.io/static/js/vendors~app.ab650e77.chunk.js:1:753863)
    at vs (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2062663)
    at ms (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2062456)
    at Ka (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2096852)
    at Fa (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2081218)
    at Na (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2078238)
    at Ra (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2076798)
    at https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038699
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2113545)
    at co (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038428)
    at po (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038645)
    at ho (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038580)
    at Oa (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2075789)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2043434)
    at r.w.setState (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2335598)
    at https://codesandbox.io/static/js/default~app~embed.d9388ce5.chunk.js:276:352224
    at e.callback (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:1467513)
    at h.flush (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:1470358)
    at d.flush (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:1466658)
    at Object.cb (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:1355036)
    at e.emit (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:1351431)
    at https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:1357198
    at Proxy.<anonymous> (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:1356253)
    at https://codesandbox.io/static/js/default~app~embed.d9388ce5.chunk.js:276:238912
    at a (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:14585)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:14373)
    at Generator.next (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:15007)
    at t (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:8537)
    at u (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:8747)

    in t
    in Unknown
    in r
    in t
    in t
    in Unknown
    in t
    in withRouter()
    in div
    in t
    in elements__Content
    in div
    in div
    in t
    in elements__Container
    in n
    in r
    in t
    in withRouter(r)
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in r
    in t
    in withRouter(r)
    in DragDropContext(withRouter(r))
    in t
    in t
    in l
    in t
```

</details>

**Comment by yeion7** [comment]
This issue was fixed on #2460
