### ISSUE TITLE
💥 Crash Report: <Please Add a Short Description of Crash Circumstances>

### ISSUE THREAD

**Issue by Jstop11** [codesandbox/codesandbox-client#2482]
<h1>💥 Crash Report</h1>

<h2>What were you trying to accomplish when the crash occurred?</h2>

> Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

<h3>Link to sandbox: [link]() (optional)</h3>

<h3>Crash Details</h3>

<details>
<summary>Environment</summary>

| Browser |  Version  | Operating System |
| ------- | --------- | ---------------- |
| chrome | 76.0.3809 | Windows 10           |

**Route:**
https://codesandbox.io/dashboard/templates

</details>

<details>
<summary>Error Message</summary>

```bash
TypeError: Cannot read property 'teams' of undefined
TypeError: Cannot read property 'teams' of undefined
    at Object.children (https://codesandbox.io/static/js/app.c23775ad.js:438:183103)
    at n (https://codesandbox.io/static/js/vendors~app.ab650e77.chunk.js:1:753765)
    at t.render (https://codesandbox.io/static/js/vendors~app.ab650e77.chunk.js:1:753863)
    at vs (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2062663)
    at ms (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2062456)
    at Ka (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2096852)
    at Fa (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2081218)
    at Na (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2078238)
    at Ra (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2076798)
    at https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038699
    at https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2113545
    at co (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038428)
    at po (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038645)
    at ho (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038580)
    at Ia (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2077225)
    at https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2028067
    at HTMLDocument.r (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:122867)

    in t
    in Unknown
    in r
    in t
    in aside
    in t
    in elements__SidebarStyled
    in n
    in r
    in t
    in withRouter(r)
    in div
    in t
    in elements__Sidebar
    in div
    in div
    in t
    in elements__Container
    in n
    in r
    in t
    in withRouter(r)
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in r
    in t
    in withRouter(r)
    in DragDropContext(withRouter(r))
    in t
    in t
    in l
    in t
```

</details>

**Comment by SaraVieira** [comment]
closed by #2483
