### ISSUE TITLE
Failed to execute 'observe' on 'MutationObserver'

### ISSUE THREAD

**Issue by codeocelot** [codesandbox/codesandbox-client#2507]
# 🐛 bug report

## Description of the problem

This one's really strange.  Calling `redux-saga-tester` SagaTester constructor will throw an exception complaining about `Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.` (full stack trace below).  The issue doesn't appear when I import it from a copy-paste of the original source.

<details>
<summary>Full Stack Trace </summary>
<pre>
Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.

TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at module.exports (https://w0slq.csb.app/node_modules/core-js/library/modules/_microtask.js:37:25)
    at evaluate (https://w0slq.csb.app/node_modules/core-js/library/modules/es6.promise.js:13:40)
    at $n (https://codesandbox.io/static/js/sandbox.a28300af.js:1:148657)
    at e.value (https://codesandbox.io/static/js/sandbox.a28300af.js:1:163921)
    at e.value (https://codesandbox.io/static/js/sandbox.a28300af.js:1:203468)
    at t (https://codesandbox.io/static/js/sandbox.a28300af.js:1:163663)
    at evaluate (https://w0slq.csb.app/node_modules/core-js/library/fn/promise.js:4:1)
    at $n (https://codesandbox.io/static/js/sandbox.a28300af.js:1:148657)
    at e.value (https://codesandbox.io/static/js/sandbox.a28300af.js:1:163921)
    at e.value (https://codesandbox.io/static/js/sandbox.a28300af.js:1:203468)
    at t (https://codesandbox.io/static/js/sandbox.a28300af.js:1:163663)
    at evaluate (https://w0slq.csb.app/node_modules/babel-runtime/core-js/promise.js:1:227)
    at $n (https://codesandbox.io/static/js/sandbox.a28300af.js:1:148657)
    at e.value (https://codesandbox.io/static/js/sandbox.a28300af.js:1:163921)
    at e.value (https://codesandbox.io/static/js/sandbox.a28300af.js:1:203468)
    at t (https://codesandbox.io/static/js/sandbox.a28300af.js:1:163663)
    at evaluate (https://w0slq.csb.app/node_modules/redux-saga-tester/dist/SagaTester.js:8:16)
    at $n (https://codesandbox.io/static/js/sandbox.a28300af.js:1:148657)
    at e.value (https://codesandbox.io/static/js/sandbox.a28300af.js:1:163921)
    at e.value (https://codesandbox.io/static/js/sandbox.a28300af.js:1:203468)
    at t (https://codesandbox.io/static/js/sandbox.a28300af.js:1:163663)
    at evaluate (https://w0slq.csb.app/src/index.test.js:9:47)
    at $n (https://codesandbox.io/static/js/sandbox.a28300af.js:1:148657)
    at e.value (https://codesandbox.io/static/js/sandbox.a28300af.js:1:163921)
    at e.value (https://codesandbox.io/static/js/sandbox.a28300af.js:1:203468)
    at e.value (https://codesandbox.io/static/js/sandbox.a28300af.js:1:203066)
    at https://codesandbox.io/static/js/sandbox.a28300af.js:1:192191
    at a (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:14585)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:14373)
    at Generator.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:15007)
    at t (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:8537)
    at u (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:8747)
    at https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:8806
    at new Promise (<anonymous>)
    at https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:8688
    at https://codesandbox.io/static/js/sandbox.a28300af.js:1:192536
    at Array.map (<anonymous>)
    at e.<anonymous> (https://codesandbox.io/static/js/sandbox.a28300af.js:1:191909)
    at a (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:14585)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:14373)
    at Generator.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:15007)
    at t (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:8537)
    at u (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:8747)
</pre>
</details>

Note that I can reproduce the issue only by including the minified version of the dependency in the app, the original source is unaffected.

I'd dive further into the problem, but the entire stacktrace is within your editor's minified js so I'm at a loss.

Reproduction Steps:

- Open [this sandbox](https://codesandbox.io/s/serene-sun-w0slq)
- Navigate to `index.test.js`.
- Uncomment `import ... from 'redux-saga-tester'`, comment out `import ... from './SagaTester'`
- Note the error in the test tab
- Comment out `import ... from 'redux-saga-tester`, uncomment `import ... from './SagaTester`
- Note the error won't appear and the test passes.
- Uncomment out `import ... from './SagaTester.min'` 
- Note the error occurs.

## How has this issue affected you? What are you trying to accomplish?

I was trying to write a test case using `redux-saga-tester`, a really thin abstraction used to assert correctness for sagas.  Not the end of the world, but I can't see a reason why this dependency throws this exception when it works fine in every other environment I've thrown at it.

I'm not a maintainer or otherwise related to the dependency.  Just a helpful user curious for a resolution.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | browser (https://codesandbox.io/)
| Browser          | Chrome 77.0.3865.90 
| Operating System | macOS Mojave 10.14.6 (18G95)

**Comment by mediafreakch** [comment]
Same issue here, but with an unknown source package (maybe `@testing-library/vue`?):
[Codesandbox](https://codesandbox.io/embed/blue-microservice-u3j80?fontsize=14&hidenavigation=1&previewwindow=tests&theme=dark)
