### ISSUE TITLE
💥 Crash Report: <Please Add a Short Description of Crash Circumstances>

### ISSUE THREAD

**Issue by Dieber** [codesandbox/codesandbox-client#2517]
<h1>💥 Crash Report</h1>

<h2>What were you trying to accomplish when the crash occurred?</h2>

> Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

<h3>Link to sandbox: [link]() (optional)</h3>

<h3>Crash Details</h3>

<details>
<summary>Environment</summary>

| Browser |  Version  | Operating System |
| ------- | --------- | ---------------- |
| chrome | 77.0.3865 | Windows 10           |

**Route:**
https://codesandbox.io/s/interesting-ardinghelli-87uhx

</details>

<details>
<summary>Error Message</summary>

```bash
TypeError: Cannot read property 'id' of undefined
TypeError: Cannot read property 'id' of undefined
    at n.value (https://codesandbox.io/static/js/app.72781e2a.js:438:316348)
    at https://codesandbox.io/static/js/default~app~embed.e9bc0e97.chunk.js:276:351897
    at f.trackScope (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:1467837)
    at n.<anonymous> (https://codesandbox.io/static/js/default~app~embed.e9bc0e97.chunk.js:276:351866)
    at vs (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2062663)
    at ms (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2062456)
    at Ka (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2096852)
    at Fa (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2081218)
    at Na (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2078238)
    at Ra (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2076798)
    at https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038699
    at https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2113545
    at co (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038428)
    at po (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038645)
    at ho (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038580)
    at Oa (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2075789)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2043434)
    at r.setState (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2335598)
    at https://codesandbox.io/static/js/default~app~embed.e9bc0e97.chunk.js:276:352284
    at https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:1467513
    at h.flush (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:1470358)
    at d.flush (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:1466658)
    at Object.cb (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:1355036)
    at e.emit (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:1351431)
    at editor.internal.setCurrentModule (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:1357198)
    at Proxy.<anonymous> (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:1356253)
    at https://codesandbox.io/static/js/default~app~embed.e9bc0e97.chunk.js:276:330988
    at a (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:14585)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:14373)
    at Generator.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:15007)
    at t (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:8537)
    at u (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:8747)

    in n
    in r
    in div
    in t
    in elements__Opener
    in div
    in n
    in r
    in DropTarget(r)
    in n
    in r
    in div
    in files
    in div
    in div
    in t
    in elements__Container
    in Unknown
    in r
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in n
    in r
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in r
    in t
    in withRouter(r)
    in DragDropContext(withRouter(r))
    in t
    in t
    in l
    in t
```

</details>

**Comment by SaraVieira** [comment]
Hey!

Can you tell me what steps you took to get this error?
