### ISSUE TITLE
💥 Crash Report: failed when adding @agm/core

### ISSUE THREAD

**Issue by doom777** [codesandbox/codesandbox-client#2518]
<h1>💥 Crash Report</h1>

<h2>What were you trying to accomplish when the crash occurred?</h2>

> Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

<h3>Link to sandbox: [link]() (optional)</h3>

<h3>Crash Details</h3>

<details>
<summary>Environment</summary>

| Browser |  Version  | Operating System |
| ------- | --------- | ---------------- |
| chrome | 77.0.3865 | Windows 10           |

**Route:**
https://codesandbox.io/s/angular-755k5

</details>

<details>
<summary>Error Message</summary>

```bash
TypeError: Cannot read property 'id' of undefined
TypeError: Cannot read property 'id' of undefined
    at Object.frameUrl (https://codesandbox.io/static/js/default~app~embed~sandbox.a852bcbc.chunk.js:1:97527)
    at v.currentUrl (https://codesandbox.io/static/js/default~app~embed.e9bc0e97.chunk.js:128:1610)
    at https://codesandbox.io/static/js/default~app~embed.e9bc0e97.chunk.js:128:7089
    at t.render (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2241923)
    at vs (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2062663)
    at ms (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2062456)
    at Ka (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2096852)
    at Fa (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2081218)
    at Na (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2078238)
    at Ra (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2076798)
    at https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038699
    at https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2113545
    at co (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038428)
    at po (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038645)
    at ho (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038580)
    at Oa (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2075789)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2043434)
    at t.<anonymous> (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2335598)
    at Object.updateStatus (https://codesandbox.io/static/js/default~app~embed.e9bc0e97.chunk.js:276:163849)
    at Object.<anonymous> (https://codesandbox.io/static/js/default~app~embed.e9bc0e97.chunk.js:276:155429)
    at https://codesandbox.io/static/js/default~app~embed~sandbox.a852bcbc.chunk.js:1:6473
    at Array.forEach (<anonymous>)
    at _ (https://codesandbox.io/static/js/default~app~embed~sandbox.a852bcbc.chunk.js:1:6443)
    at k (https://codesandbox.io/static/js/default~app~embed~sandbox.a852bcbc.chunk.js:1:6552)

    in t
    in div
    in t
    in styled.div
    in v
    in n
    in r
    in Content
    in div
    in t
    in elements__ContentContainer
    in div
    in t
    in elements__Container
    in t
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in n
    in r
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in n
    in r
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in r
    in t
    in withRouter(r)
    in DragDropContext(withRouter(r))
    in t
    in t
    in l
    in t
```

</details>

**Comment by SaraVieira** [comment]
Hey

Can you please tell me the steps you did?

It seems to work okay: https://codesandbox.io/s/angular-h07c2

**Comment by doom777** [comment]
Browser: Brave

1. Open codesandbox.io
1. Click Create Angular Sandbox
1. Let it load and transpile
1. Click Add Dependency in left panel
1. Type `@agm/core` in search box in dependency dialog and click enter
1. Click on first result `@agm/core`
1. Starts transpiling ,and then offers crash.


One the day I reported, it would crash every time. Today, it only crashed the first time, but subsequent times it worked

**Comment by SaraVieira** [comment]
Interesting, I'm gonna download brave and get back to you

**Comment by doom777** [comment]
?

**Comment by SaraVieira** [comment]
Sorry for the late response but at the time I didn't get this issue

Is it still happening?

**Comment by doom777** [comment]
No
