### ISSUE TITLE
💥 Crash Report: React app crashes constantly while writing tests

### ISSUE THREAD

**Issue by sa-ma** [codesandbox/codesandbox-client#2581]
<h1>💥 React app crashes constantly while writing tests</h1>

<h2>What were you trying to accomplish when the crash occurred?</h2>

> The code sandbox environment crashes at intervals while writing tests. I suspect it's because the tests are running in watch mode and it literally is running my tests while I type

Link to sandbox:  [Sandbox](https://codesandbox.io/s/ecstatic-forest-tdcvy) 

<h3>Crash Details</h3>

<details>
<summary>Environment</summary>

| Browser |  Version  | Operating System |
| ------- | --------- | ---------------- |
| chrome | 77.0.3865 | Linux x86_64           |

**Route:**
https://codesandbox.io/s/ecstatic-forest-tdcvy

</details>

<details>
<summary>Error Message</summary>

```bash
TypeError: Cannot read property 'tests' of undefined
TypeError: Cannot read property 'tests' of undefined
    at https://codesandbox.io/static/js/default~app~embed.e9bc0e97.chunk.js:276:157608
    at F.produce (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:1098249)
    at t.<anonymous> (https://codesandbox.io/static/js/default~app~embed.e9bc0e97.chunk.js:276:157571)
    at Io (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2041527)
    at Po (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2041788)
    at ms (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2061422)
    at Ka (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2096852)
    at Fa (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2081218)
    at Na (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2078238)
    at Ra (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2076798)
    at https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038699
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2113545)
    at co (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038428)
    at po (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038645)
    at ho (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038580)
    at Oa (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2075789)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2043434)
    at t.w.setState (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2335598)
    at Object.<anonymous> (https://codesandbox.io/static/js/default~app~embed.e9bc0e97.chunk.js:276:157531)
    at https://codesandbox.io/static/js/default~app~embed~sandbox.a852bcbc.chunk.js:1:6473
    at Array.forEach (<anonymous>)
    at _ (https://codesandbox.io/static/js/default~app~embed~sandbox.a852bcbc.chunk.js:1:6443)
    at k (https://codesandbox.io/static/js/default~app~embed~sandbox.a852bcbc.chunk.js:1:6552)

    in t
    in div
    in t
    in elements__ContentContainer
    in div
    in t
    in elements__Container
    in t
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in n
    in r
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in n
    in r
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in r
    in t
    in withRouter(r)
    in DragDropContext(withRouter(r))
    in t
    in t
    in l
    in t
```

</details>

**Comment by lakhansamani** [comment]
@sa-ma Link to sandbox gives 404 error

**Comment by sa-ma** [comment]
> @sa-ma Link to sandbox gives 404 error
Sorry about that. It is working now

**Comment by CompuIves** [comment]
This one should be easier to fix by adding a check. It's a race condition for sure somewhere in `Tests/index.tsx`.

**Comment by Shriram-Balaji** [comment]
@CompuIves I'd like to take this up :smile:
