### ISSUE TITLE
💥 Crash Report: Installing `resize-base64` on Vanilla JS break the app

### ISSUE THREAD

**Issue by Kmaschta** [codesandbox/codesandbox-client#2584]
<h1>💥 Crash Report</h1>

<h2>What were you trying to accomplish when the crash occurred?</h2>

1. On a Vanilla JS codesandbox
2. Click on the `Add a Dependency` button
3. Search for the package `resize-base64` and click on it

<h3>Crash Details</h3>

![image](https://user-images.githubusercontent.com/1819833/65868040-d2471d00-e377-11e9-8943-2ad2667a84d5.png)

<details>
<summary>Environment</summary>

| Browser |  Version  | Operating System |
| ------- | --------- | ---------------- |
| chrome | 77.0.3865 | Linux x86_64           |

**Route:**
https://codesandbox.io/s/elated-forest-1yjv1

</details>

<details>
<summary>Error Message</summary>

```bash
TypeError: Cannot read property 'id' of undefined
TypeError: Cannot read property 'id' of undefined
    at Object.frameUrl (https://codesandbox.io/static/js/default~app~embed~sandbox.a852bcbc.chunk.js:1:97527)
    at v.currentUrl (https://codesandbox.io/static/js/default~app~embed.e9bc0e97.chunk.js:128:1610)
    at https://codesandbox.io/static/js/default~app~embed.e9bc0e97.chunk.js:128:7089
    at t.render (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2241923)
    at vs (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2062663)
    at ms (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2062456)
    at Ka (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2096852)
    at Fa (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2081218)
    at Na (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2078238)
    at Ra (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2076798)

    in t
    in div
    in t
    in styled.div
    in v
    in n
    in r
    in Content
    in div
    in t
    in elements__ContentContainer
    in div
    in t
    in elements__Container
    in t
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in n
    in r
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in n
    in r
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in r
    in t
    in withRouter(r)
    in DragDropContext(withRouter(r))
    in t
    in t
    in l
    in t
```

</details>

**Comment by SaraVieira** [comment]
Hey!

Justed tested it and seems to have been fixed in the meantime
