### ISSUE TITLE
It doesn't load angular project after uploading

### ISSUE THREAD

**Issue by RezaRahmati** [codesandbox/codesandbox-client#2587]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [https://codesandbox.io/s/simple-array-devextreme-data-grid-no2kx](https://codesandbox.io/s/simple-array-devextreme-data-grid-no2kx) (optional)</h3>

  <h3>Crash Details</h3>
  It doesn't load angular project and keep showing "Loading...", it happens after updating code sandbox from the alert message
  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 75.0.3770 | Windows 10           |

  **Route:**
  https://codesandbox.io/s/dg3qg

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'integrations' of null
  TypeError: Cannot read property 'integrations' of null
    at github (https://codesandbox.io/static/js/app.b5d0b36a.js:438:406521)
    at Li (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2052403)
    at Ka (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2095495)
    at Fa (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2081218)
    at Na (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2078238)
    at Ra (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2076798)
    at https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038699
    at https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2113545
    at co (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038428)
    at po (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038645)
    at ho (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038580)
    at Ia (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2077225)
    at https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2028067
    at HTMLDocument.r (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:122867)
  
    in github
    in div
    in div
    in t
    in elements__Container
    in jd
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in n
    in r
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in r
    in t
    in withRouter(r)
    in DragDropContext(withRouter(r))
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by CompuIves** [comment]
Heyo! Does this still happen for you? I was able to run the sandbox and see the grid this time.
