### ISSUE TITLE
Live session crash report

### ISSUE THREAD

**Issue by wmain** [codesandbox/codesandbox-client#2598]
<h1>💥 Crash Report</h1>

  <h2>Join a live session</h2>

  <h3>Link to sandbox: https://codesandbox.io/live/nZY8K4() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 77.0.3865 | OS X 10.14.5           |

  **Route:**
  https://codesandbox.io/live/nZY8K4

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'editorService' of undefined
  TypeError: Cannot read property 'editorService' of undefined
    at t.destroyMonaco (https://codesandbox.io/static/js/default~app~embed.df990aeb.chunk.js:276:41612)
    at t.value (https://codesandbox.io/static/js/default~app~embed.df990aeb.chunk.js:276:42384)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2070092
    at Is (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2070133)
    at Ps (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2070214)
    at zs (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2071898)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2090729
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2113916)
    at co (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038799)
    at Ua (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2088532)
    at Ra (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2077169)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039070
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2113916)
    at co (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038799)
    at po (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039016)
    at ho (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038951)
    at Oa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2076160)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2043805)
    at r.w.setState (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2335969)
    at https://codesandbox.io/static/js/default~app~embed.df990aeb.chunk.js:276:354623
    at e.callback (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1467884)
    at h.flush (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1470729)
    at d.flush (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1467029)
    at Object.cb (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1355213)
    at e.emit (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1351588)
    at internal.setCurrentSandbox (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1357380)
    at Proxy.<anonymous> (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1356480)
    at https://codesandbox.io/static/js/default~app~embed.df990aeb.chunk.js:276:301829
    at a (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:14585)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:14373)
    at Generator.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:15007)
    at t (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:8537)
    at u (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:8747)
  
    in t
    in div
    in t
    in elements__Container
    in t
    in div
    in t
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in n
    in r
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in n
    in r
    in n
    in r
    in n
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in r
    in t
    in withRouter(r)
    in DragDropContext(withRouter(r))
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by CompuIves** [comment]
Sorry about this! Should be fixed now!
