### ISSUE TITLE
SVG upload caused crash

### ISSUE THREAD

**Issue by gokhantaskan** [codesandbox/codesandbox-client#2614]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > I tried to upload an SVG to "img" directory. It crashed instantly.

  <h3>Sandbox: https://codesandbox.io/s/vue-template-3owq0</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 77.0.3865 | Windows 10           |

  **Route:**
  https://codesandbox.io/s/vue-template-3owq0

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'length' of undefined
  TypeError: Cannot read property 'length' of undefined
    at n.value (https://codesandbox.io/static/js/app.424d65f7.js:438:318893)
    at https://codesandbox.io/static/js/default~app~embed.b9c0f482.chunk.js:276:353723
    at f.trackScope (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1468208)
    at n.<anonymous> (https://codesandbox.io/static/js/default~app~embed.b9c0f482.chunk.js:276:353692)
    at vs (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2063034)
    at ms (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2062827)
    at Ka (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2097223)
    at Fa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2081589)
    at Na (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2078609)
    at Ra (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2077169)
  
    in n
    in r
    in div
    in n
    in r
    in div
    in t
    in elements__Opener
    in div
    in n
    in r
    in DropTarget(r)
    in div
    in n
    in r
    in div
    in t
    in elements__Opener
    in div
    in n
    in r
    in DropTarget(r)
    in div
    in n
    in r
    in div
    in t
    in elements__Opener
    in div
    in n
    in r
    in DropTarget(r)
    in div
    in n
    in r
    in div
    in t
    in elements__Opener
    in div
    in n
    in r
    in DropTarget(r)
    in n
    in r
    in div
    in files
    in div
    in div
    in t
    in elements__Container
    in jd
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in n
    in r
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in r
    in t
    in withRouter(r)
    in DragDropContext(withRouter(r))
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by lbogdan** [comment]
Hey @gokhantaskan ,

I just looked at your sandbox, and noticed it contains an `.svg` file, did you manage to upload it? If this is not an issue for you anymore, we'd appreciate if you closed this. Thanks!
