### ISSUE TITLE
Crash when expanding My Sandboxes

### ISSUE THREAD

**Issue by aschokking** [codesandbox/codesandbox-client#2636]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

 I think I must have had a corrupt login state or something, I hadn't visited the site in a while and after the crash I refreshed and was asked to sign in again and this time it worked.

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 76.0.3809 | OS X 10.14.6           |

  **Route:**
  https://codesandbox.io/dashboard/sandboxes

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'collections' of undefined
  TypeError: Cannot read property 'collections' of undefined
    at Object.children (https://codesandbox.io/static/js/app.e345c11d.js:438:277408)
    at n (https://codesandbox.io/static/js/vendors~app.ab650e77.chunk.js:1:753765)
    at t.render (https://codesandbox.io/static/js/vendors~app.ab650e77.chunk.js:1:753863)
    at vs (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2063034)
    at ms (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2062827)
    at Ka (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2097223)
    at Fa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2081589)
    at Na (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2078609)
    at Ra (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2077169)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039070
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2113916)
    at co (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038799)
    at po (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039016)
    at ho (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038951)
    at Ia (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2077596)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2028438
    at HTMLDocument.r (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:122867)
  
    in t
    in div
    in t
    in t
    in n
    in div
    in n
    in t
    in withRouter(n)
    in DropTarget(withRouter(n))
    in div
    in t
    in elements__Items
    in Unknown
    in r
    in t
    in aside
    in t
    in elements__SidebarStyled
    in n
    in r
    in t
    in withRouter(r)
    in div
    in t
    in elements__Sidebar
    in div
    in div
    in t
    in elements__Container
    in n
    in r
    in t
    in withRouter(r)
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in r
    in t
    in withRouter(r)
    in DragDropContext(withRouter(r))
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by CompuIves** [comment]
Hey @aschokking! Does this also happen after a refresh? It might be a wrong sign in state, like you mentioned. I think we fixed this in a later version.

**Comment by CompuIves** [comment]
Hey @aschokking! Does this also happen after a refresh? It might be a wrong sign in state, like you mentioned. I think we fixed this in a later version.

**Comment by aschokking** [comment]
Haven't been able to repro again since the refresh, probably fixed. Just wanted to share the stack trace in case it was informative.
