### ISSUE TITLE
Crashed on save

### ISSUE THREAD

**Issue by Chrismis79** [codesandbox/codesandbox-client#2668]
<h1>💥 Crash Report</h1>

  <h2>I Saved, nothing rendered, then crashed</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>https://codesandbox.io/s/gifted-hooks-b5f3o</h3>

  <h3>Saved, nothing rendered, then crashed</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 77.0.3865 | Windows 10           |

  **Route:**
  https://codesandbox.io/s/gifted-hooks-b5f3o

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'id' of undefined
  TypeError: Cannot read property 'id' of undefined
    at Object.t.frameUrl (https://codesandbox.io/static/js/default~app~embed~sandbox.a852bcbc.chunk.js:1:97527)
    at v.currentUrl (https://codesandbox.io/static/js/default~app~embed.74f884b7.chunk.js:128:1610)
    at https://codesandbox.io/static/js/default~app~embed.74f884b7.chunk.js:128:7089
    at t.n.render (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2242294)
    at vs (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2063034)
    at ms (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2062827)
    at Ka (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2097223)
    at Fa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2081589)
    at Na (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2078609)
    at Ra (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2077169)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039070
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2113916)
    at co (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038799)
    at po (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039016)
    at ho (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038951)
    at Ia (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2077596)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2028438
    at HTMLDocument.r (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:122867)
  
    in t
    in div
    in t
    in styled.div
    in v
    in n
    in r
    in Content
    in div
    in t
    in elements__ContentContainer
    in div
    in t
    in elements__Container
    in t
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in n
    in r
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in n
    in r
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in r
    in t
    in withRouter(r)
    in DragDropContext(withRouter(r))
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by mkamranhamid** [comment]
Can you please add what Node and Yarn versions you are using?

**Comment by Chrismis79** [comment]
Node: v10.16.0
Yarn: 1.17.3

**Comment by mkamranhamid** [comment]
Please follow [this](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md) guideline for development purpose 
> make sure you have latest yarn version

**Comment by lbogdan** [comment]
Looks like `sandbox` is `undefined` here:
https://github.com/codesandbox/codesandbox-client/blob/43d96d5957d164b3ab0e368182633958a0a21d89/packages/common/src/utils/url-generator.ts#L115

**Comment by lbogdan** [comment]
Looks like this wasn't addressed in the meantime, but it neither happened lately, so I'm going to close it for now.
