### ISSUE TITLE
A crash after adding vue-pixi library from nuxt.js sandbox.

### ISSUE THREAD

**Issue by yeoupooh** [codesandbox/codesandbox-client#2694]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 77.0.3865 | Windows 10           |

  **Route:**
  https://codesandbox.io/s/codesandbox-nuxt-lztsw

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'template' of undefined
  TypeError: Cannot read property 'template' of undefined
    at wd (https://codesandbox.io/static/js/app.e345c11d.js:438:405340)
    at Li (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2052774)
    at ps (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2059858)
    at Ka (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2097141)
    at Fa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2081589)
    at Na (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2078609)
    at Ra (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2077169)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039070
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2113916)
    at co (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038799)
    at po (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039016)
    at ho (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038951)
    at Oa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2076160)
    at Yi (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2055907)
    at forceRerender (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1347315)
    at e.callback (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1467884)
    at h.flush (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1470729)
    at d.flush (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1467029)
    at Object.cb (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1355213)
    at e.emit (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1351588)
    at server.onSSEMessage (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1357380)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1356480
    at h.<anonymous> (https://codesandbox.io/static/js/default~app~embed.74f884b7.chunk.js:276:234361)
    at h.r.emit (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:660685)
    at h.emit (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2401585)
    at h.onconnect (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2403452)
    at h.onpacket (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2402608)
    at h.<anonymous> (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:659603)
    at h.r.emit (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:660685)
    at h.ondecoded (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2397496)
    at d.<anonymous> (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:659603)
    at d.r.emit (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:660685)
    at d.add (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2413465)
    at h.ondata (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2397449)
    at u.<anonymous> (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:659603)
    at u.r.emit (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:660685)
    at u.onPacket (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:832421)
    at f.<anonymous> (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:830033)
    at f.r.emit (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:660685)
    at f.i.onPacket (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:837013)
    at f.i.onData (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:836962)
    at WebSocket.ws.onmessage (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:849625)
  
    in wd
    in div
    in t
    in elements__Container
    in jd
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in n
    in r
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in r
    in t
    in withRouter(r)
    in DragDropContext(withRouter(r))
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by CompuIves** [comment]
Sorry for this! The issue should be resolved now.
