### ISSUE TITLE
Cash after the update

### ISSUE THREAD

**Issue by LasCC** [codesandbox/codesandbox-client#2698]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 77.0.3865 | Windows 10           |

  **Route:**

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
  Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at el (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2101469)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2050662
    at cs (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2058892)
    at Ka (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2097893)
    at Fa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2081589)
    at Na (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2078609)
    at Ra (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2077169)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039070
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2113916)
    at co (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038799)
    at po (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039016)
    at ho (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038951)
    at Oa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2076160)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2043805)
    at r.w.setState (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2335969)
    at https://codesandbox.io/static/js/default~app~embed.589fb797.chunk.js:276:354955
    at e.callback (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1467884)
    at h.flush (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1470729)
    at d.flush (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1467029)
    at Object.cb (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1355213)
    at e.emit (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1351588)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1357160
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1353003
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1358873
    at r (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1352552)
    at i (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1358647)
    at t (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1358684)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1357043
    at new Promise (<anonymous>)
    at live.liveMessageReceived (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1357023)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1356480
    at e.onMessage (https://codesandbox.io/static/js/default~app~embed.589fb797.chunk.js:276:212631)
    at e.value (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1430333)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1436139
    at Array.forEach (<anonymous>)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1436110
    at e.decode (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1431114)
    at e.value (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1435840)
    at WebSocket.conn.conn.onmessage (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1433050)
  
    in div
    in t
    in elements__ChildContainer
    in div
    in t
    in n
    in div
    in files
    in div
    in div
    in t
    in elements__Container
    in jd
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in n
    in r
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by CompuIves** [comment]
Sorry for this! The issue should be resolved now.
