### ISSUE TITLE
New Sandbox save/fork crash

### ISSUE THREAD

**Issue by przelu** [codesandbox/codesandbox-client#2702]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

Just created a new React sandbox and tried to save/fork it.   A couple of minutes before I saw this toast notification that there was a new version and I have clicked to install it / reloaded the page.  I am also not able to open the sandbox I have just created.

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 77.0.3865 | Windows 10           |

  **Route:**
  https://codesandbox.io/s/cool-cookies-x9qne

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
  Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at el (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2101469)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2050662
    at cs (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2058892)
    at Ka (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2097893)
    at Fa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2081589)
    at Na (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2078609)
    at Ra (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2077169)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039070
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2113916
    at co (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038799)
    at po (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039016)
    at ho (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038951)
    at Oa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2076160)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2043805)
    at t.setState (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2335969)
    at https://codesandbox.io/static/js/vendors~app.873bb633.chunk.js:1:1402666
    at r (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1063373)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1063597
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1063568)
    at x (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1060166)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1061143
    at Object.confirmTransitionTo (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1063312)
    at Object.R [as push] (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1060915)
    at Object.updateSandboxUrl (https://codesandbox.io/static/js/default~app~embed.589fb797.chunk.js:276:216804)
    at https://codesandbox.io/static/js/default~app~embed.589fb797.chunk.js:276:275502
    at a (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:14585)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:14373)
    at Generator.next (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:15007)
    at t (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:8537)
    at u (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:8747)
  
    in div
    in t
    in elements__ChildContainer
    in div
    in t
    in n
    in div
    in files
    in div
    in div
    in t
    in elements__Container
    in jd
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in n
    in r
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by przelu** [comment]
Just saw another update and it all seems okay now. Thank you.
