### ISSUE TITLE
Crash when adding react-redux 7.1.1 to default  react sandbox

### ISSUE THREAD

**Issue by TaraMcC** [codesandbox/codesandbox-client#2703]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 77.0.3865 | Windows Server 2008 R2 / 7           |

  **Route:**
  https://codesandbox.io/s/brave-tdd-f9gv1

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
  Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at el (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2101469)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2050662
    at cs (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2058892)
    at Ka (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2097893)
    at Fa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2081589)
    at Na (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2078609)
    at Ra (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2077169)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039070
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2113916)
    at co (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038799)
    at po (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039016)
    at ho (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038951)
    at Oa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2076160)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2043805)
    at t.w.setState (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2335969)
    at https://codesandbox.io/static/js/vendors~app.873bb633.chunk.js:1:1402666
    at r (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1063373)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1063597
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1063568)
    at x (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1060166)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1061143
    at Object.confirmTransitionTo (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1063312)
    at Object.R [as push] (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1060915)
    at Object.updateSandboxUrl (https://codesandbox.io/static/js/default~app~embed.589fb797.chunk.js:276:216804)
    at https://codesandbox.io/static/js/default~app~embed.589fb797.chunk.js:276:275502
    at a (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:14585)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:14373)
    at Generator.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:15007)
    at t (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:8537)
    at u (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:8747)
  
    in div
    in t
    in elements__ChildContainer
    in div
    in t
    in n
    in div
    in files
    in div
    in div
    in t
    in elements__Container
    in jd
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in n
    in r
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by CompuIves** [comment]
Sorry for this! The issue should be resolved now.
