### ISSUE TITLE
Crash Patron page

### ISSUE THREAD

**Issue by Ajdija** [codesandbox/codesandbox-client#2705]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 77.0.3865 | OS X 10.14.6           |

  **Route:**
  https://codesandbox.io/patron

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  RangeError: Invalid time value
  RangeError: Invalid time value
    at B (https://codesandbox.io/static/js/vendors~app.873bb633.chunk.js:1:1708479)
    at https://codesandbox.io/static/js/page-patron.8bb24fc5.chunk.js:1:9694
    at https://codesandbox.io/static/js/default~app~embed.46b425ab.chunk.js:276:355544
    at f.trackScope (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1468208)
    at https://codesandbox.io/static/js/default~app~embed.46b425ab.chunk.js:276:355513
    at Li (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2052774)
    at Ka (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2095866)
    at Fa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2081589)
    at Na (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2078609)
    at Ra (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2077169)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039070
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2113916
    at co (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038799)
    at po (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039016)
    at ho (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038951)
    at Oa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2076160)
    at Yi (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2055907)
    at forceRerender (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1347315)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1467884
    at h.flush (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1470729)
    at d.flush (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1467029)
    at Object.cb (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1355213)
    at e.emit (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1351588)
    at internal.setPatronPrice (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1357380)
    at Proxy.<anonymous> (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1356480)
    at https://codesandbox.io/static/js/default~app~embed.46b425ab.chunk.js:276:237521
    at a (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:14585)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:14373)
    at Generator.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:15007)
    at t (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:8537)
    at u (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:8747)
  
    in Unknown
    in r
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in Ue
    in div
    in t
    in elements__Details
    in div
    in t
    in elements__Container
    in bn
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in Unknown
    in div
    in t
    in elements__Content
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in Unknown
    in Unknown
    in n
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by garethx** [comment]
Thanks for reporting. We've a fix going out for this. See https://github.com/codesandbox/codesandbox-client/compare/337b44fbb31d...f9c0eee86ad5
