### ISSUE TITLE
Broken :-(

### ISSUE THREAD

**Issue by OliCpg** [codesandbox/codesandbox-client#2708]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  Redirected to Patron page after proceeding with subscription. 

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 77.0.3865 | OS X 10.14.6           |

  **Route:**
  https://codesandbox.io/patron

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  RangeError: Invalid time value
  RangeError: Invalid time value
    at B (https://codesandbox.io/static/js/vendors~app.873bb633.chunk.js:1:1708479)
    at https://codesandbox.io/static/js/page-patron.8bb24fc5.chunk.js:1:9694
    at https://codesandbox.io/static/js/default~app~embed.46b425ab.chunk.js:276:355544
    at f.trackScope (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1468208)
    at https://codesandbox.io/static/js/default~app~embed.46b425ab.chunk.js:276:355513
    at Li (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2052774)
    at Ka (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2095866)
    at Fa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2081589)
    at Na (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2078609)
    at Ra (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2077169)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039070
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2113916
    at co (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038799)
    at po (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039016)
    at ho (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038951)
    at Oa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2076160)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2043805)
    at n.setState (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2335969)
    at https://codesandbox.io/static/js/default~app~embed.46b425ab.chunk.js:276:416402
  
    in Unknown
    in r
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in Ue
    in div
    in t
    in elements__Details
    in div
    in t
    in elements__Container
    in bn
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in Unknown
    in div
    in t
    in elements__Content
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in Unknown
    in Unknown
    in n
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by garethx** [comment]
Thanks for reporting. We've a fix going out for this. See https://github.com/codesandbox/codesandbox-client/compare/337b44fbb31d...f9c0eee86ad5
