### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by rbrander** [codesandbox/codesandbox-client#2709]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 77.0.3865 | OS X 10.14.6           |

  **Route:**
  https://codesandbox.io/dashboard/recent

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'collections' of undefined
  TypeError: Cannot read property 'collections' of undefined
    at Object.children (https://codesandbox.io/static/js/app.a7a43e2d.js:438:275929)
    at n (https://codesandbox.io/static/js/vendors~app.873bb633.chunk.js:1:986284)
    at t.render (https://codesandbox.io/static/js/vendors~app.873bb633.chunk.js:1:986382)
    at vs (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2063034)
    at ms (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2062827)
    at Ka (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2097223)
    at Fa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2081589)
    at Na (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2078609)
    at Ra (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2077169)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039070
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2113916
    at co (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038799)
    at po (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039016)
    at ho (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038951)
    at Oa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2076160)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2043805)
    at r.setState (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2335969)
    at https://codesandbox.io/static/js/default~app~embed.46b425ab.chunk.js:276:354951
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1467884
    at h.flush (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1470729)
    at d.flush (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1467029)
    at Object.cb (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1355213)
    at e.emit (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1351588)
    at internal.setJwt (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1357380)
    at Proxy.<anonymous> (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1356480)
    at https://codesandbox.io/static/js/default~app~embed.46b425ab.chunk.js:276:242813
    at a (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:14585)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:14373)
    at Generator.next (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:15007)
    at t (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:8537)
    at u (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:8747)
  
    in t
    in div
    in t
    in t
    in n
    in div
    in n
    in t
    in withRouter(n)
    in DropTarget(withRouter(n))
    in div
    in t
    in elements__Items
    in Unknown
    in r
    in t
    in aside
    in t
    in elements__SidebarStyled
    in n
    in r
    in t
    in withRouter(r)
    in div
    in t
    in elements__Sidebar
    in div
    in div
    in t
    in elements__Container
    in n
    in r
    in t
    in withRouter(r)
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by siddharthkp** [comment]
Hi! We had some trouble on Tuesday, should be all good now. Can you confirm on your side as well?

**Comment by rbrander** [comment]
Confirmed all is working

**Comment by siddharthkp** [comment]
That's great! If you have any feedback, you know where to reach out 😉
