### ISSUE TITLE
Crash report - opening profile / sandboxes

### ISSUE THREAD

**Issue by marekrozmus** [codesandbox/codesandbox-client#2710]
<h1>💥 Crash Report</h1>

  <h2>Go to My Profile / Sandboxes</h2>

  > Just go to my profile page and clicking `sandboxes`

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 77.0.3865 | Windows 10           |

  **Route:**
  https://codesandbox.io/u/marekrozmus/sandboxes

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  RangeError: Invalid time value
  RangeError: Invalid time value
    at B (https://codesandbox.io/static/js/vendors~app.873bb633.chunk.js:1:1708479)
    at https://codesandbox.io/static/js/page-profile.ae38af70.chunk.js:9:19855
    at Proxy.map (<anonymous>)
    at Zn (https://codesandbox.io/static/js/page-profile.ae38af70.chunk.js:9:19587)
    at Li (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2052774)
    at Ka (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2095866)
    at Fa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2081589)
    at Na (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2078609)
    at Ra (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2077169)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039070
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2113916
    at co (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038799)
    at po (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039016)
    at ho (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038951)
    at Oa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2076160)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2043805)
    at r.setState (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2335969)
    at https://codesandbox.io/static/js/default~app~embed.46b425ab.chunk.js:276:354951
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1467884
    at h.flush (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1470729)
    at d.flush (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1467029)
    at t (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1355256)
    at r (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:122867)
  
    in Zn
    in div
    in n
    in r
    in t
    in t
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in Unknown
    in div
    in t
    in elements__Container
    in n
    in r
    in n
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by CompuIves** [comment]
Sorry! This should be fixed in the next deploy.
