### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by hegphegp** [codesandbox/codesandbox-client#2749]
# 🐛 bug report

## Description of the problem
```
hgp@hgp-pc:~/logs/codesandbox-client$ npm run test

> codesandbox@0.1.0 test /home/hgp/logs/codesandbox-client
> lerna run test --ignore codesandbox-browserfs

lerna notice cli v3.17.0
lerna info versioning independent
lerna info filter [ '!codesandbox-browserfs' ]
lerna info Executing command in 4 packages: "npm run test"
lerna ERR! npm run test exited 1 in 'codesandbox-api'
lerna ERR! npm run test stdout:

> codesandbox-api@0.0.22 test /home/hgp/logs/codesandbox-client/packages/codesandbox-api
> jest


lerna ERR! npm run test stderr:
● Validation Error:

  Preset ts-jest is invalid:

  The "id" argument must be of type string. Received type object
  TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Module.require (internal/modules/cjs/loader.js:687:3)
    at require (internal/modules/cjs/helpers.js:25:18)
    at setupPreset (/usr/lib/node_modules/jest/node_modules/jest-config/build/normalize.js:230:14)
    at normalize (/usr/lib/node_modules/jest/node_modules/jest-config/build/normalize.js:554:15)
    at readConfig (/usr/lib/node_modules/jest/node_modules/jest-config/build/index.js:163:46)
    at readConfigs (/usr/lib/node_modules/jest/node_modules/jest-config/build/index.js:373:26)
    at /usr/lib/node_modules/jest/node_modules/@jest/core/build/cli/index.js:155:58
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/usr/lib/node_modules/jest/node_modules/@jest/core/build/cli/index.js:108:24)

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! codesandbox-api@0.0.22 test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the codesandbox-api@0.0.22 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hgp/.npm/_logs/2019-10-12T14_37_30_009Z-debug.log

lerna ERR! npm run test exited 1 in 'codesandbox-api'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! codesandbox@0.1.0 test: `lerna run test --ignore codesandbox-browserfs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the codesandbox@0.1.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hgp/.npm/_logs/2019-10-12T14_37_30_031Z-debug.log
hgp@hgp-pc:~/logs/codesandbox-client$ 
```
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | In Master branch On 2019-10-12
| Browser          |
| Operating System |

**Comment by ConstantinChirila** [comment]
@hegphegp Did you manage to solve this issue?

**Comment by RupenAnjaria** [comment]
Facing the same issue.

**Comment by whalemare** [comment]
+1

**Comment by Leroy14** [comment]
+1

**Comment by mattvb91** [comment]
same issue

**Comment by jasonkuhrt** [comment]
Just hit this

**Comment by gavindoughtie** [comment]
Me too, converting a project to NX.

**Comment by mattvb91** [comment]
Not sure if it's relevant to others here but in my case this issue was caused by my `rootDir` setting in tsconfig.json
