### ISSUE TITLE
Crashed during testing

### ISSUE THREAD

**Issue by seanaleid** [codesandbox/codesandbox-client#2779]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 77.0.3865 | OS X 10.14.6           |

  **Route:**
  https://codesandbox.io/s/testing-ii-vgcib

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'tests' of undefined
  TypeError: Cannot read property 'tests' of undefined
    at https://codesandbox.io/static/js/default~app~embed.959d3548.chunk.js:276:157714
    at F.produce (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1098249)
    at t.<anonymous> (https://codesandbox.io/static/js/default~app~embed.959d3548.chunk.js:276:157677)
    at Io (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2041898)
    at Po (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2042159)
    at ms (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2061793)
    at Ka (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2097223)
    at Fa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2081589)
    at Na (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2078609)
    at Ra (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2077169)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039070
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2113916
    at co (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038799)
    at po (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039016)
    at ho (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038951)
    at Oa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2076160)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2043805)
    at t.setState (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2335969)
    at Object.<anonymous> (https://codesandbox.io/static/js/default~app~embed.959d3548.chunk.js:276:157637)
    at https://codesandbox.io/static/js/default~app~embed~sandbox.458603b3.chunk.js:1:6482
    at Array.forEach (<anonymous>)
    at _ (https://codesandbox.io/static/js/default~app~embed~sandbox.458603b3.chunk.js:1:6452)
    at k (https://codesandbox.io/static/js/default~app~embed~sandbox.458603b3.chunk.js:1:6561)
  
    in t
    in div
    in t
    in elements__ContentContainer
    in div
    in t
    in elements__Container
    in t
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in n
    in r
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in n
    in r
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by lbogdan** [comment]
Looks like `state.files[test.path]` is `undefined` here:
https://github.com/codesandbox/codesandbox-client/blob/729d375557db6d21a692184e91bae14c12116df2/packages/app/src/app/components/Preview/DevTools/Tests/index.tsx#L388

**Comment by lbogdan** [comment]
Closing this, it should be fixed by https://github.com/codesandbox/codesandbox-client/commit/fc10d12cc8c8be2105ea6be397c4c70a54ca23bb .
