### ISSUE TITLE
unavailable

### ISSUE THREAD

**Issue by nianxiongdi** [codesandbox/codesandbox-client#2866]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 74.0.3729 | Linux x86_64           |

  **Route:**
  https://codesandbox.io/dashboard/sandboxes

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'collections' of undefined
  TypeError: Cannot read property 'collections' of undefined
    at Object.children (https://codesandbox.io/static/js/app.339c82d8.js:438:72956)
    at n (https://codesandbox.io/static/js/vendors~app.ba3f08e4.chunk.js:1:986284)
    at t.render (https://codesandbox.io/static/js/vendors~app.ba3f08e4.chunk.js:1:986382)
    at vs (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2063518)
    at ms (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2063311)
    at Ka (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2097707)
    at Fa (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2082073)
    at Na (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2079093)
    at Ra (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2077653)
    at https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2039554
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2114400)
    at co (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2039283)
    at po (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2039500)
    at ho (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2039435)
    at Ia (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2078080)
    at https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2028922
    at HTMLDocument.r (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:122867)
  
    in t
    in div
    in t
    in t
    in n
    in div
    in n
    in t
    in withRouter(n)
    in DropTarget(withRouter(n))
    in div
    in t
    in elements__Items
    in Unknown
    in r
    in t
    in aside
    in t
    in elements__SidebarStyled
    in n
    in r
    in t
    in withRouter(r)
    in div
    in t
    in elements__Sidebar
    in div
    in div
    in t
    in elements__Container
    in n
    in r
    in t
    in withRouter(r)
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by SaraVieira** [comment]
We added some safety and it was closed by #2883
