### ISSUE TITLE
Error accessing dashboard

### ISSUE THREAD

**Issue by mariajorgemonteiro** [codesandbox/codesandbox-client#2868]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 77.0.3865 | Windows 10           |

  **Route:**
  https://codesandbox.io/dashboard/sandboxes

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'collection' of undefined
  TypeError: Cannot read property 'collection' of undefined
    at https://codesandbox.io/static/js/app.339c82d8.js:438:134294
    at https://codesandbox.io/static/js/default~app~embed.5b5df316.chunk.js:276:11000
    at https://codesandbox.io/static/js/default~app~embed.5b5df316.chunk.js:276:346408
    at h.trackScope (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:1468692)
    at o.wrappedComponent (https://codesandbox.io/static/js/default~app~embed.5b5df316.chunk.js:276:346377)
    at Li (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2053258)
    at ps (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2060342)
    at Ka (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2097625)
    at Fa (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2082073)
    at Na (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2079093)
  
    in Unknown
    in r
    in t
    in to
    in t
    in t
    in Unknown
    in t
    in withRouter()
    in div
    in t
    in elements__Content
    in div
    in div
    in t
    in elements__Container
    in n
    in r
    in t
    in withRouter(r)
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by lbogdan** [comment]
Closing this, it should be fixed by #2882 .
