### ISSUE TITLE
Server hangs when trying to fetch "My Sandboxes"

### ISSUE THREAD

**Issue by ldanet** [codesandbox/codesandbox-client#2900]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

I was on my dashboard and trying to access [My Sandboxes](https://codesandbox.io/dashboard/sandboxes) in the left-hand side menu. Instead of getting to view my sandboxes I got the text `Error!`. I then clicked on `My Templates` and was prompted to report this crash. 
Viewing my dashboard works fine, but `My Sandboxes` fails every time.

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 77.0.3865 | OS X 10.15.0           |

  **Route:**
  https://codesandbox.io/dashboard/templates

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'collections' of undefined
  TypeError: Cannot read property 'collections' of undefined
    at Object.children (https://codesandbox.io/static/js/app.b796020b.js:449:277405)
    at n (https://codesandbox.io/static/js/vendors~app.c3a205c4.chunk.js:1:985413)
    at t.render (https://codesandbox.io/static/js/vendors~app.c3a205c4.chunk.js:1:985511)
    at vs (https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2063518)
    at ms (https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2063311)
    at Ka (https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2097707)
    at Fa (https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2082073)
    at Na (https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2079093)
    at Ra (https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2077653)
    at https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2039554
    at https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2114400
    at co (https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2039283)
    at po (https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2039500)
    at ho (https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2039435)
    at Ia (https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2078080)
    at https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2028922
    at HTMLDocument.r (https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:122867)
  
    in t
    in div
    in t
    in t
    in n
    in div
    in n
    in t
    in withRouter(n)
    in DropTarget(withRouter(n))
    in div
    in t
    in elements__Items
    in Unknown
    in r
    in t
    in aside
    in t
    in elements__SidebarStyled
    in n
    in r
    in t
    in withRouter(r)
    in div
    in t
    in elements__Sidebar
    in div
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>
  
<h3>Failed query details</h3>

This happened because a request to `https://codesandbox.io/api/graphql` returned with status 504.

  <details>
  <summary>GraphQL query</summary>

```graphql
query PathedSandboxes($path: String!, $teamId: ID) {
  me {
    collections(teamId: $teamId) {
      ...SidebarCollection
      __typename
    }
    collection(path: $path, teamId: $teamId) {
      id
      path
      sandboxes {
        ...Sandbox
        __typename
      }
      __typename
    }
    __typename
  }
}

fragment Sandbox on Sandbox {
  id
  alias
  title
  description
  insertedAt
  updatedAt
  privacy
  screenshotUrl
  screenshotOutdated
  source {
    template
    __typename
  }
  customTemplate {
    id
    __typename
  }
  forkedTemplate {
    id
    color
    __typename
   }
   collection {
    path
    teamId
    __typename
  }
  __typename
}

fragment SidebarCollection on Collection {
  id
  path
  __typename
}
```
where `path` was `/` and `teamId` undefined.

  </details>
  <details>
  <summary>Server response</summary>

#### Headers

```
alt-svc: clear
cache-control: max-age=0, private, must-revalidate
cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
cf-cache-status: DYNAMIC
cf-ray: 5295dea0fdacda4a-SYD
content-type: text/html; charset=UTF-8
date: Mon, 21 Oct 2019 20:09:41 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
expires: Thu, 01 Jan 1970 00:00:01 GMT
pragma: no-cache
server: cloudflare
set-cookie: cf_ob_info=504:5295dea0fdacda4a:SYD; path=/; expires=Mon, 21-Oct-19 20:10:11 GMT
set-cookie: cf_use_ob=443; path=/; expires=Mon, 21-Oct-19 20:10:11 GMT
status: 504
via: 1.1 google
x-request-id: Fc_CbagCwsRhGD0AJ15k
```

#### Body

```html
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<meta http-equiv="refresh" content="0">

<title>codesandbox.io | 504: Gateway time-out</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->
<style type="text/css">body{margin:0;padding:0}</style>




</head>
<body>
<div id="cf-wrapper">

    

    <div id="cf-error-details" class="cf-error-details-wrapper">
        <div class="cf-wrapper cf-error-overview">
            <h1>
              
              <span class="cf-error-type">Error</span>
              <span class="cf-error-code">504</span>
              <small class="heading-ray-id">Ray ID: 5295dea0fdacda4a &bull; 2019-10-21 20:09:41 UTC</small>
            </h1>
            <h2 class="cf-subheadline">Gateway time-out</h2>
        </div><!-- /.error-overview -->
        
        <div class="cf-section cf-highlight cf-status-display">
            <div class="cf-wrapper">
                <div class="cf-columns cols-3">
                  
<div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status ">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-browser"></i>
    <i class="cf-icon-status cf-icon-ok"></i>
  </div>
  <span class="cf-status-desc">You</span>
  <h3 class="cf-status-name">Browser</h3>
  <span class="cf-status-label">Working</span>
</div>

<div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status ">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-cloud"></i>
    <i class="cf-icon-status cf-icon-ok"></i>
  </div>
  <span class="cf-status-desc">Sydney</span>
  <h3 class="cf-status-name">Cloudflare</h3>
  <span class="cf-status-label">Working</span>
</div>

<div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-server"></i>
    <i class="cf-icon-status cf-icon-error"></i>
  </div>
  <span class="cf-status-desc">codesandbox.io</span>
  <h3 class="cf-status-name">Host</h3>
  <span class="cf-status-label">Error</span>
</div>

                </div>
              
            </div>
        </div><!-- /.status-display -->

        <div class="cf-section cf-wrapper">
            <div class="cf-columns two">
                <div class="cf-column">
                    <h2>What happened?</h2>
                    <p>The web server reported a gateway time-out error.</p>
                </div>
              
                <div class="cf-column">
                    <h2>What can I do?</h2>
                    <p>Please try again in a few minutes.</p>
                </div>
            </div>
              
        </div><!-- /.section -->

        <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">Cloudflare Ray ID: <strong>5295dea0fdacda4a</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Your IP</span>: 131.203.137.142</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div><!-- /.error-footer -->


    </div><!-- /#cf-error-details -->
</div><!-- /#cf-wrapper -->
</body>
</html>
```
  </details>

**Comment by ldanet** [comment]
Part of the issue (error handling) is being fixed by https://github.com/codesandbox/codesandbox-client/pull/2883

**Comment by SaraVieira** [comment]
Closing this as now it should wait for everything to be back

We had some issues with timeouts
