### ISSUE TITLE
Can't access my dashboard?

### ISSUE THREAD

**Issue by primelos** [codesandbox/codesandbox-client#2903]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 77.0.3865 | OS X 10.12.6           |

  **Route:**
  https://codesandbox.io/dashboard/sandboxes

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'collection' of undefined
  TypeError: Cannot read property 'collection' of undefined
    at https://codesandbox.io/static/js/app.b796020b.js:449:224672
    at https://codesandbox.io/static/js/default~app~embed.33123fbe.chunk.js:265:11000
    at https://codesandbox.io/static/js/default~app~embed.33123fbe.chunk.js:265:358134
    at h.trackScope (https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:1468692)
    at https://codesandbox.io/static/js/default~app~embed.33123fbe.chunk.js:265:358103
    at Li (https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2053258)
    at ps (https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2060342)
    at Ka (https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2097625)
    at Fa (https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2082073)
    at Na (https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2079093)
    at Ra (https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2077653)
    at https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2039554
    at https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2114400
    at co (https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2039283)
    at po (https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2039500)
    at ho (https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2039435)
    at Ia (https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2078080)
    at https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:2028922
    at HTMLDocument.r (https://codesandbox.io/static/js/common.f59ac9c4.chunk.js:1:122867)
  
    in Unknown
    in r
    in t
    in eh
    in t
    in t
    in Unknown
    in t
    in withRouter()
    in div
    in t
    in elements__Content
    in div
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by SaraVieira** [comment]
Hey!

This seems to have been fixed by #2882
