### ISSUE TITLE
"Oh no! Something broke!" - not able to create new or open existing sandboxes anymore

### ISSUE THREAD

**Issue by perfectcircle** [codesandbox/codesandbox-client#2949]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

Creating a new Codesandbox or trying to open an old one will always result in an error.

  <h3>Crash Details</h3>

  <details>
Not able to create or open existing codesandboxes. The only exception are vanilla js codesandboxes.
Creating/Opening codesandboxes with this account on this machine with Firefox works like a charm.
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 78.0.3904 | OS X 10.15.0           |

  **Route:**
  https://codesandbox.io/s/gracious-frost-l3ffu

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'editorService' of undefined
  TypeError: Cannot read property 'editorService' of undefined
    at t.destroyMonaco (https://codesandbox.io/static/js/default~app~embed.f78a9197.chunk.js:265:44705)
    at t.value (https://codesandbox.io/static/js/default~app~embed.f78a9197.chunk.js:265:45477)
    at https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2071840
    at Is (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2071881)
    at Ps (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2071962)
    at zs (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2073646)
    at https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2092477
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2115664)
    at co (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2040547)
    at Ua (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2090280)
    at Ra (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2078917)
    at https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2040818
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2115664)
    at co (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2040547)
    at po (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2040764)
    at ho (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2040699)
    at Oa (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2077908)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2045553)
    at n.w.setState (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2340118)
    at https://codesandbox.io/static/js/app.a8d08689.js:449:475479
    at a (https://codesandbox.io/static/js/common-sandbox.3fe92412.chunk.js:1:14677)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.3fe92412.chunk.js:1:14465)
    at Generator.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.3fe92412.chunk.js:1:15099)
    at t (https://codesandbox.io/static/js/common-sandbox.3fe92412.chunk.js:1:8537)
    at u (https://codesandbox.io/static/js/common-sandbox.3fe92412.chunk.js:1:8747)
  
    in t
    in div
    in t
    in elements__Container
    in t
    in div
    in t
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in n
    in r
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in n
    in r
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by CompuIves** [comment]
Heyo! Does incognito work in Chrome? Checking whether it's a caching issue.

**Comment by lbogdan** [comment]
Closing this, it should be fixed by https://github.com/codesandbox/codesandbox-client/commit/6067a0b6378adb52bfecaec35a05f0dcd3d4cf66 .
