### ISSUE TITLE
 commit

### ISSUE THREAD

**Issue by ginkgo1928** [codesandbox/codesandbox-client#2950]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 78.0.3904 | Windows 10           |

  **Route:**
  https://codesandbox.io/u/ginkgo1928

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at zs (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2073724)
    at Is (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2071919)
    at Ps (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2071962)
    at zs (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2073646)
    at https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2092477
    at https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2115664
    at co (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2040547)
    at Ua (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2090280)
    at Ra (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2078917)
    at https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2040818
    at https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2115664
    at co (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2040547)
    at po (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2040764)
    at ho (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2040699)
    at Ia (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2079344)
    at https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2030186
    at HTMLDocument.r (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:123045)
  
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by SaraVieira** [comment]
closed by #4571
