### ISSUE TITLE
I was trying to look at one of my old sandboxes, and the very minimal React app wouldn't come up

### ISSUE THREAD

**Issue by mshecket** [codesandbox/codesandbox-client#2952]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 78.0.3904 | Linux x86_64           |

  **Route:**
  https://codesandbox.io/s/nervous-einstein-1j64y

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  Error: Cannot find module in /src/components/Clock.js
  Error: Cannot find module in /src/components/Clock.js
    at l (https://codesandbox.io/static/js/default~app~embed~sandbox.7ce69172.chunk.js:1:16926)
    at https://codesandbox.io/static/js/default~app~embed~sandbox.7ce69172.chunk.js:1:18335
    at https://codesandbox.io/static/js/default~app~embed.f78a9197.chunk.js:265:287887
    at Proxy.forEach (<anonymous>)
    at qi (https://codesandbox.io/static/js/default~app~embed.f78a9197.chunk.js:265:287843)
    at Object.editor.previewActionReceived (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:1360961)
    at Object.onAction (https://codesandbox.io/static/js/app.a8d08689.js:449:427594)
    at Object.<anonymous> (https://codesandbox.io/static/js/default~app~embed.f78a9197.chunk.js:128:3009)
    at https://codesandbox.io/static/js/default~app~embed~sandbox.7ce69172.chunk.js:1:6482
    at Array.forEach (<anonymous>)
    at M (https://codesandbox.io/static/js/default~app~embed~sandbox.7ce69172.chunk.js:1:6452)
    at Module.v (https://codesandbox.io/static/js/default~app~embed~sandbox.7ce69172.chunk.js:1:5994)
    at v.clearErrors (https://codesandbox.io/static/js/default~app~embed.f78a9197.chunk.js:128:4551)
    at v.executeCodeImmediately (https://codesandbox.io/static/js/default~app~embed.f78a9197.chunk.js:128:4002)
    at n.<anonymous> (https://codesandbox.io/static/js/app.a8d08689.js:449:426570)
    at No (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2045072)
    at Lo (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2044808)
    at https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2094411
    at https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2115664
    at co (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2040547)
    at Ua (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2090280)
    at Ra (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2078917)
    at https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2040818
    at https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2115664
    at co (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2040547)
    at po (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2040764)
    at ho (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2040699)
    at Ia (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2079344)
    at https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2030186
    at HTMLDocument.r (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:123045)
  
    in n
    in r
    in Content
    in div
    in t
    in elements__ContentContainer
    in div
    in t
    in elements__Container
    in t
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in n
    in r
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in n
    in r
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by CompuIves** [comment]
Heyo! That's indeed weird, I can't open the sandbox, is it deleted?

**Comment by mshecket** [comment]
Sorry about that! I'm not experienced with putting in issues. I was actually trying to get a look at the sandbox to decide if I was ready to delete it. When I hard-reloaded codesandbox, the sandbox came up OK and I decided I was good to get rid of it. I should have left it around for debugging purposes.

I just went into my trash and restored it...hope that helps!

**Comment by lbogdan** [comment]
Hey @mshecket ,

I just looked at your sandbox, and it seems to work well here. Is this still an issue for you?

**Comment by mshecket** [comment]
Unfortunately, I don't remember much about what happened. Hopefully I can be of more help next time I make a crash report here.

**Comment by lbogdan** [comment]
Well, whatever it was, seems to be solved, so I'm closing this for now, but feel free to reopen if it happens again.
