### ISSUE TITLE
Running a test and left a http request in it

### ISSUE THREAD

**Issue by LogicRoom** [codesandbox/codesandbox-client#2960]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

Ran a test with backend call, then used jest to mock it. It crashed.

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 78.0.3904 | OS X 10.14.6           |

  **Route:**
  https://codesandbox.io/s/bftdd-lesson-44-du2ho

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'tests' of undefined
  TypeError: Cannot read property 'tests' of undefined
    at https://codesandbox.io/static/js/default~app~embed.0a8ce467.chunk.js:265:157851
    at F.produce (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:1098427)
    at t.<anonymous> (https://codesandbox.io/static/js/default~app~embed.0a8ce467.chunk.js:265:157814)
    at Io (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2043646)
    at Po (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2043907)
    at ms (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2063541)
    at Ka (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2098971)
    at Fa (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2083337)
    at Na (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2080357)
    at Ra (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2078917)
    at https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2040818
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2115664)
    at co (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2040547)
    at po (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2040764)
    at ho (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2040699)
    at Oa (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2077908)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2045553)
    at t.w.setState (https://codesandbox.io/static/js/common.08aa376d.chunk.js:1:2340118)
    at Object.<anonymous> (https://codesandbox.io/static/js/default~app~embed.0a8ce467.chunk.js:265:157774)
    at https://codesandbox.io/static/js/default~app~embed~sandbox.7ce69172.chunk.js:1:6482
    at Array.forEach (<anonymous>)
    at M (https://codesandbox.io/static/js/default~app~embed~sandbox.7ce69172.chunk.js:1:6452)
    at k (https://codesandbox.io/static/js/default~app~embed~sandbox.7ce69172.chunk.js:1:6561)
  
    in t
    in div
    in t
    in elements__ContentContainer
    in div
    in t
    in elements__Container
    in t
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in n
    in r
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in n
    in r
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by lbogdan** [comment]
Hey @LogicRoom ,

I just tried your sandbox, and everything seems to work well, including tests. Is this still an issue for you?

**Comment by lbogdan** [comment]
Closing this, it should be fixed by https://github.com/codesandbox/codesandbox-client/commit/fc10d12cc8c8be2105ea6be397c4c70a54ca23bb .
