### ISSUE TITLE
Crash when clicking on a Map in console

### ISSUE THREAD

**Issue by Klaasvaak** [codesandbox/codesandbox-client#3053]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

I console logged a Map object and clicked on it in the console.

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 78.0.3904 | OS X 10.15.1           |

  **Route:**
  https://codesandbox.io/s/vigorous-tesla-97y6s

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Byear%2C%20month%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
  Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Byear%2C%20month%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at Xo (https://codesandbox.io/static/js/common.3dd8479f.chunk.js:1:2054920)
    at https://codesandbox.io/static/js/common.3dd8479f.chunk.js:1:2059741
    at cs (https://codesandbox.io/static/js/common.3dd8479f.chunk.js:1:2067374)
    at Ka (https://codesandbox.io/static/js/common.3dd8479f.chunk.js:1:2106375)
    at Fa (https://codesandbox.io/static/js/common.3dd8479f.chunk.js:1:2090071)
    at Na (https://codesandbox.io/static/js/common.3dd8479f.chunk.js:1:2087091)
    at Ra (https://codesandbox.io/static/js/common.3dd8479f.chunk.js:1:2085651)
    at https://codesandbox.io/static/js/common.3dd8479f.chunk.js:1:2047552
    at https://codesandbox.io/static/js/common.3dd8479f.chunk.js:1:2122398
    at co (https://codesandbox.io/static/js/common.3dd8479f.chunk.js:1:2047281)
    at po (https://codesandbox.io/static/js/common.3dd8479f.chunk.js:1:2047498)
    at ho (https://codesandbox.io/static/js/common.3dd8479f.chunk.js:1:2047433)
    at Ia (https://codesandbox.io/static/js/common.3dd8479f.chunk.js:1:2086078)
    at https://codesandbox.io/static/js/common.3dd8479f.chunk.js:1:2036920
    at HTMLDocument.r (https://codesandbox.io/static/js/common.3dd8479f.chunk.js:1:120151)
  
    in span
    in l
    in span
    in l
    in bound 
    in div
    in li
    in t
    in t
    in ol
    in li
    in t
    in t
    in t
    in t
    in t
    in g
    in div
    in Styled(div)
    in t
    in WithTheme(t)
    in t
    in WithTheme(t)
    in div
    in Styled(div)
    in div
    in Styled(div)
    in t
    in t
    in div
    in Styled(div)
    in t
    in t
    in div
    in t
    in elements__Messages
    in div
    in t
    in elements__Container
    in t
    in WithTheme(t)
    in div
    in t
    in elements__ContentContainer
    in div
    in t
    in elements__Container
    in t
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in n
    in r
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in n
    in r
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by arthurdenner** [comment]
This is related to https://github.com/samdenty/console-feed/issues/34.
