### ISSUE TITLE
Sandbox Crashed

### ISSUE THREAD

**Issue by balamuruganjbm** [codesandbox/codesandbox-client#3104]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 78.0.3904 | Windows 10           |

  **Route:**
  https://codesandbox.io/s/school-administration-71wsp

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'dependencies' of undefined
  TypeError: Cannot read property 'dependencies' of undefined
    at wl (https://codesandbox.io/static/js/app.1c18494b.js:449:693019)
    at Li (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1668378)
    at Ks (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1711470)
    at Fs (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1697193)
    at Ns (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1694213)
    at Bs (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1692773)
    at https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1654674
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1729520)
    at co (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1654403)
    at po (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1654620)
    at ho (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1654555)
    at Os (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1691764)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1659409)
    at t.w.setState (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1952146)
    at https://codesandbox.io/static/js/vendors~app.92525556.chunk.js:1:1805535
    at r (https://codesandbox.io/static/js/vendors~app.92525556.chunk.js:1:1057678)
    at https://codesandbox.io/static/js/vendors~app.92525556.chunk.js:1:1057902
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (https://codesandbox.io/static/js/vendors~app.92525556.chunk.js:1:1057873)
    at w (https://codesandbox.io/static/js/vendors~app.92525556.chunk.js:1:1054471)
    at https://codesandbox.io/static/js/vendors~app.92525556.chunk.js:1:1055448
    at Object.confirmTransitionTo (https://codesandbox.io/static/js/vendors~app.92525556.chunk.js:1:1057617)
    at Object.P [as push] (https://codesandbox.io/static/js/vendors~app.92525556.chunk.js:1:1055220)
    at Object.updateSandboxUrl (https://codesandbox.io/static/js/app.1c18494b.js:449:321381)
    at https://codesandbox.io/static/js/app.1c18494b.js:449:419967
    at a (https://codesandbox.io/static/js/common-sandbox.dd417ea9.chunk.js:1:14048)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.dd417ea9.chunk.js:1:13836)
    at Generator.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.dd417ea9.chunk.js:1:14470)
    at t (https://codesandbox.io/static/js/common-sandbox.dd417ea9.chunk.js:1:8537)
    at u (https://codesandbox.io/static/js/common-sandbox.dd417ea9.chunk.js:1:8747)
  
    in wl
    in div
    in t
    in elements__ChildContainer
    in div
    in t
    in n
    in div
    in files
    in div
    in div
    in t
    in elements__Container
    in gg
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in Unknown
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by MichaelDeBoey** [comment]
This one's fixed by 90e666a
