### ISSUE TITLE
[Crash Report] when modify `package.json` file, cause the page to crash 

### ISSUE THREAD

**Issue by caiyongmin** [codesandbox/codesandbox-client#3105]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 78.0.3904 | OS X 10.11.0           |

  **Route:**
  https://codesandbox.io/s/epic-water-d6t2b?fontsize=14

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'dependencies' of undefined
  TypeError: Cannot read property 'dependencies' of undefined
    at wl (https://codesandbox.io/static/js/app.1c18494b.js:449:693019)
    at Li (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1668378)
    at Ks (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1711470)
    at Fs (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1697193)
    at Ns (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1694213)
    at Bs (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1692773)
    at https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1654674
    at https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1729520
    at co (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1654403)
    at po (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1654620)
    at ho (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1654555)
    at Os (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1691764)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1659409)
    at r.setState (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1952146)
    at https://codesandbox.io/static/js/app.1c18494b.js:449:502356
    at https://codesandbox.io/static/js/vendors~app.92525556.chunk.js:1:1345902
    at m.flush (https://codesandbox.io/static/js/vendors~app.92525556.chunk.js:1:1348747)
    at p.flush (https://codesandbox.io/static/js/vendors~app.92525556.chunk.js:1:1345047)
    at Object.cb (https://codesandbox.io/static/js/vendors~app.92525556.chunk.js:1:1298136)
    at e.emit (https://codesandbox.io/static/js/vendors~app.92525556.chunk.js:1:1294339)
    at track (https://codesandbox.io/static/js/vendors~app.92525556.chunk.js:1:1300495)
    at https://codesandbox.io/static/js/vendors~app.92525556.chunk.js:1:1299433
    at e.runSignal (https://codesandbox.io/public/vscode25/vs/editor/codesandbox.editor.main.js:1:414736)
    at e.publicLog (https://codesandbox.io/public/vscode25/vs/editor/codesandbox.editor.main.js:1:1600312)
    at t.onDidEditorOpen (https://codesandbox.io/public/vscode25/vs/editor/codesandbox.editor.main.js:1:4139027)
    at https://codesandbox.io/public/vscode25/vs/editor/codesandbox.editor.main.js:1:4138361
    at e.fire (https://codesandbox.io/public/vscode25/vs/editor/codesandbox.editor.main.js:1:133049)
    at t.openEditor (https://codesandbox.io/public/vscode25/vs/editor/codesandbox.editor.main.js:1:2572185)
    at t.doOpenEditor (https://codesandbox.io/public/vscode25/vs/editor/codesandbox.editor.main.js:1:4143963)
    at t.openEditor (https://codesandbox.io/public/vscode25/vs/editor/codesandbox.editor.main.js:1:4143417)
    at t.doOpenEditor (https://codesandbox.io/public/vscode25/vs/editor/codesandbox.editor.main.js:1:4008135)
    at t.openEditor (https://codesandbox.io/public/vscode25/vs/editor/codesandbox.editor.main.js:1:4008035)
    at Proxy.t.doOpenCodeEditor (https://codesandbox.io/public/vscode25/vs/editor/codesandbox.editor.main.js:1:2872421)
    at Proxy.t.openCodeEditor (https://codesandbox.io/public/vscode25/vs/editor/codesandbox.editor.main.js:1:2872325)
    at Object.openFile (https://codesandbox.io/static/js/app.1c18494b.js:449:373271)
    at https://codesandbox.io/static/js/app.1c18494b.js:449:331958
    at a (https://codesandbox.io/static/js/common-sandbox.dd417ea9.chunk.js:1:14048)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.dd417ea9.chunk.js:1:13836)
    at Generator.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.dd417ea9.chunk.js:1:14470)
    at t (https://codesandbox.io/static/js/common-sandbox.dd417ea9.chunk.js:1:8537)
    at u (https://codesandbox.io/static/js/common-sandbox.dd417ea9.chunk.js:1:8747)
    at https://codesandbox.io/static/js/common-sandbox.dd417ea9.chunk.js:1:8806
    at new Promise (<anonymous>)
    at e.<anonymous> (https://codesandbox.io/static/js/common-sandbox.dd417ea9.chunk.js:1:8688)
    at e.changeModule (https://codesandbox.io/static/js/app.1c18494b.js:449:332253)
    at https://codesandbox.io/static/js/app.1c18494b.js:449:368631
    at a (https://codesandbox.io/static/js/common-sandbox.dd417ea9.chunk.js:1:14048)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.dd417ea9.chunk.js:1:13836)
    at Generator.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.dd417ea9.chunk.js:1:14470)
    at t (https://codesandbox.io/static/js/common-sandbox.dd417ea9.chunk.js:1:8537)
  
    in wl
    in div
    in t
    in elements__ChildContainer
    in div
    in t
    in n
    in div
    in files
    in div
    in div
    in t
    in elements__Container
    in gg
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in Unknown
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by MichaelDeBoey** [comment]
This one should be fixed by 90e666a
