### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by beldariakhil** [codesandbox/codesandbox-client#3111]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 78.0.3904 | Windows 10           |

  **Route:**
  https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/archives/v6-examples/react-table-editable-content

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'integrations' of null
  TypeError: Cannot read property 'integrations' of null
    at l (https://codesandbox.io/static/js/app.4a335d99.js:449:788265)
    at Li (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1668378)
    at Ks (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1711470)
    at Fs (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1697193)
    at Ns (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1694213)
    at Bs (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1692773)
    at https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1654674
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1729520)
    at co (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1654403)
    at po (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1654620)
    at ho (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1654555)
    at Os (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1691764)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1659409)
    at r.w.setState (https://codesandbox.io/static/js/common.8156f37c.chunk.js:1:1952146)
    at https://codesandbox.io/static/js/app.4a335d99.js:449:504122
    at e.callback (https://codesandbox.io/static/js/vendors~app.92525556.chunk.js:1:1345902)
    at m.flush (https://codesandbox.io/static/js/vendors~app.92525556.chunk.js:1:1348747)
    at p.flush (https://codesandbox.io/static/js/vendors~app.92525556.chunk.js:1:1345047)
    at Object.cb (https://codesandbox.io/static/js/vendors~app.92525556.chunk.js:1:1298136)
    at e.emit (https://codesandbox.io/static/js/vendors~app.92525556.chunk.js:1:1294339)
    at internal.setJwt (https://codesandbox.io/static/js/vendors~app.92525556.chunk.js:1:1300495)
    at Proxy.<anonymous> (https://codesandbox.io/static/js/vendors~app.92525556.chunk.js:1:1299433)
    at https://codesandbox.io/static/js/app.4a335d99.js:449:282741
    at a (https://codesandbox.io/static/js/common-sandbox.dd417ea9.chunk.js:1:14048)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.dd417ea9.chunk.js:1:13836)
    at Generator.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.dd417ea9.chunk.js:1:14470)
    at t (https://codesandbox.io/static/js/common-sandbox.dd417ea9.chunk.js:1:8537)
    at u (https://codesandbox.io/static/js/common-sandbox.dd417ea9.chunk.js:1:8747)
  
    in l
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by SaraVieira** [comment]
Hey!

Can you please  explain what you were doing when this error showed up?
