### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by akhileshcoder** [codesandbox/codesandbox-client#3152]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 78.0.3904 | OS X 10.13.6           | PROD-1575721600-9ec7e52a1          |

  **Route:**
  https://codesandbox.io/s/js-task-gqoic

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'id' of undefined
  TypeError: Cannot read property 'id' of undefined
    at https://codesandbox.io/static/js/app.09325390.js:522:694006
    at https://codesandbox.io/static/js/app.09325390.js:522:550209
    at h.trackScope (https://codesandbox.io/static/js/vendors~app.7b263973.chunk.js:1:1345846)
    at https://codesandbox.io/static/js/app.09325390.js:522:550178
    at Li (https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:1670744)
    at pa (https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:1677828)
    at Ks (https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:1715111)
    at Fs (https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:1699559)
    at Ns (https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:1696579)
    at Bs (https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:1695139)
  
    in Unknown
    in r
    in div
    in t
    in elements__Opener
    in div
    in n
    in r
    in DropTarget(r)
    in n
    in r
    in div
    in div
    in files
    in div
    in div
    in t
    in elements__Container
    in lh
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in Unknown
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by SaraVieira** [comment]
Hey!

Can you please tell me what you were doing when this error occured?
