### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by lxradda** [codesandbox/codesandbox-client#3154]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 78.0.3904 | Windows 10           | PROD-1575721600-9ec7e52a1          |

  **Route:**
  https://codesandbox.io/s/github/3s3s/opentrade

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at za (https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:1689946)
    at Ra (https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:1688141)
    at Pa (https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:1688184)
    at za (https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:1689868)
    at https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:1708699
    at https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:1731886
    at co (https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:1656769)
    at Us (https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:1706502)
    at Bs (https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:1695139)
    at https://codesandbox.io/static/js/common.9c166b39.chunk.js:1:1657040
  
    in elements__Container
    in div
    in mc
    in div
    in t
    in elements__Right
    in div
    in t
    in elements__EntryContainer
    in div
    in t
    in div
    in Unknown
    in DragSource(Component)
    in div
    in t
    in elements__EntryContainer
    in div
    in n
    in r
    in DropTarget(r)
    in div
    in Unknown
    in r
    in div
    in t
    in elements__Opener
    in div
    in n
    in r
    in DropTarget(r)
    in div
    in Unknown
    in r
    in div
    in t
    in elements__Opener
    in div
    in n
    in r
    in DropTarget(r)
    in n
    in r
    in div
    in t
    in elements__ChildContainer
    in div
    in t
    in n
    in div
    in project-summary
    in div
    in div
    in t
    in elements__Container
    in lh
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in Unknown
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by SaraVieira** [comment]
Hey

Can you please explain what you were doing at the time of the crash?
