### ISSUE TITLE
Error Joining Live Session

### ISSUE THREAD

**Issue by mustangJaro** [codesandbox/codesandbox-client#3186]
<h1>💥 Crash Report</h1>

  <h2>Attempted to join live JS session</h2>

  > I've tried multiple live sessions this morning and for every attempt we got the response of a failure to join the live session.

  ### Link to sandbox: [link](https://codesandbox.io/live/2RNOxv)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 78.0.3904 | OS X 10.13.6           | PROD-1576075543-c3f36805f          |

  **Route:**
  https://codesandbox.io/live/2RNOxv

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'users' of null
  TypeError: Cannot read property 'users' of null
    at bc (https://codesandbox.io/static/js/app.4714f7d9.js:522:499512)
    at live.internal.clearUserSelections (https://codesandbox.io/static/js/vendors~app.e426fe46.chunk.js:1:1307126)
    at Proxy.<anonymous> (https://codesandbox.io/static/js/vendors~app.e426fe46.chunk.js:1:1306132)
    at vc (https://codesandbox.io/static/js/app.4714f7d9.js:522:499625)
    at live.internal.reset (https://codesandbox.io/static/js/vendors~app.e426fe46.chunk.js:1:1307126)
    at Proxy.<anonymous> (https://codesandbox.io/static/js/vendors~app.e426fe46.chunk.js:1:1306132)
    at as (https://codesandbox.io/static/js/app.4714f7d9.js:522:514505)
    at Object.live.onNavigateAway (https://codesandbox.io/static/js/vendors~app.e426fe46.chunk.js:1:1307126)
    at N (https://codesandbox.io/static/js/page-live.06402563.chunk.js:1:3762)
    at https://codesandbox.io/static/js/page-live.06402563.chunk.js:1:3848
    at Da (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1634766)
    at https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1659161
    at https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1679091
    at co (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1603974)
    at Ws (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1658966)
    at Ns (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1643454)
    at Bs (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1642344)
    at https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1604245
    at https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1679091
    at co (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1603974)
    at po (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1604191)
    at ho (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1604126)
    at Os (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1641335)
    at $i (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1621082)
    at forceRerender (https://codesandbox.io/static/js/vendors~app.e426fe46.chunk.js:1:1296232)
    at https://codesandbox.io/static/js/vendors~app.e426fe46.chunk.js:1:1370248
    at m.flush (https://codesandbox.io/static/js/vendors~app.e426fe46.chunk.js:1:1373093)
    at p.flush (https://codesandbox.io/static/js/vendors~app.e426fe46.chunk.js:1:1369393)
    at Object.cb (https://codesandbox.io/static/js/vendors~app.e426fe46.chunk.js:1:1304835)
    at e.emit (https://codesandbox.io/static/js/vendors~app.e426fe46.chunk.js:1:1301038)
    at live.internal.initialize (https://codesandbox.io/static/js/vendors~app.e426fe46.chunk.js:1:1307194)
    at Proxy.<anonymous> (https://codesandbox.io/static/js/vendors~app.e426fe46.chunk.js:1:1306132)
    at https://codesandbox.io/static/js/app.4714f7d9.js:522:510468
    at a (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:14048)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:13836)
    at Generator.next (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:14470)
    at t (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:8537)
    at u (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:8747)
  
    in ee
    in n
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in t
    in l
    in t
  ```

  </details>

**Comment by CompuIves** [comment]
Thanks for the report! I can reproduce it, this seems to cause it: https://github.com/codesandbox/codesandbox-client/commit/2b5089474881b4a6a3ca5df1a05a3834ed03dbfc

**Comment by CompuIves** [comment]
I'm going to fix this now.

**Comment by CompuIves** [comment]
A fix should be live in 10 min

**Comment by SaraVieira** [comment]
This was fixed yesterday, we had some issues in that page

**Comment by mustangJaro** [comment]
Thanks so much for the fast response @CompuIves! We definitely tested it yesterday and this morning with great success!
