### ISSUE TITLE
CodesandBox client crashes

### ISSUE THREAD

**Issue by aldrinpvincent** [codesandbox/codesandbox-client#3206]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: https://codesandbox.io/s/interesting-dan-vkh3f</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 78.0.3904 | OS X 10.14.6           | PROD-1576147486-f5255700a          |

  **Route:**
  https://codesandbox.io/s/interesting-dan-vkh3f

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ba%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
  Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ba%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at Yo (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1611613)
    at https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1616434
    at ca (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1624067)
    at Ks (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1663068)
    at Fs (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1646764)
    at Ns (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1643784)
    at Bs (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1642344)
    at https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1604245
    at https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1679091
    at co (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1603974)
    at po (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1604191)
    at ho (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1604126)
    at Rs (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1642771)
    at https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1593613
    at HTMLDocument.r (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:120881)
  
    in span
    in l
    in span
    in l
    in bound 
    in div
    in li
    in t
    in t
    in ol
    in li
    in t
    in t
    in t
    in t
    in t
    in v
    in div
    in Styled(div)
    in t
    in WithTheme(t)
    in t
    in WithTheme(t)
    in div
    in Styled(div)
    in div
    in Styled(div)
    in t
    in t
    in div
    in Styled(div)
    in t
    in t
    in div
    in t
    in elements__Messages
    in div
    in t
    in elements__Container
    in t
    in WithTheme(t)
    in div
    in t
    in elements__ContentContainer
    in div
    in t
    in elements__Container
    in t
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in xe
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in Unknown
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in t
    in l
    in t
  ```

  </details>

**Comment by SaraVieira** [comment]
Hey!

Can you give us some more information? What were you doing when this happened?

**Comment by aldrinpvincent** [comment]
It's fixed. It was crashing when I  tried to expand a Map in console
Closing ticket.
