### ISSUE TITLE
?

### ISSUE THREAD

**Issue by fryftpbmb** [codesandbox/codesandbox-client#3210]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 79.0.3945 | OS X 10.14.6           | PROD-1576147486-f5255700a          |

  **Route:**
  https://codesandbox.io/s/dank-fire-62w7x

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at za (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1637173)
    at https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1655904
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1679091)
    at co (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1603974)
    at Us (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1653707)
    at Bs (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1642344)
    at https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1604245
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1679091)
    at co (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1603974)
    at po (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1604191)
    at ho (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1604126)
    at Os (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1641335)
    at $i (https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1:1621082)
    at forceRerender (https://codesandbox.io/static/js/vendors~app.06685bc6.chunk.js:1:1296232)
    at e.callback (https://codesandbox.io/static/js/vendors~app.06685bc6.chunk.js:1:1370248)
    at m.flush (https://codesandbox.io/static/js/vendors~app.06685bc6.chunk.js:1:1373093)
    at p.flush (https://codesandbox.io/static/js/vendors~app.06685bc6.chunk.js:1:1369393)
    at Object.cb (https://codesandbox.io/static/js/vendors~app.06685bc6.chunk.js:1:1304835)
    at e.emit (https://codesandbox.io/static/js/vendors~app.06685bc6.chunk.js:1:1301038)
    at internal.setPatronPrice (https://codesandbox.io/static/js/vendors~app.06685bc6.chunk.js:1:1307194)
    at Proxy.<anonymous> (https://codesandbox.io/static/js/vendors~app.06685bc6.chunk.js:1:1306132)
    at https://codesandbox.io/static/js/app.75fc78dd.js:524:321239
    at a (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:14048)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:13836)
    at Generator.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:14470)
    at t (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:8537)
    at u (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:8747)
  
    in div
    in t
    in elements__Folder
    in div
    in ForwardRef
    in div
    in t
    in elements__Container
    in div
    in t
    in elements__Main
    in wr
    in div
    in t
    in elements__Centered
    in header
    in t
    in elements__Container
    in Er
    in div
    in t
    in elements__Container
    in t
    in Unknown
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in t
    in l
    in t
  ```

  </details>

**Comment by SaraVieira** [comment]
Can you please let us know what you were doing when that happened?

**Comment by garethx** [comment]
Insufficient info to progress
