### ISSUE TITLE
Not sure what has been going on :/

### ISSUE THREAD

**Issue by fang092** [codesandbox/codesandbox-client#3221]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 77.0.3865 | Windows Server 2008 R2 / 7           | PROD-1576508781-4cc2753db          |

  **Route:**
  https://codesandbox.io/s/github/fang092/BlogDraftV1/tree/csb-1576591543906/

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'branch' of null
  TypeError: Cannot read property 'branch' of null
    at Sd (https://codesandbox.io/static/js/app.4f26dc5e.js:532:762486)
    at Li (https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1642936)
    at pa (https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1650020)
    at Ks (https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1687303)
    at Fs (https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1671751)
    at Ns (https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1668771)
    at Bs (https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1667331)
    at https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1629232
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1704078)
    at co (https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1628961)
    at po (https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1629178)
    at ho (https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1629113)
    at Os (https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1666322)
    at $i (https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1646069)
    at forceRerender (https://codesandbox.io/static/js/vendors~app.32688a05.chunk.js:1:1295893)
    at e.callback (https://codesandbox.io/static/js/vendors~app.32688a05.chunk.js:1:1349039)
    at m.flush (https://codesandbox.io/static/js/vendors~app.32688a05.chunk.js:1:1351884)
    at p.flush (https://codesandbox.io/static/js/vendors~app.32688a05.chunk.js:1:1348184)
    at Object.cb (https://codesandbox.io/static/js/vendors~app.32688a05.chunk.js:1:1304496)
    at e.emit (https://codesandbox.io/static/js/vendors~app.32688a05.chunk.js:1:1300699)
    at server.startContainer (https://codesandbox.io/static/js/vendors~app.32688a05.chunk.js:1:1306855)
    at Proxy.<anonymous> (https://codesandbox.io/static/js/vendors~app.32688a05.chunk.js:1:1305793)
    at https://codesandbox.io/static/js/app.4f26dc5e.js:532:324535
    at a (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:14048)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:13836)
    at Generator.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:14470)
    at t (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:8537)
    at u (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:8747)
    at https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:8806
    at new Promise (<anonymous>)
    at https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:8688
    at https://codesandbox.io/static/js/app.4f26dc5e.js:532:324625
    at internal.setCurrentSandbox (https://codesandbox.io/static/js/vendors~app.32688a05.chunk.js:1:1306787)
    at Proxy.<anonymous> (https://codesandbox.io/static/js/vendors~app.32688a05.chunk.js:1:1305793)
    at https://codesandbox.io/static/js/app.4f26dc5e.js:532:456783
    at a (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:14048)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:13836)
    at Generator.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:14470)
    at t (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:8537)
    at u (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:8747)
  
    in Sd
    in github
    in div
    in div
    in t
    in elements__Container
    in ph
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in Unknown
    in Gh
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in t
    in l
    in t
  ```

  </details>

**Comment by sreetamdas** [comment]
Is the repository a private repo? Your link currently gives me a 422 error.
