### ISSUE TITLE
I'm getting error when I try to log in with my github account

### ISSUE THREAD

**Issue by nur91m** [codesandbox/codesandbox-client#3229]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 79.0.3945 | Windows 10           | PROD-1576682437-d66544931          |

  **Route:**
  https://codesandbox.io/s/github/nur91m/kazgor-sms

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'integrations' of null
  TypeError: Cannot read property 'integrations' of null
    at l (https://codesandbox.io/static/js/app.b3f150bd.js:532:862990)
    at Li (https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1642936)
    at Ks (https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1686028)
    at Fs (https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1671751)
    at Ns (https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1668771)
    at Bs (https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1667331)
    at https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1629232
    at https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1704078
    at co (https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1628961)
    at po (https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1629178)
    at ho (https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1629113)
    at Os (https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1666322)
    at $i (https://codesandbox.io/static/js/common.bfa6a1c3.chunk.js:1:1646069)
    at forceRerender (https://codesandbox.io/static/js/vendors~app.c17aa81d.chunk.js:1:1295893)
    at https://codesandbox.io/static/js/vendors~app.c17aa81d.chunk.js:1:1349141
    at m.flush (https://codesandbox.io/static/js/vendors~app.c17aa81d.chunk.js:1:1351986)
    at p.flush (https://codesandbox.io/static/js/vendors~app.c17aa81d.chunk.js:1:1348286)
    at Object.cb (https://codesandbox.io/static/js/vendors~app.c17aa81d.chunk.js:1:1304520)
    at e.emit (https://codesandbox.io/static/js/vendors~app.c17aa81d.chunk.js:1:1300699)
    at internal.setJwt (https://codesandbox.io/static/js/vendors~app.c17aa81d.chunk.js:1:1306957)
    at Proxy.<anonymous> (https://codesandbox.io/static/js/vendors~app.c17aa81d.chunk.js:1:1305817)
    at https://codesandbox.io/static/js/app.b3f150bd.js:532:320602
    at a (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:14048)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:13836)
    at Generator.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:14470)
    at t (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:8537)
    at u (https://codesandbox.io/static/js/common-sandbox.25d2d35a.chunk.js:1:8747)
  
    in l
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in Kh
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in t
    in l
    in t
  ```

  </details>

**Comment by nur91m** [comment]
@CompuIves Hi Ivan. When I try import repository from github it says Somthing went wrong. Status code 422 error.

**Comment by garethx** [comment]
The error in the 422 is 'Only a max of 500 modules is allowed in a sandbox'. So your dependencies are using more than 500 modules, which is a hard limit on what can be used on CodeSandbox at the moment for performance reasons.
