### ISSUE TITLE
tabler

### ISSUE THREAD

**Issue by mzx2020** [codesandbox/codesandbox-client#3315]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 79.0.3945 | Windows 10           | PROD-1578672633-2548a0612          |

  **Route:**
  https://codesandbox.io/s/github/tabler/tabler

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at za (https://codesandbox.io/static/js/common.0dff1fe12.chunk.js:1:1662138)
    at Da (https://codesandbox.io/static/js/common.0dff1fe12.chunk.js:1:1660333)
    at Pa (https://codesandbox.io/static/js/common.0dff1fe12.chunk.js:1:1660376)
    at za (https://codesandbox.io/static/js/common.0dff1fe12.chunk.js:1:1662060)
    at https://codesandbox.io/static/js/common.0dff1fe12.chunk.js:1:1680891
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.0dff1fe12.chunk.js:1:1704078)
    at co (https://codesandbox.io/static/js/common.0dff1fe12.chunk.js:1:1628961)
    at Us (https://codesandbox.io/static/js/common.0dff1fe12.chunk.js:1:1678694)
    at Bs (https://codesandbox.io/static/js/common.0dff1fe12.chunk.js:1:1667331)
    at https://codesandbox.io/static/js/common.0dff1fe12.chunk.js:1:1629232
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.0dff1fe12.chunk.js:1:1704078)
    at co (https://codesandbox.io/static/js/common.0dff1fe12.chunk.js:1:1628961)
    at po (https://codesandbox.io/static/js/common.0dff1fe12.chunk.js:1:1629178)
    at ho (https://codesandbox.io/static/js/common.0dff1fe12.chunk.js:1:1629113)
    at Os (https://codesandbox.io/static/js/common.0dff1fe12.chunk.js:1:1666322)
    at $i (https://codesandbox.io/static/js/common.0dff1fe12.chunk.js:1:1646069)
    at forceRerender (https://codesandbox.io/static/js/vendors~app.8b1be9e79.chunk.js:1:1241924)
    at e.callback (https://codesandbox.io/static/js/vendors~app.8b1be9e79.chunk.js:1:1295172)
    at m.flush (https://codesandbox.io/static/js/vendors~app.8b1be9e79.chunk.js:1:1298017)
    at p.flush (https://codesandbox.io/static/js/vendors~app.8b1be9e79.chunk.js:1:1294317)
    at t (https://codesandbox.io/static/js/vendors~app.8b1be9e79.chunk.js:1:1250594)
    at r (https://codesandbox.io/static/js/common.0dff1fe12.chunk.js:1:120881)
  
    in Unknown
    in Jh
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in t
    in l
    in t
  ```

  </details>

**Comment by lbogdan** [comment]
Hey @mzx2020 ,

I'm not sure what you were trying to do here. If you were trying to run [tabler](https://github.com/tabler/tabler) inside CodeSandbox, note that it depends on Ruby, which, while technically possible to run inside a container / server sandbox, we don't officially support. Also that repository exceeds our current limit of 500 files per repository.

That being said, it shouldn't crash like that. Can you please check if this still happens for you? It "works" here, meaning that it doesn't crash and I get this:

![image](https://user-images.githubusercontent.com/2083930/73301116-df3b2680-421a-11ea-90a6-27580bd9f552.png)
