### ISSUE TITLE
Could not find dependency: 'es-abstract' in tests

### ISSUE THREAD

**Issue by SheaBelsky** [codesandbox/codesandbox-client#3477]
# 🐛 bug report

## Description of the problem
Unit tests in CodeSandbox fail due to a dependency issue.

```
Could not find dependency: 'es-abstract' relative to '/node_modules/object.fromentries/implementation.js'

DependencyNotFoundError: Could not find dependency: 'es-abstract' relative to '/node_modules/object.fromentries/implementation.js'
    at n (https://codesandbox.io/static/js/sandbox.1282bc6dd.js:1:34070)
    at new n (https://codesandbox.io/static/js/sandbox.1282bc6dd.js:1:28421)
    at e.value (https://codesandbox.io/static/js/sandbox.1282bc6dd.js:1:224006)
    at e.value (https://codesandbox.io/static/js/sandbox.1282bc6dd.js:1:224851)
    at t (https://codesandbox.io/static/js/sandbox.1282bc6dd.js:1:195083)
    at evaluate (https://rdfn2.csb.app/node_modules/object.fromentries/implementation.js:3:30)
.......
```

## How has this issue affected you? What are you trying to accomplish?
We want to allow people who visit the below CodeSandbox to fork it and write their own unit tests. However, our empty test assertions aren't running anymore, and we see the above error in CodeSandbox when the output of a test is expanded.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1580823156-8f4024d7d
| Browser          | Google Chrome  79.0.3945.130
| Operating System | macOS Mojave 10.14.6

**Comment by CompuIves** [comment]
Hey! Thanks for reporting the bug, I found issue and pushed a fix, should be live in a couple minutes!

https://github.com/codesandbox/codesandbox-client/commit/dac6ada07b831df599d9b570ee63663adf721816
