### ISSUE TITLE
Deleting All Sandboxes breaks the page

### ISSUE THREAD

**Issue by RaviKavaiya** [codesandbox/codesandbox-client#3498]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  Whenever I delete a sandbox permanently from the Trash, it gives a crash warning...

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 80.0.3987 | Windows 10           | PROD-1581023033-dac6ada07          |

  **Route:**
  https://codesandbox.io/dashboard/trash

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'template' of null
  TypeError: Cannot read property 'template' of null
    at https://codesandbox.io/static/js/app.53e43730f.js:532:624799
    at Array.map (<anonymous>)
    at Ap (https://codesandbox.io/static/js/app.53e43730f.js:532:624763)
    at https://codesandbox.io/static/js/app.53e43730f.js:532:637830
    at jd (https://codesandbox.io/static/js/app.53e43730f.js:532:934774)
    at da (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1695375)
    at $a (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1703618)
    at Ss (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1741961)
    at Sl (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1726418)
    at xl (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1726343)
  
    in jd
    in t
    in xg
    in t
    in t
    in Unknown
    in withRouter()
    in div
    in t
    in elements__Content
    in div
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in t
    in div
    in t
    in elements__Content
    in t
    in withRouter(t)
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in t
    in l
    in t
  ```

  </details>

**Comment by garethx** [comment]
Will follow https://github.com/codesandbox/codesandbox-client/issues/3500 for updates
