### ISSUE TITLE
Consistent crash on GitHub commit

### ISSUE THREAD

**Issue by sebastien** [codesandbox/codesandbox-client#3552]
<h1>💥 Crash Report</h1>

  <h2>Commit with GitHub</h2>

  Every time I commit through GitHub the application crashed, but the commit gets through.

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 80.0.3987 | Windows 10           | PROD-1581626805-0394eb371          |

  **Route:**
  https://codesandbox.io/s/XXX

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'rights' of null
  TypeError: Cannot read property 'rights' of null
    at ak (https://codesandbox.io/static/js/app.eaca164e3.js:536:1336225)
    at da (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1695375)
    at $a (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1703618)
    at Ss (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1741961)
    at Sl (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1726418)
    at xl (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1726343)
    at gl (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1723663)
    at https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1681659
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1757109)
    at Go (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1681369)
    at Xo (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1681605)
    at Yo (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1681540)
    at hl (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1720431)
    at ja (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1699048)
    at forceRerender (https://codesandbox.io/static/js/vendors~app.6374ce098.chunk.js:1:1252829)
    at e.callback (https://codesandbox.io/static/js/vendors~app.6374ce098.chunk.js:1:1304299)
    at b.flush (https://codesandbox.io/static/js/vendors~app.6374ce098.chunk.js:1:1307176)
    at h.flush (https://codesandbox.io/static/js/vendors~app.6374ce098.chunk.js:1:1303353)
    at t (https://codesandbox.io/static/js/vendors~app.6374ce098.chunk.js:1:1259517)
    at r (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:120909)
  
    in ak
    in div
    in t
    in styled.div
    in div
    in t
    in Styled(styled.div)
    in section
    in t
    in Styled(styled.div)
    in Unknown
    in Unknown
    in div
    in t
    in Unknown
    in div
    in t
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in Unknown
    in gh
    in t
    in t
    in div
    in t
    in elements__Content
    in t
    in withRouter(t)
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in t
    in l
    in t
  ```

  </details>

**Comment by sebastien** [comment]
Hi there, this is still happening for me today. The first commit worked fine, but the next one did not -- maybe the fix is not deployed yet?

```
  TypeError: Cannot read property 'rights' of null
  TypeError: Cannot read property 'rights' of null
    at ak (https://codesandbox.io/static/js/app.eaca164e3.js:536:1336225)
    at da (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1695375)
    at $a (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1703618)
    at Ss (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1741961)
    at Sl (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1726418)
    at xl (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1726343)
    at gl (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1723663)
    at https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1681659
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1757109)
    at Go (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1681369)
    at Xo (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1681605)
    at Yo (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1681540)
    at hl (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1720431)
    at ja (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1699048)
    at forceRerender (https://codesandbox.io/static/js/vendors~app.6374ce098.chunk.js:1:1252829)
    at e.callback (https://codesandbox.io/static/js/vendors~app.6374ce098.chunk.js:1:1304299)
    at b.flush (https://codesandbox.io/static/js/vendors~app.6374ce098.chunk.js:1:1307176)
    at h.flush (https://codesandbox.io/static/js/vendors~app.6374ce098.chunk.js:1:1303353)
    at t (https://codesandbox.io/static/js/vendors~app.6374ce098.chunk.js:1:1259517)
    at r (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:120909)
```
