### ISSUE TITLE
trying to logout because my proyect wasn't working and it brokes

### ISSUE THREAD

**Issue by darkyelox** [codesandbox/codesandbox-client#3566]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 80.0.3987 | Linux x86_64           | PROD-1581626805-0394eb371          |

  **Route:**
  https://codesandbox.io/s/hexagon-honeycomb-animation-v2-jsrh6

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'username' of null
  TypeError: Cannot read property 'username' of null
    at ie (https://codesandbox.io/static/js/app.eaca164e3.js:536:1418084)
    at da (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1695375)
    at $a (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1703618)
    at Ss (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1741961)
    at Sl (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1726418)
    at xl (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1726343)
    at gl (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1723663)
    at https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1681659
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1757109)
    at Go (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1681369)
    at Xo (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1681605)
    at Yo (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1681540)
    at ae (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1750858)
    at https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:1665014
    at HTMLDocument.r (https://codesandbox.io/static/js/common.dc6c0e494.chunk.js:1:120909)
  
    in ie
    in div
    in t
    in elements__UserMenuContainer
    in div
    in t
    in elements__AccountContainer
    in div
    in t
    in elements__Right
    in header
    in t
    in elements__Container
    in Rr
    in div
    in t
    in elements__Container
    in t
    in Unknown
    in gh
    in t
    in t
    in div
    in t
    in elements__Content
    in t
    in withRouter(t)
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in t
    in l
    in t
  ```

  </details>

**Comment by garethx** [comment]
This should be fixed in the latest version. Please update when you see the update prompt after loading the editor.
