### ISSUE TITLE
Cannot start the project, error shows at the first step `yarn`

### ISSUE THREAD

**Issue by anyexinglu** [codesandbox/codesandbox-client#3567]
# 🐛 bug report

## The problem
Following [CONTRIBUTING.md](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md#setting-up-the-project-locally), I want to start the project, but errors shown at the first step `yarn`

## Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| yarn | 1.19.1(the latest)
| node | 10.16.2(following .nvmrc) | 

## My step and the Errors

when I run `yarn` in the root directory, errors show:

```
➜  codesandbox-client-code git:(master) ✗ yarn
yarn install v1.19.1
[1/6] 🔍  Validating package.json...
[2/6] 🔍  Resolving packages...
[3/6] 🚚  Fetching packages...
warning np@5.2.1: The engine "git" appears to be invalid.
warning overmind-themes@1.0.2-1562145138120: The engine "browsers" appears to be invalid.
[4/6] 🔗  Linking dependencies...
warning " > eslint-import-resolver-webpack@0.8.4" has unmet peer dependency "webpack@>=1.11.0".
warning " > eslint-loader@1.9.0" has incorrect peer dependency "eslint@>=1.6.0 <5.0.0".
warning " > @codesandbox/components@1.0.8" has unmet peer dependency "react@^16.9.0".
warning " > @codesandbox/components@1.0.8" has unmet peer dependency "react-dom@^16.9.0".
warning " > @codesandbox/react-embed@0.0.14" has unmet peer dependency "react@^15.0.0 | ^16.0.0".
warning " > @codesandbox/notifications@1.0.6" has unmet peer dependency "react@^16.8.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > app > @apollo/react-hooks@3.1.3" has unmet peer dependency "apollo-client@^2.6.4".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > app > babel-plugin-transform-vue-jsx@3.7.0" has unmet peer dependency "babel-helper-vue-jsx-merge-props@^2.0.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > app > downshift@1.31.15" has unmet peer dependency "prop-types@>=15".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > app > eslint-plugin-vue@4.5.0" has incorrect peer dependency "eslint@^3.18.0 || ^4.0.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > app > monaco-editor-textmate@2.0.0" has unmet peer dependency "monaco-editor@^0.12.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > app > react-addons-css-transition-group@15.6.2" has incorrect peer dependency "react@^15.4.2".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > app > react-apollo@2.5.8" has unmet peer dependency "apollo-client@^2.6.3".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > app > react-scrollbars-custom@4.0.21" has unmet peer dependency "prop-types@^15.0.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > app > acorn-dynamic-import@4.0.0" has unmet peer dependency "acorn@^6.0.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > app > jest-image-snapshot@1.0.1" has incorrect peer dependency "jest@^20.0.0 || ^21.0.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > app > script-ext-html-webpack-plugin@2.1.4" has incorrect peer dependency "html-webpack-plugin@^3.0.0 || ^4.0.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > homepage > @react-hook/mouse-position@1.0.3" has unmet peer dependency "prop-types@^15.6.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > homepage > gatsby-plugin-typography@2.3.3" has unmet peer dependency "react-typography@^0.16.1 || ^1.0.0-alpha.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > homepage > gatsby-react-router-scroll@2.1.4" has unmet peer dependency "@reach/router@^1.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > @codesandbox/common > @tippy.js/react@3.1.1" has unmet peer dependency "react-dom@>=16.8".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > @codesandbox/common > @storybook/react@5.2.8" has unmet peer dependency "react-dom@*".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > @codesandbox/common > babel-loader@8.0.6" has unmet peer dependency "webpack@>=2".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > @codesandbox/common > enzyme-adapter-react-16@1.14.0" has unmet peer dependency "react-dom@^16.0.0-0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > @codesandbox/components > @reach/auto-id@0.7.1" has unmet peer dependency "react@^16.8.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > @codesandbox/components > @reach/auto-id@0.7.1" has unmet peer dependency "react-dom@^16.8.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > @codesandbox/components > @reach/visually-hidden@0.7.0" has unmet peer dependency "react@^16.8.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > @codesandbox/components > @reach/visually-hidden@0.7.0" has unmet peer dependency "react-dom@^16.8.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > @codesandbox/components > storybook-addon-styled-component-theme@1.3.0" has unmet peer dependency "@storybook/addons@^5.2.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > dynamic-pages > @babel/plugin-transform-modules-commonjs@7.7.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > dynamic-pages > file-loader@3.0.1" has unmet peer dependency "webpack@^4.0.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > @codesandbox/notifications > styled-components@5.0.0" has unmet peer dependency "react@>= 16.8.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > @codesandbox/notifications > styled-components@5.0.0" has unmet peer dependency "react-dom@>= 16.8.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > @codesandbox/notifications > styled-components@5.0.0" has unmet peer dependency "react-is@>= 16.8.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > app > @apollo/react-hooks > @apollo/react-common@3.1.3" has unmet peer dependency "apollo-client@^2.6.4".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > app > @apollo/react-hooks > @apollo/react-common@3.1.3" has unmet peer dependency "apollo-utilities@^1.3.2".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > app > console-feed > emotion-theming@9.1.2" has unmet peer dependency "prop-types@>= 15".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > app > react-icons > react-icon-base@2.1.0" has unmet peer dependency "prop-types@*".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > app > react-instantsearch > react-instantsearch-native@5.7.0" has unmet peer dependency "react-native@>= 0.32.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > homepage > @react-hook/mouse-position > @react-hook/hover@1.0.1" has unmet peer dependency "prop-types@^15.6.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > homepage > @react-hook/mouse-position > @react-hook/throttle@1.0.5" has unmet peer dependency "prop-types@>= 15.6.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > @codesandbox/common > @storybook/addon-a11y > @storybook/components@5.2.8" has unmet peer dependency "react-dom@*".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > @codesandbox/common > @storybook/addon-a11y > @storybook/theming@5.2.8" has unmet peer dependency "react-dom@*".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > @codesandbox/common > @storybook/addon-a11y > react-sizeme@2.6.10" has unmet peer dependency "prop-types@^15.0.0-0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > @codesandbox/common > @storybook/addon-a11y > react-sizeme@2.6.10" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0-0 || ^16.0.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > @codesandbox/common > @storybook/addon-knobs > react-select@3.0.8" has unmet peer dependency "react-dom@^16.8.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > @codesandbox/common > @storybook/addon-storysource > @storybook/router@5.2.8" has unmet peer dependency "react-dom@*".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > @codesandbox/common > @storybook/react > @storybook/core@5.2.8" has unmet peer dependency "react-dom@*".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > @codesandbox/components > storybook-addon-styled-component-theme > recompose@0.27.1" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > dynamic-pages > @zeit/next-css > css-loader@1.0.0" has unmet peer dependency "webpack@^4.0.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > dynamic-pages > @zeit/next-css > mini-css-extract-plugin@0.4.3" has unmet peer dependency "webpack@^4.4.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > dynamic-pages > next > unistore@3.2.1" has unmet peer dependency "preact@*".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > app > react-instantsearch > react-instantsearch-core > algoliasearch-helper@2.26.1" has unmet peer dependency "algoliasearch@>= 3.1 < 4".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > app > @graphql-codegen/cli > prettier > angular-estree-parser@1.1.5" has incorrect peer dependency "@angular/compiler@^6.0.0 || ^7.0.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > app > graphql-cli > graphql-cli-prepare > graphql-import@0.4.5" has incorrect peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > app > graphql-cli > graphql-cli-prepare > graphql-static-binding@0.9.3" has incorrect peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > app > graphql-cli > tmp-graphql-config-extension-openapi > @kbrandwijk/swagger-to-graphql@2.4.3" has incorrect peer dependency "graphql@^0.12.0 || ^0.13.0".
warning "workspace-aggregator-3f939e32-19d5-4c5c-a54c-10d9011357c6 > @codesandbox/common > @storybook/addon-knobs > react-select > react-transition-group@2.3.1" has unmet peer dependency "react-dom@>=15.0.0".
[5/6] 🔨  Building fresh packages...
[-/46] ⠄ waiting...
[22/46] ⠄ sharp
[21/46] ⠄ cwebp-bin
[-/46] ⠄ waiting...
error /Users/yangxiayan/Documents/duoduo/codesandbox-client-code/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /Users/yangxiayan/Documents/duoduo/codesandbox-client-code/node_modules/sharp
Output:
info sharp Using cached /Users/yangxiayan/.npm/_libvips/libvips-8.7.4-darwin-x64.tar.gz
ERR! sharp Please delete /Users/yangxiayan/.npm/_libvips/libvips-8.7.4-darwin-x64.tar.gz as it is not a valid tarball
ERR! sharp zlib: unexpected end of file
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/page/install for required dependencies
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.16.2 | darwin | x64
gyp info find Python using Python version 2.7.10 found at "/usr/bin/python"
gyp http GET https://nodejs.org/download/release/v10.16.2/node-v10.16.2-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.16.2/node-v10.16.2-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v10.16.2/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v10.16.2/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/yangxiayan/Documents/duoduo/codesandbox-client-code/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/yangxiayan/Documents/duoduo/codesandbox-client-code/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/yangxiayan/Documents/duoduo/codesandbox-client-code/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/yangxiayan/Library/Caches/node-gyp/10.16.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/yangxiayan/Library/Caches/node-gyp/10.16.2',
gyp info spawn args   '-Dnode_gyp_dir=/Users/yangxiayan/Documents/duoduo/codesandbox-client-code/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/yangxiayan/Library/Caches/node-gyp/10.16.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/yangxiayan/Documents/duoduo/codesandbox-client-code/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:25:10: fatal error: 'vips/vips8' file not found
#include <vips/vips8>
         ^~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/yangxiayan/Documents/duoduo/codesandbox-client-code/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/yangxiayan/.nvm/versions/node/v10.16.2/bin/node" "/Users/yangxiayan/Documents/duoduo/codesandbox-client-code/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/yangxiayan/Documents/duoduo/codesandbox-client-code/node_modules/sharp
```

**Comment by anyexinglu** [comment]
After delete the content within ` /Users/yangxiayan/.npm/_libvips/`, the problem solved
