### ISSUE TITLE
Crash when I tried logging into github

### ISSUE THREAD

**Issue by anfedorov** [codesandbox/codesandbox-client#3644]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

I was logged out of GitHub, then logged in in a separate tab, then came back to CS and clicked the "signin" button. A OAuth popup came up, then closed itself, then redirected to error page.

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 80.0.3987 | OS X 10.15.3           | PROD-1583440701-41bd38c73          |

  **Route:**
  https://codesandbox.io/s/turtle-run-2-4j5sm

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'username' of null
  TypeError: Cannot read property 'username' of null
    at ce (https://codesandbox.io/static/js/app.3ccb9c828.js:539:1584762)
    at da (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1694646)
    at Ss (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1740046)
    at Sl (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1725689)
    at xl (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1725614)
    at gl (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1722934)
    at https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1680930
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1756380)
    at Go (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1680640)
    at Xo (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1680876)
  
    in ce
    in div
    in t
    in Actions___StyledStack
    in pr
    in header
    in t
    in Header___StyledStack
    in lo
    in t
    in Unknown
    in div
    in t
    in elements__Container
    in t
    in Unknown
    in Cv
    in t
    in t
    in div
    in t
    in elements__Content
    in t
    in withRouter(t)
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in t
    in l
    in t
  ```

  </details>

**Comment by garethx** [comment]
This should be fixed in the latest version. Please update when you see the update prompt after loading the editor.
