### ISSUE TITLE
sandbox won't open unless logged in

### ISSUE THREAD

**Issue by acdcjunior** [codesandbox/codesandbox-client#3756]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

Just opened the sandbox. Wasn't logged in. If I'm logged in (using github), the issue is gone and the sandbox opens.

  <h3>Link to sandbox:</h3>

https://codesandbox.io/s/vue-template-xsy58

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 80.0.3987 | Windows 10           | PROD-1583406191-882f45e99          |

  **Route:**
  https://codesandbox.io/s/vue-template-xsy58

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'username' of null
  TypeError: Cannot read property 'username' of null
    at ce (https://codesandbox.io/static/js/app.d3424c154.js:539:1573528)
    at da (https://codesandbox.io/static/js/common.62d10c271.chunk.js:1:1694646)
    at Ss (https://codesandbox.io/static/js/common.62d10c271.chunk.js:1:1740046)
    at Sl (https://codesandbox.io/static/js/common.62d10c271.chunk.js:1:1725689)
    at xl (https://codesandbox.io/static/js/common.62d10c271.chunk.js:1:1725614)
    at gl (https://codesandbox.io/static/js/common.62d10c271.chunk.js:1:1722934)
    at https://codesandbox.io/static/js/common.62d10c271.chunk.js:1:1680930
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.62d10c271.chunk.js:1:1756380)
    at Go (https://codesandbox.io/static/js/common.62d10c271.chunk.js:1:1680640)
    at Xo (https://codesandbox.io/static/js/common.62d10c271.chunk.js:1:1680876)
  
    in ce
    in div
    in t
    in Actions___StyledStack
    in fr
    in header
    in t
    in Header___StyledStack
    in uo
    in t
    in Unknown
    in div
    in t
    in elements__Container
    in t
    in Unknown
    in Cv
    in t
    in t
    in div
    in t
    in elements__Content
    in t
    in withRouter(t)
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in t
    in l
    in t
  ```

  </details>

**Comment by CompuIves** [comment]
Hey! Do you still see this? I can't seem to repro the issue.

**Comment by acdcjunior** [comment]
Hi! Thanks for the feedback! I can't reproduce it either. Closing, then! Thanks again!
