### ISSUE TITLE
cheikh268

### ISSUE THREAD

**Issue by cheikh268** [codesandbox/codesandbox-client#3775]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 80.0.3987 | Windows 10           | PROD-1585411602-2cbc33b88          |

  **Route:**
  https://codesandbox.io/s/wizardly-mestorf-d2syj

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ws (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1715716)
    at gs (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1713717)
    at ws (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1715453)
    at https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1734944
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1756380)
    at Go (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1680640)
    at Tl (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1732850)
    at gl (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1723134)
    at https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1680930
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1756380)
    at Go (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1680640)
    at Xo (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1680876)
    at Yo (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1680811)
    at le (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1750339)
    at kn (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1664751)
    at jn (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1665708)
    at Sn (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1664996)
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1756380)
    at https://codesandbox.io/static/js/common.80a8af82d.chunk.js:1:1664366
  
    in elements__Container
    in div
    in ex
    in div
    in t
    in Styled(styled.div)
    in li
    in t
    in Entry___StyledListAction
    in div
    in t
    in div
    in Unknown
    in DragSource(Component)
    in div
    in t
    in elements__EntryContainer
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in Mx
    in div
    in t
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in t
    in Styled(styled.div)
    in section
    in t
    in Styled(styled.div)
    in Unknown
    in t
    in Files___StyledCollapsible
    in eS
    in FS
    in Unknown
    in div
    in t
    in Unknown
    in div
    in t
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in Unknown
    in Sg
    in t
    in t
    in div
    in t
    in elements__Content
    in t
    in withRouter(t)
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in t
    in l
    in t
  ```

  </details>

**Comment by SaraVieira** [comment]
Hey!

Can you please tell us what you were doing when thismis crash occured?

**Comment by cheikh268** [comment]
Bonjour ! j'aimerais que vous m'aidez a réalise mon projet je suis un débutant ...je ne métrise  pas bien la plateforme GitHub.

**Comment by MichaelDeBoey** [comment]
> Bonjour ! j'aimerais que vous m'aidez a réalise mon projet je suis un débutant ...je ne métrise pas bien la plateforme GitHub.

Translation via Google Translate:
> Hello ! I would like you to help me realize my project I am a beginner ... I do not understand the GitHub platform well.

**Comment by cheikh268** [comment]
> Hey!
> 
> Pouvez-vous nous dire ce que vous faisiez lorsque cet accident s'est produit?
Bonjour ! j'aimerais que vous m'aidez un réalise mon projet je suis un débutant ... je ne métrise pas bien la plateforme GitHub.

**Comment by lbogdan** [comment]
Closing this as duplicate of #4374 .

@cheikh268 Please comment on that ^^ issue instead. Thanks!
