### ISSUE TITLE
Sandbox breaks on load, no error message, never progresses past placeholder ui

### ISSUE THREAD

**Issue by brumm** [codesandbox/codesandbox-client#3804]
# 🐛 bug report

## Description of the problem

tried to load random example sandbox for `react-sortable-tree`, no error message, never progresses past placeholder ui

here's the error message, click to toggle full stack
<details>
<summary>index.js:27 ModuleNotFoundError: Could not find module in path: 'react-dnd/lib/DragDropContext' relative to '/node_modules/react-sortable-tree/dist/index.cjs.js'</summary>
```
index.js:27 ModuleNotFoundError: Could not find module in path: 'react-dnd/lib/DragDropContext' relative to '/node_modules/react-sortable-tree/dist/index.cjs.js'
    at n (https://codesandbox.io/static/js/sandbox.741f3740d.js:1:34070)
    at new n (https://codesandbox.io/static/js/sandbox.741f3740d.js:1:32681)
    at e.value (https://codesandbox.io/static/js/sandbox.741f3740d.js:1:225026)
    at e.value (https://codesandbox.io/static/js/sandbox.741f3740d.js:1:225888)
    at t (https://codesandbox.io/static/js/sandbox.741f3740d.js:1:195921)
    at evaluate (https://xj7mmx93xz.csb.app/node_modules/react-sortable-tree/dist/index.cjs.js:11:23)
    at Qr (https://codesandbox.io/static/js/sandbox.741f3740d.js:1:179600)
    at e.value (https://codesandbox.io/static/js/sandbox.741f3740d.js:1:196180)
    at e.value (https://codesandbox.io/static/js/sandbox.741f3740d.js:1:218288)
    at t (https://codesandbox.io/static/js/sandbox.741f3740d.js:1:195992)
    at evaluate (https://xj7mmx93xz.csb.app/src/index.js:21:50)
    at Qr (https://codesandbox.io/static/js/sandbox.741f3740d.js:1:179600)
    at e.value (https://codesandbox.io/static/js/sandbox.741f3740d.js:1:196180)
    at e.value (https://codesandbox.io/static/js/sandbox.741f3740d.js:1:218288)
    at e.value (https://codesandbox.io/static/js/sandbox.741f3740d.js:1:217892)
    at https://codesandbox.io/static/js/sandbox.741f3740d.js:1:256925
    at d (https://codesandbox.io/static/js/common-sandbox.8155934d5.chunk.js:1:13828)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.8155934d5.chunk.js:1:13616)
    at Generator.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.8155934d5.chunk.js:1:14250)
    at t (https://codesandbox.io/static/js/common-sandbox.8155934d5.chunk.js:1:8537)
    at i (https://codesandbox.io/static/js/common-sandbox.8155934d5.chunk.js:1:8747)
```
</details>

### Link to sandbox: [link](https://codesandbox.io/s/xj7mmx93xz)

**Comment by brumm** [comment]
Sure, my point is rather that codesandbox-client should not completely break if there's an error in the sandbox's code :)

**Comment by CompuIves** [comment]
Oh interesting, thanks for letting us know about updating the service worker. It could be that an older version had issues with it.
