### ISSUE TITLE
Codesandbox crashed when clicked on the small message icon beside editor line numbers

### ISSUE THREAD

**Issue by reachtokish** [codesandbox/codesandbox-client#4239]
<h1>💥 Crash Report</h1>

  <h2>I was trying out something on React. Then I saw a small message kind of icon beside the line numbers in the editor area. It seemed like I can comment on the line. When I clicked on that and it appeared a screen where the message was something like it crashed.</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: <a href="https://codesandbox.io/s/interesting-glitter-5i0sl?file=/src/App.js">Link</a></h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 81.0.4044 | Windows 10           | 3f53157da          |

  **Route:**
  https://codesandbox.io/s/interesting-glitter-5i0sl?file=/src/App.js

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'id' of undefined
  TypeError: Cannot read property 'id' of undefined
    at https://codesandbox.io/static/js/app.719d61325.js:571:1009859
    at Array.map (<anonymous>)
    at zu (https://codesandbox.io/static/js/app.719d61325.js:571:1009792)
    at ua (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1735529)
    at xs (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1780792)
    at ml (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1766368)
    at hl (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1766293)
    at il (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1763621)
    at https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1721804
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1797140)
    at qo (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1721513)
    at Yo (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1721749)
    at $o (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1721684)
    at el (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1760407)
    at Sa (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1739202)
    at forceRerender (https://codesandbox.io/static/js/vendors~app.ece734bf0.chunk.js:1:922189)
    at e.callback (https://codesandbox.io/static/js/vendors~app.ece734bf0.chunk.js:1:1043031)
    at b.flush (https://codesandbox.io/static/js/vendors~app.ece734bf0.chunk.js:1:1045951)
    at h.flush (https://codesandbox.io/static/js/vendors~app.ece734bf0.chunk.js:1:1042085)
    at Object.cb (https://codesandbox.io/static/js/vendors~app.ece734bf0.chunk.js:1:931462)
    at e.emit (https://codesandbox.io/static/js/vendors~app.ece734bf0.chunk.js:1:925307)
    at comments.onCommentClick (https://codesandbox.io/static/js/vendors~app.ece734bf0.chunk.js:1:934102)
    at Object.onCommentClick (https://codesandbox.io/static/js/vendors~app.ece734bf0.chunk.js:1:933027)
    at https://codesandbox.io/static/js/app.719d61325.js:571:443300
  
    in zu
    in vf
    in je
    in Unknown
    in je
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

**Comment by CodeSandboxNotifications** [comment]
Oh no,


That should not have happened, seemed to be a glitch between to tow deployments and I can never see it again as that is something we are working on that's under development and hidden for now


Please reopen if you see it again



--- original message ---
On May 30, 2020, 7:01 AM GMT+2 notifications@github.com wrote:



💥 Crash Report

I was trying out something on React. Then I saw a small message kind of icon beside the line numbers in the editor area. It seemed like I can comment on the line. When I clicked on that and it appeared a screen where the message was something like it crashed.

> Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!


Link to sandbox: Link

Crash Details
EnvironmentBrowser Version Operating System CodeSandbox Version 
chrome 81.0.4044 Windows 10 3f53157 


Route:

https://codesandbox.io/s/interesting-glitter-5i0sl?file=/src/App.js
Error Message
TypeError: Cannot read property 'id' of undefined
TypeError: Cannot read property 'id' of undefined
at https://codesandbox.io/static/js/app.719d61325.js:571:1009859
at Array.map (<anonymous>)
at zu (https://codesandbox.io/static/js/app.719d61325.js:571:1009792)
at ua (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1735529)
at xs (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1780792)
at ml (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1766368)
at hl (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1766293)
at il (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1763621)
at https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1721804
at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1797140)
at qo (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1721513)
at Yo (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1721749)
at $o (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1721684)
at el (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1760407)
at Sa (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1739202)
at forceRerender (https://codesandbox.io/static/js/vendors~app.ece734bf0.chunk.js:1:922189)
at e.callback (https://codesandbox.io/static/js/vendors~app.ece734bf0.chunk.js:1:1043031)
at b.flush (https://codesandbox.io/static/js/vendors~app.ece734bf0.chunk.js:1:1045951)
at h.flush (https://codesandbox.io/static/js/vendors~app.ece734bf0.chunk.js:1:1042085)
at Object.cb (https://codesandbox.io/static/js/vendors~app.ece734bf0.chunk.js:1:931462)
at e.emit (https://codesandbox.io/static/js/vendors~app.ece734bf0.chunk.js:1:925307)
at comments.onCommentClick (https://codesandbox.io/static/js/vendors~app.ece734bf0.chunk.js:1:934102)
at Object.onCommentClick (https://codesandbox.io/static/js/vendors~app.ece734bf0.chunk.js:1:933027)
at https://codesandbox.io/static/js/app.719d61325.js:571:443300

in zu
in vf
in je
in Unknown
in je
in Unknown
in Unknown
in Unknown
in t
in t
in div
in elements__Content
in n
in withRouter(n)
in div
in elements__Container
in Unknown
in withRouter()
in t
in Unknown
in je
in c
in t


—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---
