### ISSUE TITLE
Copy to Clipboard on external resources

### ISSUE THREAD

**Issue by deadcoder0904** [codesandbox/codesandbox-client#4240]
# 🌈 Feature

I have been using Classless CSS to make my codesandboxes look decent so would love to have a copy-to-cliboard button (or icon, next to close) on external resources section so when I create new sandboxes I can easily add them.

**Comment by siddharthkp** [comment]
I didn't completely understand, can you give an example?

**Comment by deadcoder0904** [comment]
Just like there is an copy-to-clipboard icon on https://clipboardjs.com/ for code blocks `<pre />`

I would love the same under external resources where I put external **CSS**. Apparently, clicking on it opens the **CSS** in `New Tab`. Here's the demo, check the 🟦 thing:

![codesandbox](https://user-images.githubusercontent.com/16436270/83329807-23156980-a2a9-11ea-8b30-e887780444a2.png)

Apparently, just realized you can right-click & do `Copy Link Address` but still think this is handy :)

**Comment by deadcoder0904** [comment]
This is because I constantly make Sandboxes & want to add these links to my new sandbox but apparently don't remember where I got these CSS from online.

So I open the codesandbox (which I remember has that CSS) & click it which opens new tab. This isn't a big issue but still a little improvement.

Also, I hate the overlapping icons under `dependencies`, i.e, `version no.`, `Update to Latest` (refresh icon) & `Remove` (close icon). Again just a minor issue :)

**Comment by siddharthkp** [comment]
> This is because I constantly make Sandboxes & want to add these links to my new sandbox but apparently don't remember where I got these CSS from online.

Makes sense to me!

> Also, I hate the overlapping icons under dependencies, i.e, version no., Update to Latest (refresh icon) & Remove (close icon). Again just a minor issue :)

what do you hate about it?

**Comment by deadcoder0904** [comment]
> what do you hate about it?

"hate" is a strong word. "don't like it" is appropriate 😂 

it's just awkward to see overlapping things

**Comment by siddharthkp** [comment]
Gotcha!

Would you like to implement click to copy as suggested in your solution? This is the right file to add to: [ExternalResources](https://github.com/codesandbox/codesandbox-client/blob/master/packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Explorer/ExternalResources/index.tsx)

**Comment by deadcoder0904** [comment]
Huh, I tried it multiple times (~30 mins) but can't get the client running. Here's the log:

```bash
❯ yarn start
yarn run v1.22.4
$ yarn build:deps && cross-env NODE_ENV=development lerna run start --scope @codesandbox/common --scope @codesandbox/components --scope app --parallel
$ lerna run build:dev
lerna notice cli v3.16.4
lerna info versioning independent
lerna info Executing command in 11 packages: "npm run build:dev"
lerna info run Ran npm script 'build:dev' in 'template-icons' in 2.3s:

> template-icons@1.0.0 build:dev F:\Coding\Overmind\codesandbox-client\packages\template-icons
> npm run build


> template-icons@1.0.0 build F:\Coding\Overmind\codesandbox-client\packages\template-icons
> babel src --out-dir lib --extensions '.ts,.tsx'

Successfully compiled 0 files with Babel.
lerna info run Ran npm script 'build:dev' in 'codesandbox-deps' in 6.9s:

> codesandbox-deps@0.1.1 build:dev F:\Coding\Overmind\codesandbox-client\packages\deps
> yarn build

$ yarn build:clean && yarn build:rollup
$ rimraf dist
$ rollup -c
lerna info run Ran npm script 'build:dev' in 'vscode-textmate' in 11.0s:

> vscode-textmate@4.0.1 build:dev F:\Coding\Overmind\codesandbox-client\standalone-packages\vscode-textmate
> tsc

lerna info run Ran npm script 'build:dev' in 'codesandbox-api' in 26.1s:

> codesandbox-api@0.0.24 build:dev F:\Coding\Overmind\codesandbox-client\packages\codesandbox-api
> tsc && rollup -c

lerna info run Ran npm script 'build:dev' in 'sse-hooks' in 9.3s:

> sse-hooks@0.1.0 build:dev F:\Coding\Overmind\codesandbox-client\packages\sse-hooks
> rollup -c rollup.config.js

lerna info run Ran npm script 'build:dev' in 'codesandbox-browserfs' in 62.8s:

> codesandbox-browserfs@2.0.0 build:dev F:\Coding\Overmind\codesandbox-client\standalone-packages\codesandbox-browserfs
> npm-run-all build script:make_dist dist:build:node


> codesandbox-browserfs@2.0.0 build F:\Coding\Overmind\codesandbox-client\standalone-packages\codesandbox-browserfs
> npm-run-all --parallel build:tsc build:scripts --sequential build:rollup --parallel build:webpack build:webpack-release


> codesandbox-browserfs@2.0.0 build:tsc F:\Coding\Overmind\codesandbox-client\standalone-packages\codesandbox-browserfs
> tsc -p src


> codesandbox-browserfs@2.0.0 build:scripts F:\Coding\Overmind\codesandbox-client\standalone-packages\codesandbox-browserfs
> tsc -p scripts


> codesandbox-browserfs@2.0.0 build:rollup F:\Coding\Overmind\codesandbox-client\standalone-packages\codesandbox-browserfs
> rollup -c src/rollup.config.js


> codesandbox-browserfs@2.0.0 build:webpack F:\Coding\Overmind\codesandbox-client\standalone-packages\codesandbox-browserfs
> webpack  --mode development --config src/webpack.config.js


> codesandbox-browserfs@2.0.0 build:webpack-release F:\Coding\Overmind\codesandbox-client\standalone-packages\codesandbox-browserfs
> webpack -p --config src/webpack.config.js

Hash: d556c22def544d51bd67
Version: webpack 4.31.0
Time: 2769ms
Built at: 06/02/2020 11:47:08 AM
                    Asset     Size  Chunks             Chunk Names
    ..\build\browserfs.js  724 KiB    main  [emitted]  main
..\build\browserfs.js.map  861 KiB    main  [emitted]  main
Entrypoint main = ..\build\browserfs.js ..\build\browserfs.js.map
[0] util (ignored) 15 bytes {main} [built]
[./build/temp/library/rollup/browserfs.rollup.js] 422 KiB {main} [built]
[./build/temp/library/webpack/BFSBuffer.js] 43 bytes {main} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {main} [built]
    + 41 hidden modules
Hash: cca9db6c8fdbbec4b804
Version: webpack 4.31.0
Time: 2676ms
Built at: 06/02/2020 11:47:13 AM
                        Asset      Size  Chunks             Chunk Names
    ..\build\browserfs.min.js   227 KiB       0  [emitted]  main
..\build\browserfs.min.js.map  1.01 MiB       0  [emitted]  main
Entrypoint main = ..\build\browserfs.min.js ..\build\browserfs.min.js.map
 [6] (webpack)/buildin/global.js 472 bytes {0} [built]
 [9] ./build/temp/library/webpack/BFSBuffer.js 43 bytes {0} [built]
[19] ./build/temp/library/rollup/browserfs.rollup.js 422 KiB {0} [built]
[26] util (ignored) 15 bytes {0} [built]
    + 41 hidden modules

> codesandbox-browserfs@2.0.0 script:make_dist F:\Coding\Overmind\codesandbox-client\standalone-packages\codesandbox-browserfs
> node build/scripts/make_dist.js


> codesandbox-browserfs@2.0.0 dist:build:node F:\Coding\Overmind\codesandbox-client\standalone-packages\codesandbox-browserfs
> tsc -p src/tsconfig.node.json

lerna info run Ran npm script 'build:dev' in '@codesandbox/components' in 39.3s:

> @codesandbox/components@0.0.2 build:dev F:\Coding\Overmind\codesandbox-client\packages\components
> yarn build

$ yarn build:lib
$ yarn clean && yarn tsc
$ rimraf lib && yarn rimraf node_modules/@types/react && yarn rimraf node_modules/@types/react-native
$ F:\Coding\Overmind\codesandbox-client\node_modules\.bin\rimraf node_modules/@types/react
$ F:\Coding\Overmind\codesandbox-client\node_modules\.bin\rimraf node_modules/@types/react-native
$ F:\Coding\Overmind\codesandbox-client\node_modules\.bin\tsc
lerna info run Ran npm script 'build:dev' in '@codesandbox/notifications' in 20.6s:

> @codesandbox/notifications@1.0.6 build:dev F:\Coding\Overmind\codesandbox-client\packages\notifications
> yarn build

$ rimraf lib && tsc
lerna ERR! npm run build:dev exited 2 in '@codesandbox/common'
lerna ERR! npm run build:dev stdout:

> @codesandbox/common@1.0.8 build:dev F:\Coding\Overmind\codesandbox-client\packages\common
> yarn build

$ yarn build:lib
$ yarn clean && yarn tsc && yarn babel src --out-dir lib && yarn cpx "src/**/*.{css,svg,png,jpg,woff,woff2}" lib
$ rimraf lib && yarn rimraf node_modules/@types/react-native
$ F:\Coding\Overmind\codesandbox-client\node_modules\.bin\rimraf node_modules/@types/react-native
$ F:\Coding\Overmind\codesandbox-client\node_modules\.bin\tsc
src/components/Template/UserTemplate.tsx(2,37): error TS2307: Cannot find module 'template-icons'.
src/templates/icons.ts(28,8): error TS2307: Cannot find module 'template-icons'.
src/utils/getTemplateIcon.ts(1,37): error TS2307: Cannot find module 'template-icons'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! npm run build:dev stderr:
warning package.json: No license field
warning package.json: No license field
warning package.json: No license field
warning package.json: No license field
warning package.json: No license field
error Command failed with exit code 2.
error Command failed with exit code 2.
error Command failed with exit code 2.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @codesandbox/common@1.0.8 build:dev: `yarn build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @codesandbox/common@1.0.8 build:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DEADMAN.INC\AppData\Roaming\npm-cache\_logs\2020-06-02T06_18_42_534Z-debug.log

lerna ERR! npm run build:dev exited 2 in '@codesandbox/common'
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

And the log file:

```log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:dev' ]
2 info using npm@6.9.0
3 info using node@v10.16.2
4 verbose run-script [ 'prebuild:dev', 'build:dev', 'postbuild:dev' ]
5 info lifecycle @codesandbox/common@1.0.8~prebuild:dev: @codesandbox/common@1.0.8
6 info lifecycle @codesandbox/common@1.0.8~build:dev: @codesandbox/common@1.0.8
7 verbose lifecycle @codesandbox/common@1.0.8~build:dev: unsafe-perm in lifecycle true
8 verbose lifecycle @codesandbox/common@1.0.8~build:dev: PATH: C:\Users\DEADMAN.INC\AppData\Roaming\nvm\v10.16.2\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;F:\Coding\Overmind\codesandbox-client\packages\common\node_modules\.bin;F:\Coding\Overmind\codesandbox-client\packages\common\node_modules\.bin;F:\Coding\Overmind\codesandbox-client\packages\node_modules\.bin;F:\Coding\Overmind\codesandbox-client\node_modules\.bin;F:\Coding\Overmind\node_modules\.bin;F:\Coding\node_modules\.bin;F:\node_modules\.bin;C:\Program Files\nodejs;C:\Users\DEADMAN.INC\AppData\Local\Temp\yarn--1591078581135-0.9088522854424677;F:\Coding\Overmind\codesandbox-client\node_modules\.bin;C:\Users\DEADMAN.INC\AppData\Local\Yarn\Data\link\node_modules\.bin;F:\Coding\Overmind\codesandbox-client\node_modules\.bin;C:\Program Files\libexec\lib\node_modules\npm\bin\node-gyp-bin;C:\Program Files\lib\node_modules\npm\bin\node-gyp-bin;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\DEADMAN.INC\AppData\Local\Temp\yarn--1591078580838-0.9871900414085473;F:\Coding\Overmind\codesandbox-client\node_modules\.bin;C:\Users\DEADMAN.INC\AppData\Local\Yarn\Data\link\node_modules\.bin;F:\Coding\Overmind\codesandbox-client\node_modules\.bin;C:\Program Files\libexec\lib\node_modules\npm\bin\node-gyp-bin;C:\Program Files\lib\node_modules\npm\bin\node-gyp-bin;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\Calibre2\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\dotnet\;C:\Users\DEADMAN.INC\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\DEADMAN.INC\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\DEADMAN.INC\AppData\Local\Programs\Python\Python37-32\;C:\Users\DEADMAN.INC\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\DEADMAN.INC\AppData\Local\Programs\Python\Python38-32\;C:\Ruby25-x64\bin;C:\Users\DEADMAN.INC\.windows-build-tools\python27\;node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\DEADMAN.INC\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\.bin;C:\Users\DEADMAN.INC\AppData\Roaming\npm\node_modules\.bin;C:\ProgramData\chocolatey\bin;C:\Users\DEADMAN.INC\AppData\Local\Microsoft\WindowsApps;C:\Users\DEADMAN.INC\AppData\Local\hyper\app-3.0.2\resources\bin;C:\Users\DEADMAN.INC\AppData\Roaming\npm;C:\Users\DEADMAN.INC\AppData\Local\Microsoft\WindowsApps;C:\Users\DEADMAN.INC\AppData\Local\Yarn\bin;C:\Program Files\Sublime Text 3\subl.exe;C:\Users\DEADMAN.INC\AppData\Roaming\nvm;C:\Program Files\nodejs
9 verbose lifecycle @codesandbox/common@1.0.8~build:dev: CWD: F:\Coding\Overmind\codesandbox-client\packages\common
10 silly lifecycle @codesandbox/common@1.0.8~build:dev: Args: [ '/d /s /c', 'yarn build' ]
11 silly lifecycle @codesandbox/common@1.0.8~build:dev: Returned: code: 2  signal: null
12 info lifecycle @codesandbox/common@1.0.8~build:dev: Failed to exec build:dev script
13 verbose stack Error: @codesandbox/common@1.0.8 build:dev: `yarn build`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\DEADMAN.INC\AppData\Roaming\nvm\v10.16.2\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\DEADMAN.INC\AppData\Roaming\nvm\v10.16.2\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @codesandbox/common@1.0.8
15 verbose cwd F:\Coding\Overmind\codesandbox-client\packages\common
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:dev"
18 verbose node v10.16.2
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 2
22 error @codesandbox/common@1.0.8 build:dev: `yarn build`
22 error Exit status 2
23 error Failed at the @codesandbox/common@1.0.8 build:dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

But should be easy enough to implement using https://github.com/zenorocha/clipboard.js as it supports older versions too & `MdContentCopy` from https://react-icons.github.io/react-icons/icons?name=md

**Comment by deadcoder0904** [comment]
On Windows, so it sucks.

PS: On [CONTRIBUTING](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md) you should add https://github.com/coreybutler/nvm-windows on point 2 as `fnm` only supports Linux & Mac :)

**Comment by softmarshmallow** [comment]
```
Cannot find module '@codesandbox/common/lib/version'
```

having similar problem here
