### ISSUE TITLE
attempting to change the default browsers. now it breaks when starting up

### ISSUE THREAD

**Issue by ruttyj** [codesandbox/codesandbox-client#4252]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

attempting to change the default browsers. now it breaks when starting up

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 83.0.4103 | Windows 10           | d5beccdb5          |

  **Route:**
  https://codesandbox.io/s/focused-tree-zq70d

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'Content' of undefined
  TypeError: Cannot read property 'Content' of undefined
    at https://codesandbox.io/static/js/default~app~embed.ee17c125e.chunk.js?_sw-precache=becb5b025a46e143445e181fe47baafd:550:123557
    at Array.map (<anonymous>)
    at n.value (https://codesandbox.io/static/js/default~app~embed.ee17c125e.chunk.js?_sw-precache=becb5b025a46e143445e181fe47baafd:550:123514)
    at Ya (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1746970)
    at $a (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1746763)
    at xs (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1782064)
    at ml (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1766368)
    at hl (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1766293)
    at il (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1763621)
    at https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1721804
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1797140)
    at qo (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1721513)
    at Yo (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1721749)
    at $o (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1721684)
    at se (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1790892)
    at Sn (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:1705310)
    at HTMLDocument.r (https://codesandbox.io/static/js/common.8f6fa98d0.chunk.js:1:145201)
  
    in n
    in div
    in div
    in t
    in div
    in t
    in div
    in je
    in Fe
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in je
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

**Comment by CompuIves** [comment]
Hey! Looking into this now, how did you change the default browser?

**Comment by lbogdan** [comment]
`this.getViews()[view.id]` returns `undefined`, so the destructuring fails here:

https://github.com/codesandbox/codesandbox-client/blob/66714e552553a38475a9386e34b281a201dbddb1/packages/app/src/app/components/Preview/DevTools/index.tsx#L507
