### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by pugnascotia** [codesandbox/codesandbox-client#4281]
# 🐛 bug report

## Description of the problem

I can't use my repo as a template. It used to work in the past.

## How has this issue affected you? What are you trying to accomplish?

The Next build process appear to work although it takes a while, and the browser pane reports a 502. Then once the console claims the site is ready and I refresh the browser pane, I get this in the console:

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:762:20)
    at ChildProcess.target.send (internal/child_process.js:634:19)
    at ChildProcessWorker.initialize (/sandbox/node_modules/jest-worker/build/workers/ChildProcessWorker.js:181:11)
    at ChildProcessWorker.onExit (/sandbox/node_modules/jest-worker/build/workers/ChildProcessWorker.js:263:12)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
Emitted 'error' event at:
    at process.nextTick (internal/child_process.js:766:39)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | |
| Browser          | Firefox 76.0    |
| Operating System | Mac OSX 10.14.6 |

**Comment by lbogdan** [comment]
Hey @pugnascotia ,

Sorry you're running into this issue, unfortunately it's a memory one: we're hard-limiting the sandbox containers to 1GB of memory, and your app is trying to use more than that and it gets OOM (out-of-memory) killed - EPIPE and exit code 137 are usually symptoms of that.

> It used to work in the past.

That's weird, maybe packages were updated and as a result it's using more memory?

**Comment by lbogdan** [comment]
Hey @pugnascotia ,

I just tried this again and it seems to be working, can you confirm it's working for you, too? Thanks!

**Comment by pugnascotia** [comment]
Oh wow, so it does. I've updated the dependencies (notably Next.js) since I raised this issue, it must have helped. Thanks!

**Comment by lbogdan** [comment]
Glad it works! (Re)closing it for now, please reopen if you experience further issues.
