### ISSUE TITLE
Crash when searching npm after forking Sandbox + removing deps

### ISSUE THREAD

**Issue by shuckster** [codesandbox/codesandbox-client#4447]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

Steps taken:

1. **Forked** existing public Sandbox
2. Made it **Private**
3. Deleted several **dependencies**: react, react-dom, react-scripts
4. Clicked **Add dependency**
5. Started typing to perform **search**
6. Crash!

Hope this is enough to investigate the issue.

Thanks so much for this otherwise excellent tool.

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 83.0.4103 | OS X 10.15.5           | 47dceead3          |

  **Route:**
  https://codesandbox.io/dashboard/recent

  **Error Code:**
cb0938a24d4b469eaf54eea932f3d806

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  Error: Unable to parse color from string "#00000060"
  Error: Unable to parse color from string "#00000060"
    at new a (https://codesandbox.io/static/js/common.45abdf43d.chunk.js:1:2405164)
    at a (https://codesandbox.io/static/js/common.45abdf43d.chunk.js:1:2404921)
    at https://codesandbox.io/static/js/app.2a37e69a6.js:568:53206
    at ce (https://codesandbox.io/static/js/common.45abdf43d.chunk.js:1:2118250)
    at e.generateAndInjectStyles (https://codesandbox.io/static/js/common.45abdf43d.chunk.js:1:2119877)
    at https://codesandbox.io/static/js/common.45abdf43d.chunk.js:1:2121190
    at Te (https://codesandbox.io/static/js/common.45abdf43d.chunk.js:1:2121257)
    at elements__License (https://codesandbox.io/static/js/common.45abdf43d.chunk.js:1:2122380)
    at ua (https://codesandbox.io/static/js/common.45abdf43d.chunk.js:1:1734358)
    at Wa (https://codesandbox.io/static/js/common.45abdf43d.chunk.js:1:1741753)
    at Es (https://codesandbox.io/static/js/common.45abdf43d.chunk.js:1:1781820)
    at ml (https://codesandbox.io/static/js/common.45abdf43d.chunk.js:1:1765197)
    at hl (https://codesandbox.io/static/js/common.45abdf43d.chunk.js:1:1765122)
    at il (https://codesandbox.io/static/js/common.45abdf43d.chunk.js:1:1762450)
    at https://codesandbox.io/static/js/common.45abdf43d.chunk.js:1:1720633
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.45abdf43d.chunk.js:1:1795969)
    at qo (https://codesandbox.io/static/js/common.45abdf43d.chunk.js:1:1720342)
    at Yo (https://codesandbox.io/static/js/common.45abdf43d.chunk.js:1:1720578)
    at $o (https://codesandbox.io/static/js/common.45abdf43d.chunk.js:1:1720513)
    at el (https://codesandbox.io/static/js/common.45abdf43d.chunk.js:1:1759236)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.45abdf43d.chunk.js:1:1725337)
    at g._.setState (https://codesandbox.io/static/js/common.45abdf43d.chunk.js:1:2033842)
    at https://codesandbox.io/static/js/vendors~app.10b5c084c.chunk.js:1:1413612
    at https://codesandbox.io/static/js/vendors~app.10b5c084c.chunk.js:1:1419518
    at Array.forEach (<anonymous>)
    at Object.setState (https://codesandbox.io/static/js/vendors~app.10b5c084c.chunk.js:1:1419490)
    at m.<anonymous> (https://codesandbox.io/static/js/vendors~app.10b5c084c.chunk.js:1:1422484)
    at m.a.emit (https://codesandbox.io/static/js/vendors~app~embed~jest-lite.3c2f7afa6.chunk.js:1:49871)
    at https://codesandbox.io/static/js/vendors~app.10b5c084c.chunk.js:1:247689
    at e.exports (https://codesandbox.io/static/js/vendors~app.10b5c084c.chunk.js:1:960329)
    at e.exports (https://codesandbox.io/static/js/vendors~app.10b5c084c.chunk.js:1:994103)
    at m._dispatchAlgoliaResponse (https://codesandbox.io/static/js/vendors~app.10b5c084c.chunk.js:1:247585)
  
    in elements__License
    in div
    in elements__Row
    in div
    in elements__Left
    in div
    in elements__Container
    in n
    in div
    in div
    in t
    in n
    in AlgoliaAutoComplete(n)
    in div
    in t
    in n
    in div
    in n
    in Component
    in div
    in div
    in div
    in div
    in t
    in t
    in Modal___StyledModal
    in n
    in je
    in Unknown
    in zu
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

**Comment by shuckster** [comment]
Just noticed the fix, thank you!
