### ISSUE TITLE
NextJS template  - typed something in the add dependency search box

### ISSUE THREAD

**Issue by thomasmery** [codesandbox/codesandbox-client#4565]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > just as the title says

then it crashed

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 81.0.4044 | OS X 10.15.2           | baeed1ee1          |

  **Route:**
  https://codesandbox.io/s/admiring-almeida-xk0q6

  **Error Code:**
fcea8edf412e42cdb71a8411629faa03

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot convert undefined or null to object
  TypeError: Cannot convert undefined or null to object
    at https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:167638
    at n.<anonymous> (https://codesandbox.io/static/js/app.de7cc5a21.js:551:141410)
    at _i (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1726220)
    at yi (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1725956)
    at yl (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1777538)
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1797332)
    at qo (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1721705)
    at bl (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1773685)
    at il (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1764012)
    at https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1721996
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1797332)
    at qo (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1721705)
    at Yo (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1721941)
    at $o (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1721876)
    at https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1791203
    at le (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1791209)
    at fe (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1681549)
    at On (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1705863)
    at Mn (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1706791)
    at Tn (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1706079)
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1797332)
    at qo (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1721705)
    at se (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1791038)
    at Sn (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1705502)
  
    in n
    in AlgoliaAutoComplete(n)
    in div
    in t
    in n
    in div
    in n
    in Component
    in div
    in div
    in div
    in div
    in t
    in t
    in Modal___StyledModal
    in n
    in je
    in Unknown
    in Fc
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

**Comment by SaraVieira** [comment]
Hey!

I know this may not be the easiest thing to remember but do you know what you're were typing?

**Comment by thomasmery** [comment]
hi,

I was typing ... `ms` or something like that

but this is not related I think
the sandbox crashed again just after that when trying to use it again
I successfully added the dependency then but the sandbox crashed after the install process
a third time when I clicked on a file in the explorer

I've had a lot of crashed lately - w/ completely unrelated actions and/or sandboxes

here is the latest crash error

```bash
  TypeError: Cannot convert undefined or null to object
  TypeError: Cannot convert undefined or null to object
    at https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:167638
    at https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1664704
    at Es (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1784300)
    at ml (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1766560)
    at hl (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1766485)
    at il (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1763813)
    at https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1721996
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1797332)
    at qo (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1721705)
    at Yo (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1721941)
    at $o (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1721876)
    at el (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1760599)
    at Sa (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1739394)
    at forceRerender (https://codesandbox.io/static/js/vendors~app.a7fdf041d.chunk.js:1:1051699)
    at e.callback (https://codesandbox.io/static/js/vendors~app.a7fdf041d.chunk.js:1:1174078)
    at b.flush (https://codesandbox.io/static/js/vendors~app.a7fdf041d.chunk.js:1:1176907)
    at h.flush (https://codesandbox.io/static/js/vendors~app.a7fdf041d.chunk.js:1:1173132)
    at t (https://codesandbox.io/static/js/vendors~app.a7fdf041d.chunk.js:1:1061087)
    at r (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:166028)
  
    in DropTarget(Component)
    in div
    in Is
    in div
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in Styled(styled.div)
    in section
    in Styled(styled.div)
    in Unknown
    in Files___StyledCollapsible
    in $s
    in Ys
    in div
    in je
    in Unknown
    in div
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in je
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

don't know if that might be related to my account? ...

**Comment by CompuIves** [comment]
I've seen this report in sentry too, I think it's unrelated to the dependency search modal, but definitely something that happens more often. I'll add the sentry link
