### ISSUE TITLE
package.json error

### ISSUE THREAD

**Issue by lokeshsundaresan** [codesandbox/codesandbox-client#4592]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 84.0.4147 | Windows 10           | 1ed71a491          |

  **Route:**
  https://codesandbox.io/s/boring-sutherland-08eq4

  **Error Code:**
59f14c930db444468fcd2f48f7f3ab07

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'parsed' of undefined
  TypeError: Cannot read property 'parsed' of undefined
    at l.getEntries (https://codesandbox.io/static/js/default~app~embed~sandbox.254e4a9fd.chunk.js?_sw-precache=a760cfaecd0ae256922fa7d624af1729:1:22120)
    at i (https://codesandbox.io/static/js/app.938b87e55.js?_sw-precache=14c120a7c928c81f5ee2057f8ec57be4:551:880630)
    at l.cb (https://codesandbox.io/static/js/app.938b87e55.js?_sw-precache=14c120a7c928c81f5ee2057f8ec57be4:551:736455)
    at l.runScope (https://codesandbox.io/static/js/vendors~app.485fdf169.chunk.js?_sw-precache=9343216f143f15fb159bfa439cbc69c3:1:1056390)
    at l.evaluate (https://codesandbox.io/static/js/vendors~app.485fdf169.chunk.js?_sw-precache=9343216f143f15fb159bfa439cbc69c3:1:1056826)
    at Object.onFunction (https://codesandbox.io/static/js/vendors~app.485fdf169.chunk.js?_sw-precache=9343216f143f15fb159bfa439cbc69c3:1:1062470)
    at Object.get (https://codesandbox.io/static/js/vendors~app.485fdf169.chunk.js?_sw-precache=9343216f143f15fb159bfa439cbc69c3:1:1171517)
    at https://codesandbox.io/static/js/app.938b87e55.js?_sw-precache=14c120a7c928c81f5ee2057f8ec57be4:551:1146783
    at ua (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1735721)
    at Ka (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1743986)
    at qa (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1743805)
    at Es (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1784459)
    at ml (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1766560)
    at hl (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1766485)
    at il (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1763813)
    at https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1721996
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1797332)
    at qo (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1721705)
    at Yo (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1721941)
    at $o (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1721876)
    at el (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1760599)
    at Sa (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1739394)
    at forceRerender (https://codesandbox.io/static/js/vendors~app.485fdf169.chunk.js?_sw-precache=9343216f143f15fb159bfa439cbc69c3:1:1052115)
    at https://codesandbox.io/static/js/vendors~app.485fdf169.chunk.js?_sw-precache=9343216f143f15fb159bfa439cbc69c3:1:1174494
    at b.flush (https://codesandbox.io/static/js/vendors~app.485fdf169.chunk.js?_sw-precache=9343216f143f15fb159bfa439cbc69c3:1:1177323)
    at h.flush (https://codesandbox.io/static/js/vendors~app.485fdf169.chunk.js?_sw-precache=9343216f143f15fb159bfa439cbc69c3:1:1173548)
    at Object.cb (https://codesandbox.io/static/js/vendors~app.485fdf169.chunk.js?_sw-precache=9343216f143f15fb159bfa439cbc69c3:1:1061460)
    at e.emit (https://codesandbox.io/static/js/vendors~app.485fdf169.chunk.js?_sw-precache=9343216f143f15fb159bfa439cbc69c3:1:1055188)
    at live.internal.initializeModuleFromState (https://codesandbox.io/static/js/vendors~app.485fdf169.chunk.js?_sw-precache=9343216f143f15fb159bfa439cbc69c3:1:1064132)
    at Proxy.<anonymous> (https://codesandbox.io/static/js/vendors~app.485fdf169.chunk.js?_sw-precache=9343216f143f15fb159bfa439cbc69c3:1:1063057)
    at https://codesandbox.io/static/js/app.938b87e55.js?_sw-precache=14c120a7c928c81f5ee2057f8ec57be4:551:789966
    at Array.forEach (<anonymous>)
    at Rd (https://codesandbox.io/static/js/app.938b87e55.js?_sw-precache=14c120a7c928c81f5ee2057f8ec57be4:551:789918)
    at live.internal.initializeModuleState (https://codesandbox.io/static/js/vendors~app.485fdf169.chunk.js?_sw-precache=9343216f143f15fb159bfa439cbc69c3:1:1064064)
    at Proxy.<anonymous> (https://codesandbox.io/static/js/vendors~app.485fdf169.chunk.js?_sw-precache=9343216f143f15fb159bfa439cbc69c3:1:1063057)
    at https://codesandbox.io/static/js/app.938b87e55.js?_sw-precache=14c120a7c928c81f5ee2057f8ec57be4:551:788559
    at l (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255733)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255486)
    at Generator.forEach.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:256090)
    at t (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2405)
    at i (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2616)
  
    in Unknown
    in div
    in Is
    in div
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in Is
    in div
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in Styled(styled.div)
    in section
    in Styled(styled.div)
    in Unknown
    in Files___StyledCollapsible
    in $s
    in Ys
    in div
    in je
    in Unknown
    in div
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in je
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

**Comment by SaraVieira** [comment]
Thank you so much for the error report

Seems to have been fixed in the meantime from what I can see in our error tracking
