### ISSUE TITLE
Issue - error throws while editing html code

### ISSUE THREAD

**Issue by CrisAllen** [codesandbox/codesandbox-client#4665]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 74.0.3729 | Linux aarch64           | caab652ef          |

  **Route:**
  https://codesandbox.io/s/jolly-voice-vmddy?file=/index.html

  **Error Code:**
cbd3f609bbd94ba49d0002c8a09a8004

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot convert undefined or null to object
  TypeError: Cannot convert undefined or null to object
    at https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:167638
    at https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1705774
    at Es (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1821453)
    at ml (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1803713)
    at hl (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1803638)
    at il (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1800966)
    at https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1759149
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1834485)
    at qo (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1758858)
    at $o (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1759094)
    at Yo (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1759029)
    at el (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1797752)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1763853)
    at t._.setState (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:2068371)
    at https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1912380
    at r (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:902690)
    at https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:902920
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:902890)
    at k (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:904112)
    at https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:905497
    at Object.confirmTransitionTo (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:902629)
    at Object.replace (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:905281)
    at e.value (https://codesandbox.io/static/js/app.0542c17c5.js:306:493292)
    at https://codesandbox.io/static/js/app.0542c17c5.js:306:592390
    at b (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:979648)
    at C (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:979923)
    at w (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:979813)
    at r (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:166028)
  
    in DropTarget(Component)
    in div
    in elements__Tabs
    in div
    in elements__Container
    in Zt
    in div
    in elements__Header
    in div
    in elements__Container
    in n
    in div
    in div
    in t
    in div
    in t
    in div
    in je
    in Fe
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in je
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

**Comment by SaraVieira** [comment]
Hey!

Sorry for the delay but do you have any idea what you were doing when it crashed?

**Comment by SaraVieira** [comment]
Closing for lack of response
