### ISSUE TITLE
edit table

### ISSUE THREAD

**Issue by fcabreraco** [codesandbox/codesandbox-client#4687]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 84.0.4147 | Windows 10           | e53d68b35          |

  **Route:**
  https://codesandbox.io/dashboard/recent

  **Error Code:**
f097b9deea214940b741a247b0c68f13

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'subscription_plan' of null
  TypeError: Cannot read property 'subscription_plan' of null
    at Ws (https://codesandbox.io/static/js/app.4cb763821.js?_sw-precache=7ae713067cc964d2e3bd8d4f09f17aeb:306:222596)
    at ua (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1772874)
    at Es (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1818137)
    at ml (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1803713)
    at hl (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1803638)
    at il (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1800966)
    at https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1759149
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1834485)
    at qo (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1758858)
    at $o (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1759094)
    at Yo (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1759029)
    at se (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1828237)
    at Sn (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1742655)
  
    in Ws
    in tu
    in su
    in Yd
    in t
    in t
    in div
    in Content___StyledElement
    in Unknown
    in withRouter()
    in main
    in Dashboard___StyledElement2
    in div
    in Dashboard___StyledStack2
    in div
    in Dashboard___StyledStack
    in Unknown
    in je
    in Unknown
    in dp
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

**Comment by oskarabc** [comment]
Can you tell me what happened @fcabreraco and if you expect to run into this again?
