### ISSUE TITLE
It's showing something broke, not able to see dashboard in codesandbox

### ISSUE THREAD

**Issue by swetadash0610** [codesandbox/codesandbox-client#4702]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 84.0.4147 | Windows 10           | e99bee059          |

  **Route:**
  https://codesandbox.io/dashboard

  **Error Code:**
bf34c853c6694f68ba64c28236065d53

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'filter' of null
  TypeError: Cannot read property 'filter' of null
    at vl (https://codesandbox.io/static/js/app.da9b2f8cd.js?_sw-precache=3384404ce70235df5c2636b1c7898ec1:306:190404)
    at ua (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1772874)
    at Es (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1818137)
    at ml (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1803713)
    at hl (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1803638)
    at il (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1800966)
    at https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1759149
    at https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1834485
    at qo (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1758858)
    at $o (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1759094)
    at Yo (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1759029)
    at el (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1797752)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1763853)
    at t.setState (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:2068371)
    at https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1912380
    at r (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:902690)
    at https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:902920
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:902890)
    at k (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:904112)
    at https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:905166
    at Object.confirmTransitionTo (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:902629)
    at Object.push (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:904946)
    at https://codesandbox.io/static/js/app.da9b2f8cd.js?_sw-precache=3384404ce70235df5c2636b1c7898ec1:306:1173448
    at l (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255733)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255486)
    at Generator.forEach.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:256090)
    at t (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2405)
    at i (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2616)
  
    in vl
    in aside
    in Dashboard___StyledElement
    in t
    in div
    in Dashboard___StyledStack2
    in div
    in Dashboard___StyledStack
    in Unknown
    in je
    in Unknown
    in dp
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

**Comment by SaraVieira** [comment]
closed by 002236c

Sorry for the issues
