### ISSUE TITLE
Crash on dashboard

### ISSUE THREAD

**Issue by dagatsoin** [codesandbox/codesandbox-client#4704]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  I was on another website and I just acceded Codesandbox dashboard.

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 84.0.4147 | OS X 10.12.6           | e99bee059          |

  **Route:**
  https://codesandbox.io/dashboard

  **Error Code:**
3f5f368105264460be09d98b91bdd97c

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'filter' of null
  TypeError: Cannot read property 'filter' of null
    at vl (https://codesandbox.io/static/js/app.da9b2f8cd.js:306:190404)
    at ua (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1772874)
    at Es (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1818137)
    at ml (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1803713)
    at hl (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1803638)
    at il (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1800966)
    at el (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1797731)
    at Ul (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1825720)
    at https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1826955
    at sl (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1801314)
  
    in vl
    in aside
    in Dashboard___StyledElement
    in t
    in div
    in Dashboard___StyledStack2
    in div
    in Dashboard___StyledStack
    in Unknown
    in je
    in Unknown
    in dp
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

**Comment by SaraVieira** [comment]
closed by 002236c

Sorry for the issues
