### ISSUE TITLE
Crashed navigating to site (logged-in state)

### ISSUE THREAD

**Issue by wbellman** [codesandbox/codesandbox-client#4730]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > I was attempting to navigate to "codesandbox.io" while logged in.  I tried relogging but it did not make a difference.

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 84.0.4147 | Windows 10           | e99bee059          |

  **Route:**
  https://codesandbox.io/dashboard

  

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'filter' of null
  TypeError: Cannot read property 'filter' of null
    at vl (https://codesandbox.io/static/js/app.da9b2f8cd.js:306:190404)
    at ua (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1772874)
    at Es (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1818137)
    at ml (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1803713)
    at hl (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1803638)
    at il (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1800966)
    at https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1759149
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1834485)
    at qo (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1758858)
    at $o (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1759094)
  
    in vl
    in aside
    in Dashboard___StyledElement
    in t
    in div
    in Dashboard___StyledStack2
    in div
    in Dashboard___StyledStack
    in Unknown
    in je
    in Unknown
    in dp
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

**Comment by SaraVieira** [comment]
closed by 002236c

Sorry for the issues
