### ISSUE TITLE
crash report codesandbox react

### ISSUE THREAD

**Issue by Cvan23** [codesandbox/codesandbox-client#4815]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 85.0.4183 | Windows 10           | 926e6e0d2          |

  **Route:**
  https://codesandbox.io/s/new

  **Error Code:**
f606bceb10b6401f9285425398a8d8d1

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'id' of undefined
  TypeError: Cannot read property 'id' of undefined
    at https://codesandbox.io/static/js/app.22c21a658.js?_sw-precache=15dda38ef6014080001dd838cd7fd39c:306:870053
    at Array.map (<anonymous>)
    at Wn (https://codesandbox.io/static/js/app.22c21a658.js?_sw-precache=15dda38ef6014080001dd838cd7fd39c:306:870020)
    at ua (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1772874)
    at Es (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1818137)
    at ml (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1803713)
    at hl (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1803638)
    at il (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1800966)
    at https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1759149
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1834485)
    at qo (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1758858)
    at $o (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1759094)
    at Yo (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1759029)
    at el (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1797752)
    at Sa (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1776547)
    at https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1050313
    at https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1050996
    at https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1172448
    at m.flush (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1175277)
    at p.flush (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1171502)
    at Object.cb (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1060110)
    at e.emit (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1053753)
    at dashboard.getTeams (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1062743)
    at Proxy.<anonymous> (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1061785)
    at https://codesandbox.io/static/js/app.22c21a658.js?_sw-precache=15dda38ef6014080001dd838cd7fd39c:306:445978
    at l (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255733)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255486)
    at Generator.forEach.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:256090)
    at t (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2405)
    at i (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2616)
    at https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2675
    at new Promise (<anonymous>)
    at https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2556
    at https://codesandbox.io/static/js/app.22c21a658.js?_sw-precache=15dda38ef6014080001dd838cd7fd39c:306:446472
    at internal.initializeNewUser (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1062675)
    at Proxy.<anonymous> (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1061785)
    at https://codesandbox.io/static/js/app.22c21a658.js?_sw-precache=15dda38ef6014080001dd838cd7fd39c:306:446901
    at l (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255733)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255486)
    at Generator.forEach.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:256090)
    at t (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2405)
    at i (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2616)
  
    in Wn
    in div
    in Actions___StyledStack
    in xr
    in header
    in Header___StyledStack
    in Oa
    in je
    in Unknown
    in div
    in elements__Container
    in je
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

**Comment by Cvan23** [comment]
Trying to sign in to Codesandbox w/my Github account
