### ISSUE TITLE
Static template made boom boom.

### ISSUE THREAD

**Issue by RWOverdijk** [codesandbox/codesandbox-client#4829]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

I just made a new static sandbox.

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 84.0.4147 | OS X 10.15.6           | 595c543c5          |

  **Route:**
  https://codesandbox.io/s/mutable-meadow-xznol

  **Error Code:**
b22fdc7c1f7c47d6ae04a65a5de7deda

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'teamId' of undefined
  TypeError: Cannot read property 'teamId' of undefined
    at zn (https://codesandbox.io/static/js/app.8aae43b33.js?_sw-precache=75577b8b634c9fa1c9cecebc0281db25:306:868788)
    at ua (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1772874)
    at Es (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1818137)
    at ml (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1803713)
    at hl (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1803638)
    at il (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1800966)
    at https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1759149
    at https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1834485
    at qo (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1758858)
    at $o (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1759094)
    at Yo (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1759029)
    at el (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1797752)
    at Sa (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1776547)
    at https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1050313
    at https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1050996
    at https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1172448
    at m.flush (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1175277)
    at p.flush (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1171502)
    at Object.cb (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1060110)
    at e.emit (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1053753)
    at workspace.openDefaultItem (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1062743)
    at Proxy.<anonymous> (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1061785)
    at https://codesandbox.io/static/js/app.8aae43b33.js?_sw-precache=75577b8b634c9fa1c9cecebc0281db25:306:451520
    at l (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255733)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255486)
    at Generator.forEach.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:256090)
    at t (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2405)
    at i (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2616)
    at https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2675
    at new Promise (<anonymous>)
    at https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2556
    at https://codesandbox.io/static/js/app.8aae43b33.js?_sw-precache=75577b8b634c9fa1c9cecebc0281db25:306:451674
    at internal.setCurrentSandbox (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1062675)
    at Proxy.<anonymous> (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1061785)
    at https://codesandbox.io/static/js/app.8aae43b33.js?_sw-precache=75577b8b634c9fa1c9cecebc0281db25:306:608649
    at l (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255733)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255486)
    at Generator.forEach.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:256090)
    at t (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2405)
    at i (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2616)
  
    in zn
    in div
    in ForwardRef
    in div
    in ForwardRef
    in Unknown
    in ForwardRef
    in ForwardRef
    in ForwardRef
    in Styled(styled.div)
    in Unknown
    in ForkButton___StyledMenuList
    in d
    in Unknown
    in styled.div
    in h
    in div
    in Styled(styled.div)
    in qn
    in div
    in Actions___StyledStack
    in Er
    in header
    in Header___StyledStack
    in Ia
    in je
    in Unknown
    in div
    in elements__Container
    in je
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

**Comment by SaraVieira** [comment]
Closed by #4830
