### ISSUE TITLE
Proyecto PPI

### ISSUE THREAD

**Issue by Brayan-HG** [codesandbox/codesandbox-client#4882]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 85.0.4183 | Windows 10           | f3feeea3e          |

  **Route:**
  https://codesandbox.io/s/weathered-leaf-lv0im

  **Error Code:**
66fd82d87cc04210886ad474481ac3f0

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ys (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1793951)
    at yl (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1812953)
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1834485)
    at qo (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1758858)
    at bl (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1810838)
    at il (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1801165)
    at https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1759149
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1834485)
    at qo (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1758858)
    at $o (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1759094)
  
    in Ua
    in Unknown
    in Styled(Component)
    in nav
    in elements__Container
    in Ga
    in je
    in Unknown
    in div
    in styled.div
    in div
    in elements__Container
    in je
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

**Comment by SaraVieira** [comment]
Hey!

Can you please explain what you were doing when this crash happened?

**Comment by SaraVieira** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
