### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ajkhedkar15** [codesandbox/codesandbox-client#4981]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 74.0.3729 | Windows 10           | 9fac3efb4          |

  **Route:**
  https://codesandbox.io/s/keeper-app-part-1-starting-forked-9278u?file=/src/index.js

  **Error Code:**
b5e3195ca30d493898a6fb17020e4603

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot convert undefined or null to object
  TypeError: Cannot convert undefined or null to object
    at https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:168325
    at https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1702843
    at Es (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1818522)
    at ml (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1800782)
    at hl (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1800707)
    at il (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1798035)
    at https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1756218
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1831554)
    at qo (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1755927)
    at Xo (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1756163)
    at Yo (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1756098)
    at el (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1794821)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1760922)
    at t._.setState (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:2065440)
    at https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1909449
    at r (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:903470)
    at https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:903700
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:903670)
    at k (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:904892)
    at https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:906277
    at Object.confirmTransitionTo (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:903409)
    at Object.replace (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:906061)
    at e.value (https://codesandbox.io/static/js/app.3805583d2.js:272:518191)
    at https://codesandbox.io/static/js/app.3805583d2.js:272:618759
    at b (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:976717)
    at C (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:976992)
    at w (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:976882)
    at r (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:166715)
  
    in DropTarget(Component)
    in div
    in elements__Tabs
    in div
    in elements__Container
    in Yt
    in div
    in elements__Header
    in div
    in elements__Container
    in n
    in div
    in div
    in t
    in div
    in t
    in div
    in De
    in Fe
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in De
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by sannek** [comment]
Hi, 
Thanks for your report. I can't see anything wrong with the sandbox you linked. Do you have some more information about exactly what was going on when it crashed? Or a sandbox link that is still broken (if you fixed this one in the mean time).
Thanks!
