### ISSUE TITLE
Crash when typing code into the editor

### ISSUE THREAD

**Issue by thomasmery** [codesandbox/codesandbox-client#5017]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

I created a simple react sandbox and was adding code into a useEffect hook I had created

it probably is not related to the specific code I was typing as this has happened several times before on other sandboxes

it is all I can report for now

thanks

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 81.0.4044 | OS X 10.15.2           | 356ff723c          |

  **Route:**
  https://codesandbox.io/s/stoic-feather-yb70d?file=/src/App.js

  **Error Code:**
0b69431d38884f53a4790b03bc4ca83b

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot convert undefined or null to object
  TypeError: Cannot convert undefined or null to object
    at https://codesandbox.io/static/js/common.788940570.chunk.js:1:191879
    at https://codesandbox.io/static/js/common.788940570.chunk.js:1:1709936
    at xs (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1825615)
    at ml (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1807875)
    at hl (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1807800)
    at il (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1805128)
    at https://codesandbox.io/static/js/common.788940570.chunk.js:1:1763311
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1838647)
    at qo (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1763020)
    at Xo (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1763256)
    at Yo (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1763191)
    at el (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1801914)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1768015)
    at t._.setState (https://codesandbox.io/static/js/common.788940570.chunk.js:1:2021667)
    at https://codesandbox.io/static/js/common.788940570.chunk.js:1:1865676
    at r (https://codesandbox.io/static/js/common.788940570.chunk.js:1:910243)
    at https://codesandbox.io/static/js/common.788940570.chunk.js:1:910473
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (https://codesandbox.io/static/js/common.788940570.chunk.js:1:910443)
    at k (https://codesandbox.io/static/js/common.788940570.chunk.js:1:911665)
    at https://codesandbox.io/static/js/common.788940570.chunk.js:1:911928
    at Object.confirmTransitionTo (https://codesandbox.io/static/js/common.788940570.chunk.js:1:910182)
    at T (https://codesandbox.io/static/js/common.788940570.chunk.js:1:911883)
    at S (https://codesandbox.io/static/js/common.788940570.chunk.js:1:911802)
  
    in DropTarget(Component)
    in div
    in elements__Tabs
    in div
    in elements__Container
    in Yt
    in div
    in elements__Header
    in div
    in elements__Container
    in n
    in div
    in div
    in t
    in div
    in t
    in div
    in De
    in Fe
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in De
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by lbogdan** [comment]
Hey @thomasmery ,

Thank you for your report! We've been chasing this bug for a while, but haven't been able to consistently replicate it so far. 😕 Just to be sure we got this right, the crash suddenly happened while you were typing inside an open file in the editor?

**Comment by thomasmery** [comment]
Hi there,

that's right

a basic App.js from the react template

thanks !

**Comment by christianalfoni** [comment]
Hi @thomasmery ,

Are you able to replicate the issue? It would be great with some reproducible steps. Or if you can remember if you did something out of the ordinary before you started writing code 😄

**Comment by thomasmery** [comment]
Hi

I'm afraid I had not time to retry

FWIW everytime it crashed I was just using the editor, different cases each
time

sorry I can't help more right now

**Comment by SaraVieira** [comment]
keeping track in #5406
