### ISSUE TITLE
Codesandbox ekip proje bağlantı problemi 

### ISSUE THREAD

**Issue by kadirselcuk** [codesandbox/codesandbox-client#5068]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 86.0.4240 | Android 10           | 5f4aecf6f          |

  **Route:**
  https://codesandbox.io/signin/eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJDb2RlU2FuZGJveCIsImV4cCI6MTYwNjU5MDY5MCwiaWF0IjoxNjAzOTk4NjkwLCJpc3MiOiJDb2RlU2FuZGJveCIsImp0aSI6IjVjNWFiOWZjLTU4ZTAtNGFjOS05Zjk5LTAwYTc3NDJiMDQyMyIsIm5iZiI6MTYwMzk5ODY4OSwic3ViIjoiVXNlcjo0ZTFmOWM3NS0wNGNiLTQ2YWYtYTk1NC03ZmY2MTVjYWViZDUiLCJ0eXAiOiJhY2Nlc3MifQ.nkCATwB2obNFHA8wLKTWq2wqEGNl59_zjAVmYAsnR29BFAE5bILU0-lkkwcTozYaEXU1oNN28u6obVbnN3rmOg

  **Error Code:**
abb1a34211b74224a127cad0b82220d7

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  SecurityError: Blocked a frame with origin "https://codesandbox.io" from accessing a cross-origin frame.
  Error: Blocked a frame with origin "https://codesandbox.io" from accessing a cross-origin frame.
    at new n (https://codesandbox.io/static/js/page-sign-in.246da4d89.chunk.js:1:8570)
    at ki (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1768733)
    at Ya (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1785616)
    at xs (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1823571)
    at ml (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1807875)
    at hl (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1807800)
    at il (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1805128)
    at https://codesandbox.io/static/js/common.788940570.chunk.js:1:1763311
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1838647)
    at qo (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1763020)
    at Xo (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1763256)
    at Yo (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1763191)
    at el (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1801914)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1768015)
    at r._.setState (https://codesandbox.io/static/js/common.788940570.chunk.js:1:2021667)
    at https://codesandbox.io/static/js/default~app~embed.aa719343a.chunk.js?_sw-precache=b2b52fc61559a597c56c6d0231b2b2c1:482:141726
  
    in n
    in r
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by sannek** [comment]
Thanks for your report. Could you let me know if this happened only once, or if it happens often when you try to sign in?

**Comment by kadirselcuk** [comment]
@Sannek Hi, thank you for your interest and I think i repeated several times but it was not a big problem

**Comment by SaraVieira** [comment]
Hey!

Did this happen when you were trying to sign in to codesanbox in another website?
