### ISSUE TITLE
someone can help me? i cant write, or erase anything in codesandboxes, i think i toch something in my keyboard and now i can't do anything:( just appear one rectangle white

### ISSUE THREAD

**Issue by ADRIANACERON18** [codesandbox/codesandbox-client#5134]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 86.0.4240 | Windows 10           | 4b3fc182f          |

  **Route:**
  https://codesandbox.io/s/tender-tesla-w8ofz?file=/package.json:150-152

  **Error Code:**
0ddbf2ffd4d24624b2539eb8443df8f6

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ys (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1798113)
    at ms (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1796114)
    at ys (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1797850)
    at yl (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1817115)
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1838647)
    at qo (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1763020)
    at bl (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1815000)
    at il (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1805327)
    at https://codesandbox.io/static/js/common.788940570.chunk.js:1:1763311
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1838647)
    at qo (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1763020)
    at Xo (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1763256)
    at Yo (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1763191)
    at se (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1832399)
    at Sn (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1746817)
  
    in hd
    in div
    in De
    in Unknown
    in div
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in De
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by SaraVieira** [comment]
Hey

Can you please try to clear the cache and local storage like so:

![CleanShot 2020-11-16 at 18 52 45](https://user-images.githubusercontent.com/1051509/99289356-1a0b5b00-283d-11eb-904f-01ebed33485a.png)
![CleanShot 2020-11-16 at 18 52 57](https://user-images.githubusercontent.com/1051509/99289358-1bd51e80-283d-11eb-8c5e-f9fd28329682.png)

You will then need to log in again since this will clear everything.

Let me know if it all goes back to normal

**Comment by SaraVieira** [comment]
Hey!

Can you please let me know if you have any translation extension in Chrome?
