### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by lc5562010** [codesandbox/codesandbox-client#5243]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 89.0.4343 | OS X 10.14.6           | c937e63ed          |

  **Route:**
  https://codesandbox.io/dashboard/all/demo?workspace=8d6493ca-99d6-447d-9b9e-fa122b9c4f0d

  **Error Code:**
390d46fdc1fa4c34ac163e0884a92ee9

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at HTMLDivElement.removeChild (<anonymous>)
    at ys (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1798131)
    at yl (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1817115)
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1838647)
    at qo (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1763020)
    at bl (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1815000)
    at il (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1805327)
    at https://codesandbox.io/static/js/common.788940570.chunk.js:1:1763311
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1838647)
    at qo (https://codesandbox.io/static/js/common.788940570.chunk.js:1:1763020)
  
    in div
    in elements__CenteredMessage
    in Qe
    in div
    in span
    in styled.span
    in span
    in styled.span
    in div
    in n
    in Styled(n)
    in Unknown
    in ut
    in div
    in ForwardRef(p)
    in ForwardRef(p)
    in elements__TabContent
    in div
    in elements__Container
    in De
    in Unknown
    in lr
    in div
    in div
    in div
    in div
    in t
    in t
    in Modal___StyledModal
    in n
    in De
    in Unknown
    in Z
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by SaraVieira** [comment]
Hey!

Can you please let me know if you have any translation extension in Chrome?
