### ISSUE TITLE
error

### ISSUE THREAD

**Issue by carlosgaleano** [codesandbox/codesandbox-client#5348]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 87.0.4280 | Windows 10           | e1a24a434          |

  **Route:**
  https://codesandbox.io/s

  **Error Code:**
dae7b13cfe0f442aa81d0c410485ac96

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ys (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1801945)
    at yl (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1820929)
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1842461)
    at qo (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1766834)
    at bl (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1818814)
    at il (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1809141)
    at https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1767125
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1842461)
    at qo (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1766834)
    at Xo (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1767070)
    at Yo (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1767005)
    at el (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1805728)
    at Sa (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1784523)
    at https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:966749
    at https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:967432
    at e.callback (https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:1095677)
    at m.flush (https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:1098506)
    at p.flush (https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:1094731)
    at Object.cb (https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:977408)
    at e.emit (https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:416577)
    at setLoadingAuth (https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:980107)
    at https://codesandbox.io/static/js/app.2cceb40e9.js:266:1355525
    at l (https://codesandbox.io/static/js/common-sandbox.71780db40.chunk.js:1:257407)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.71780db40.chunk.js:1:257160)
    at Generator.forEach.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.71780db40.chunk.js:1:257764)
    at t (https://codesandbox.io/static/js/common-sandbox.71780db40.chunk.js:1:2405)
    at i (https://codesandbox.io/static/js/common-sandbox.71780db40.chunk.js:1:2616)
  
    in div
    in elements__Folder
    in div
    in Styled(styled.div)
    in div
    in elements__Main
    in xo
    in header
    in Header___StyledStack
    in Go
    in De
    in Unknown
    in div
    in elements__Container
    in De
    in Unknown
    in Unknown
    in Unknown
    in component
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by SaraVieira** [comment]
Hey!


Can you tell me what you were doing when the crash happened? Also where you using a translator?

**Comment by SaraVieira** [comment]
Nevermind, found it! Thank you for creating the report!
