### ISSUE TITLE
Crash when making comment

### ISSUE THREAD

**Issue by Michiel87** [codesandbox/codesandbox-client#5356]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Making a comment in Pro workspaces
  > When you click on comment label in the gutter and you click it again before writing the comment, the screen crashes!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 87.0.4280 | Windows 10           | 4f5e90920          |

  **Route:**
  https://codesandbox.io/s/gallant-cray-qd6jp?file=/src/App.tsx

  **Error Code:**
d93059c8e2304f879be3702c8a4601fc

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'id' of undefined
  TypeError: Cannot read property 'id' of undefined
    at https://codesandbox.io/static/js/app.2cceb40e9.js?_sw-precache=746766ba6b22700516339d08349e1f66:266:1307500
    at Array.map (<anonymous>)
    at Sb (https://codesandbox.io/static/js/app.2cceb40e9.js?_sw-precache=746766ba6b22700516339d08349e1f66:266:1307433)
    at ua (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1780850)
    at xs (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1826113)
    at ml (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1811689)
    at hl (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1811614)
    at il (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1808942)
    at https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1767125
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1842461)
    at qo (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1766834)
    at Xo (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1767070)
    at Yo (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1767005)
    at el (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1805728)
    at Sa (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1784523)
    at https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:966749
    at https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:967432
    at e.callback (https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:1095677)
    at m.flush (https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:1098506)
    at p.flush (https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:1094731)
    at Object.cb (https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:977408)
    at e.emit (https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:416577)
    at comments.onCommentClick (https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:980107)
    at Object.onCommentClick (https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:979101)
    at https://codesandbox.io/static/js/app.2cceb40e9.js?_sw-precache=746766ba6b22700516339d08349e1f66:266:484440
  
    in Sb
    in Sv
    in De
    in Unknown
    in De
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by SaraVieira** [comment]
Hey

Sorry about the issue, just made a PR that should prevent this
