### ISSUE TITLE
html 

### ISSUE THREAD

**Issue by Deborah1464** [codesandbox/codesandbox-client#5391]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 87.0.4280 | Windows Server 2008 R2 / 7           | 6a844e4f7          |

  **Route:**
  https://codesandbox.io/dashboard/home?workspace=03bf51f6-d007-4091-82cb-570cbbd8af60

  **Error Code:**
bbf656e8090e478fbdb5d268fee25937

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ys (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1801927)
    at ms (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1799928)
    at ys (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1801664)
    at yl (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1820929)
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1842461)
    at qo (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1766834)
    at bl (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1818814)
    at il (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1809141)
    at https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1767125
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1842461)
    at qo (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1766834)
    at Xo (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1767070)
    at Yo (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1767005)
    at se (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1836213)
    at Sn (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1750631)
  
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by SaraVieira** [comment]
Hey!

Consegues me dizer o que estavas a fazer na altura em que quebrou? E se estavas a usar alguma extensão de tradução? 

Temos tido estes problema com Google translate mas é difícil de encontrar 😭

**Comment by SaraVieira** [comment]
Also, sorry, em Portugal não usamos você, tudo é tu 😂
