### ISSUE TITLE
I was just writing code

### ISSUE THREAD

**Issue by jemajoo** [codesandbox/codesandbox-client#5420]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 74.0.3729 | Windows Server 2008 R2 / 7           | f8ede25e2          |

  **Route:**
  https://codesandbox.io/s/html-code-editor-forked-s728v?file=/index.html

  **Error Code:**
d5b9af5327de47b4928ac82c552f5d91

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot convert undefined or null to object
  TypeError: Cannot convert undefined or null to object
    at https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:195472
    at https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1713750
    at xs (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1829429)
    at ml (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1811689)
    at hl (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1811614)
    at il (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1808942)
    at https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1767125
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1842461)
    at qo (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1766834)
    at Xo (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1767070)
    at Yo (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1767005)
    at el (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1805728)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1771829)
    at t._.setState (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:2025481)
    at https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1869490
    at r (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:913867)
    at https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:914097
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:914067)
    at k (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:915289)
    at https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:916674
    at Object.confirmTransitionTo (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:913806)
    at Object.replace (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:916458)
    at e.value (https://codesandbox.io/static/js/app.f83c4b426.js:266:593315)
    at https://codesandbox.io/static/js/app.f83c4b426.js:266:714428
    at b (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:987434)
    at C (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:987709)
    at w (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:987599)
    at r (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:193862)
  
    in DropTarget(Component)
    in div
    in elements__Tabs
    in div
    in elements__Container
    in Zt
    in div
    in elements__Header
    in div
    in elements__Container
    in n
    in div
    in div
    in t
    in div
    in t
    in div
    in De
    in Wt
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in De
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by SaraVieira** [comment]
Sorry for your issue, we are tracking and trying to figure out why this is happening here https://github.com/codesandbox/codesandbox-client/issues/5406
