### ISSUE TITLE
Web Crashed after uploaded a pdf file to React Create App  public folder

### ISSUE THREAD

**Issue by noberk** [codesandbox/codesandbox-client#5438]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 88.0.4324 | Windows 10           | cacc11a40          |

  **Route:**
  https://codesandbox.io/s/thirsty-mountain-4imsj?file=/src/App.tsx

  **Error Code:**
b271518b246d4800ba69d733ad77176e

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'branch' of null
  TypeError: Cannot read property 'branch' of null
    at Component (https://codesandbox.io/static/js/app.4f6798100.js:266:228510)
    at ua (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1780850)
    at xs (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1826113)
    at ml (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1811689)
    at hl (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1811614)
    at il (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1808942)
    at https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1767125
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1842461)
    at qo (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1766834)
    at Xo (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1767070)
    at Yo (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1767005)
    at el (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1805728)
    at Sa (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js:1:1784523)
    at https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:966749
    at https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:967432
    at e.callback (https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:1095677)
    at m.flush (https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:1098506)
    at p.flush (https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:1094731)
    at Object.cb (https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:977408)
    at e.emit (https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:416577)
    at git._setGitChanges (https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:980107)
    at Proxy.<anonymous> (https://codesandbox.io/static/js/vendors~app.320556d3a.chunk.js:1:979101)
    at https://codesandbox.io/static/js/app.4f6798100.js:266:784619
    at l (https://codesandbox.io/static/js/common-sandbox.71780db40.chunk.js:1:257407)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.71780db40.chunk.js:1:257160)
    at Generator.forEach.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.71780db40.chunk.js:1:257764)
    at t (https://codesandbox.io/static/js/common-sandbox.71780db40.chunk.js:1:2405)
    at i (https://codesandbox.io/static/js/common-sandbox.71780db40.chunk.js:1:2616)
  
    in Component
    in div
    in div
    in div
    in div
    in t
    in t
    in Modal___StyledModal
    in n
    in De
    in Unknown
    in Ks
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by noberk** [comment]
![image](https://user-images.githubusercontent.com/26300918/106617266-69923500-65a9-11eb-8eb4-591461441cc2.png)

**Comment by SaraVieira** [comment]
That was the cause if a PR I made, reverted the PR :)

**Comment by noberk** [comment]
> That was the cause if a PR I made, reverted the PR :)

what cause this happen😿
