### ISSUE TITLE
毎回クラッシュする

### ISSUE THREAD

**Issue by 1018masatosi** [codesandbox/codesandbox-client#5559]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 88.0.4324 | OS X 11.2.2           | 00bf9fad7          |

  **Route:**
  https://codesandbox.io/dashboard/home?workspace=9d1f283a-fb29-42a8-b61d-7bc0b92a545c

  **Error Code:**
dddfb23096634647a7fe4e0cff8f1d25

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'type' of undefined
  TypeError: Cannot read property 'type' of undefined
    at https://codesandbox.io/static/js/app.e812aec58.js:266:274453
    at Array.filter (<anonymous>)
    at Zd (https://codesandbox.io/static/js/app.e812aec58.js:266:274414)
    at ua (https://codesandbox.io/static/js/common.b65abcb54.chunk.js:1:1780850)
    at xs (https://codesandbox.io/static/js/common.b65abcb54.chunk.js:1:1826113)
    at ml (https://codesandbox.io/static/js/common.b65abcb54.chunk.js:1:1811689)
    at hl (https://codesandbox.io/static/js/common.b65abcb54.chunk.js:1:1811614)
    at il (https://codesandbox.io/static/js/common.b65abcb54.chunk.js:1:1808942)
    at https://codesandbox.io/static/js/common.b65abcb54.chunk.js:1:1767125
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.b65abcb54.chunk.js:1:1842461)
    at qo (https://codesandbox.io/static/js/common.b65abcb54.chunk.js:1:1766834)
    at Xo (https://codesandbox.io/static/js/common.b65abcb54.chunk.js:1:1767070)
    at Yo (https://codesandbox.io/static/js/common.b65abcb54.chunk.js:1:1767005)
    at se (https://codesandbox.io/static/js/common.b65abcb54.chunk.js:1:1836213)
    at Sn (https://codesandbox.io/static/js/common.b65abcb54.chunk.js:1:1750631)
  
    in Zd
    in nm
    in um
    in Zf
    in t
    in t
    in div
    in Content___StyledElement
    in Unknown
    in withRouter()
    in main
    in Dashboard___StyledElement2
    in div
    in Dashboard___StyledStack2
    in div
    in Dashboard___StyledStack
    in Unknown
    in De
    in Unknown
    in qv
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by fuchao2012** [comment]
https://translate.google.com/?sl=ja&tl=en&text=毎回クラッシュする&op=translate

means: `crash every time`

**Comment by lbogdan** [comment]
`item` can be `undefined` here:

https://github.com/codesandbox/codesandbox-client/blob/00bf9fad79788ea917edb1f70c6e0a55ad7e4691/packages/app/src/app/pages/Dashboard/Components/Selection/ContextMenus/MultiItemMenu.tsx#L48-L56
