### ISSUE TITLE
unknown

### ISSUE THREAD

**Issue by derekseabrooke** [codesandbox/codesandbox-client#5721]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 90.0.4430 | Windows 10           | de3b2cd32          |

  **Route:**
  https://codesandbox.io/s/agitated-solomon-w40re?file=/src/components/jsonviewer.vue

  **Error Code:**
a12a43ce4a374220a3b2011b83ef0999

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  RangeError: Maximum call stack size exceeded
  RangeError: Maximum call stack size exceeded
    at https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:951946
    at P (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:2027791)
    at e (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:2027105)
    at I (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:2027570)
    at Object.forEach (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:2028448)
    at e (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:951875)
    at t.render (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:952214)
    at Xa (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1792531)
    at Ya (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1792324)
    at xs (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1827625)
    at ml (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1811929)
    at hl (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1811854)
    at il (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1809182)
    at https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1767365
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1842701)
    at qo (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1767074)
    at Xo (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1767310)
    at Yo (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1767245)
    at el (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1805968)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1772069)
    at n._.setState (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:2025721)
    at n.value (https://codesandbox.io/static/js/default~app~embed.785ff4e5a.chunk.js:499:33043)
    at Object.<anonymous> (https://codesandbox.io/static/js/default~app~embed.785ff4e5a.chunk.js:499:31463)
    at https://codesandbox.io/static/js/default~app~embed~sandbox.c007aaee8.chunk.js:1:6948
    at Array.forEach (<anonymous>)
    at R (https://codesandbox.io/static/js/default~app~embed~sandbox.c007aaee8.chunk.js:1:6911)
    at U (https://codesandbox.io/static/js/default~app~embed~sandbox.c007aaee8.chunk.js:1:7120)
  
    in t
    in div
    in Styled(div)
    in t
    in WithTheme(t)
    in div
    in Styled(div)
    in div
    in Styled(div)
    in v
    in t
    in div
    in Styled(div)
    in v
    in t
    in div
    in elements__Messages
    in div
    in elements__Container
    in n
    in WithTheme(n)
    in div
    in elements__ContentContainer
    in div
    in elements__Container
    in n
    in div
    in div
    in t
    in div
    in t
    in div
    in De
    in Wt
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in De
    in dC
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by sbinlondon** [comment]
Hi there @derekseabrooke can you please fill out the **"What were you trying to accomplish when the crash occurred?"** part of the template? It helps us to have as much information as possible about what you were doing leading up to the crash. Right now, opening the sandbox looks fine to me and I can't reproduce.

**Comment by derekseabrooke** [comment]
Did you keep a snapshot of the sandbox at the time of the crash?  It’s completely different now.  I don’t remember what I was doing.  I won’t bother reporting it in the future.

Sent from Mail for Windows 10
