### ISSUE TITLE
my sandBox crashing 

### ISSUE THREAD

**Issue by Nauman-cloud** [codesandbox/codesandbox-client#5754]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 90.0.4430 | Linux x86_64           | cb021378d          |

  **Route:**
  https://codesandbox.io/dashboard/home?workspace=d1599b1c-ad8f-45f2-aade-e59a13f70cd0

  **Error Code:**
b19e38f1515d4cfe8730819513ff4f5b

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'avatarUrl' of null
  TypeError: Cannot read property 'avatarUrl' of null
    at https://codesandbox.io/static/js/app.6361209bd.js?_sw-precache=7b20a32d2548be644660cf4cfeb07293:266:73218
    at ua (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1781090)
    at Ka (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1789355)
    at qa (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1789174)
    at Va (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1788893)
    at xs (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1829784)
    at ml (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1811929)
    at hl (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1811854)
    at il (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1809182)
    at https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1767365
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1842701)
    at qo (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1767074)
    at Xo (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1767310)
    at Yo (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1767245)
    at Cl (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1824553)
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1842701)
    at qo (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1767074)
    at wl (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1824204)
    at https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1824115
    at z (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1842082)
    at MessagePort.A.port1.onmessage (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1840826)
  
    in Unknown
    in li
    in Sidebar___StyledListItem
    in ul
    in Styled(styled.div)
    in aside
    in ForwardRef
    in Sidebar___StyledStack
    in Tu
    in div
    in Dashboard___StyledElement
    in t
    in div
    in Dashboard___StyledStack2
    in div
    in Dashboard___StyledStack
    in Unknown
    in De
    in Unknown
    in ly
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by DeMoorJasper** [comment]
Thanks for reporting, #5754 should resolve this issue
