### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by DevCleverton** [codesandbox/codesandbox-client#5825]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 74.0.3729 | Windows 10           | 72d987691          |

  **Route:**
  https://codesandbox.io/s/magical-faraday-n93lz

  

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'parsed' of undefined
  TypeError: Cannot read property 'parsed' of undefined
    at l.getEntries (https://codesandbox.io/static/js/default~app~embed~sandbox.993e26d54.chunk.js:1:22608)
    at je (https://codesandbox.io/static/js/app.f69cc7b3e.js:266:591398)
    at a.cb (https://codesandbox.io/static/js/app.f69cc7b3e.js:266:827121)
    at a.runScope (https://codesandbox.io/static/js/vendors~app.597f527d1.chunk.js:1:1041354)
    at a.evaluate (https://codesandbox.io/static/js/vendors~app.597f527d1.chunk.js:1:1041792)
    at Object.onGetFunction (https://codesandbox.io/static/js/vendors~app.597f527d1.chunk.js:1:1031360)
    at Object.get (https://codesandbox.io/static/js/vendors~app.597f527d1.chunk.js:1:1155064)
    at https://codesandbox.io/static/js/app.f69cc7b3e.js:266:1305149
    at ua (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1781090)
    at Ka (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1789355)
  
    in Unknown
    in div
    in mm
    in div
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in mm
    in div
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in Styled(styled.div)
    in section
    in Styled(styled.div)
    in Unknown
    in Files___StyledCollapsible
    in Mm
    in Pm
    in div
    in De
    in Unknown
    in div
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in De
    in yC
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by lbogdan** [comment]
Hey @DevCleverton ,

Thanks for your report, can you please give us a bit more details about what you were doing when the crash happened?

**Comment by lbogdan** [comment]
`configurationFiles.package` can be `undefined` here:

https://github.com/codesandbox/codesandbox-client/blob/72d9876913c4c6e6f03c38e0e0a7b7efe40fbce6/packages/common/src/templates/angular.ts#L85-L88
