### ISSUE TITLE
Folder crashed

### ISSUE THREAD

**Issue by tanishraj** [codesandbox/codesandbox-client#5870]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 91.0.4472 | OS X 10.15.7           | 013bf2f0b          |

  **Route:**
  https://codesandbox.io/dashboard/all/Data%20Structure/10%20-%20100%%20Optional%20Challenge?workspace=f33fa2d9-de9e-427f-bb77-16660fca2f14

  

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  URIError: URI malformed
  URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at V (https://codesandbox.io/static/js/app.0617e6b8a.js?_sw-precache=557263e5cac2cfa642b0f9dad6c5b9d2:266:82929)
    at W (https://codesandbox.io/static/js/app.0617e6b8a.js?_sw-precache=557263e5cac2cfa642b0f9dad6c5b9d2:266:83122)
    at ua (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1781090)
    at Ka (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1789355)
    at xs (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1827543)
    at ml (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1811929)
    at hl (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1811854)
    at il (https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1809182)
    at https://codesandbox.io/static/js/common.06f11edc9.chunk.js:1:1767365
  
    in W
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by DeMoorJasper** [comment]
Hey, Could you share some more detailed steps to reproduce this?
