### ISSUE TITLE
Crash during in deleting multiple items

### ISSUE THREAD

**Issue by dimitriiy** [codesandbox/codesandbox-client#5892]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 91.0.4472 | Windows 10           | a566285e0          |

  **Route:**
  https://codesandbox.io/dashboard/drafts?workspace=72f0263f-d74d-4b4a-bcf4-24748f8b2e08

  **Error Code:**
2676e6c1027348579973dbb6254010a7

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'type' of undefined
  TypeError: Cannot read property 'type' of undefined
    at https://codesandbox.io/static/js/app.2d91d8855.js:266:281499
    at Array.filter (<anonymous>)
    at _m (https://codesandbox.io/static/js/app.2d91d8855.js:266:281460)
    at ua (https://codesandbox.io/static/js/common.06f11edc9.chunk.js?_sw-precache=07cdd3d049c0272c26234d6e31131d5e:1:1781090)
    at xs (https://codesandbox.io/static/js/common.06f11edc9.chunk.js?_sw-precache=07cdd3d049c0272c26234d6e31131d5e:1:1826353)
    at ml (https://codesandbox.io/static/js/common.06f11edc9.chunk.js?_sw-precache=07cdd3d049c0272c26234d6e31131d5e:1:1811929)
    at hl (https://codesandbox.io/static/js/common.06f11edc9.chunk.js?_sw-precache=07cdd3d049c0272c26234d6e31131d5e:1:1811854)
    at il (https://codesandbox.io/static/js/common.06f11edc9.chunk.js?_sw-precache=07cdd3d049c0272c26234d6e31131d5e:1:1809182)
    at https://codesandbox.io/static/js/common.06f11edc9.chunk.js?_sw-precache=07cdd3d049c0272c26234d6e31131d5e:1:1767365
    at https://codesandbox.io/static/js/common.06f11edc9.chunk.js?_sw-precache=07cdd3d049c0272c26234d6e31131d5e:1:1842701
    at qo (https://codesandbox.io/static/js/common.06f11edc9.chunk.js?_sw-precache=07cdd3d049c0272c26234d6e31131d5e:1:1767074)
    at Xo (https://codesandbox.io/static/js/common.06f11edc9.chunk.js?_sw-precache=07cdd3d049c0272c26234d6e31131d5e:1:1767310)
    at Yo (https://codesandbox.io/static/js/common.06f11edc9.chunk.js?_sw-precache=07cdd3d049c0272c26234d6e31131d5e:1:1767245)
    at se (https://codesandbox.io/static/js/common.06f11edc9.chunk.js?_sw-precache=07cdd3d049c0272c26234d6e31131d5e:1:1836453)
    at Sn (https://codesandbox.io/static/js/common.06f11edc9.chunk.js?_sw-precache=07cdd3d049c0272c26234d6e31131d5e:1:1750871)
  
    in _m
    in Bm
    in Wm
    in pb
    in t
    in t
    in div
    in Content___StyledElement
    in Unknown
    in withRouter()
    in main
    in Dashboard___StyledElement2
    in div
    in Dashboard___StyledStack2
    in div
    in Dashboard___StyledStack
    in Unknown
    in De
    in Unknown
    in wy
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by dimitriiy** [comment]
Also I used Shift and Ctrl for filtering items.

**Comment by alexnm** [comment]
Hey @dimitriiy does this happen consistently? Can you please provide a couple of more details if you can find a consistent reproducible scenario? are you deleting sandboxes and/or folders?

**Comment by dimitriiy** [comment]
First, I selected several sandboxes and deleted them. After that I also selected several sandboxes using Shift, and pressing Ctrl clicked the selected sandboxes;
[https://www.youtube.com/watch?v=DCsMKoxaiT0&ab_channel=Dimedrol](url)

**Comment by dimitriiy** [comment]
Hope this helps you!

**Comment by alexnm** [comment]
thanks! I'm still not able to reproduce this, but will try again tomorrow morning.
