### ISSUE TITLE
Cannot update to Angular 12

### ISSUE THREAD

**Issue by MurhafSousli** [codesandbox/codesandbox-client#5995]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

The sandbox is outdated when you choose the Angular template :(

I was trying to update it to Angular 12, once I rename the file .angular-cli.json to `angular.json` it crashed and now I cannot open the project anymore, I have been adding writing code for 20 minutes and I did save all the changes but it is all gone now.

  <details>
  <summary>Angular</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 92.0.4515 | OS X 10.15.7           | 8dea6dedb          |

  **Route:**
  https://codesandbox.io/s/wizardly-johnson-nv12o

  **Error Code:**
ec1b7e505bd54505864b2afeb126f86f

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'undefined' of undefined
  TypeError: Cannot read property 'undefined' of undefined
    at https://codesandbox.io/static/js/default~app~embed~sandbox.f4dc4c632.chunk.js?_sw-precache=679ecbb1a54a4f1364b495c6392d2b12:1:22460
    at l.getEntries (https://codesandbox.io/static/js/default~app~embed~sandbox.f4dc4c632.chunk.js?_sw-precache=679ecbb1a54a4f1364b495c6392d2b12:1:22586)
    at je (https://codesandbox.io/static/js/app.4be7dfb72.js?_sw-precache=999090deb8e469821cd87358d819f159:266:607644)
    at a.cb (https://codesandbox.io/static/js/app.4be7dfb72.js?_sw-precache=999090deb8e469821cd87358d819f159:266:842899)
    at a.runScope (https://codesandbox.io/static/js/vendors~app.5dda64d70.chunk.js?_sw-precache=afcf49cd5c60bfbbd51535036a2cc734:1:1039644)
    at a.evaluate (https://codesandbox.io/static/js/vendors~app.5dda64d70.chunk.js?_sw-precache=afcf49cd5c60bfbbd51535036a2cc734:1:1040084)
    at Object.onGetFunction (https://codesandbox.io/static/js/vendors~app.5dda64d70.chunk.js?_sw-precache=afcf49cd5c60bfbbd51535036a2cc734:1:1029639)
    at Object.get (https://codesandbox.io/static/js/vendors~app.5dda64d70.chunk.js?_sw-precache=afcf49cd5c60bfbbd51535036a2cc734:1:1153433)
    at Sm (https://codesandbox.io/static/js/app.4be7dfb72.js?_sw-precache=999090deb8e469821cd87358d819f159:266:1325969)
    at ua (https://codesandbox.io/static/js/common.9517b6661.chunk.js?_sw-precache=87f4030e32e358792d32fc24f42eb6bf:1:1787440)
    at xs (https://codesandbox.io/static/js/common.9517b6661.chunk.js?_sw-precache=87f4030e32e358792d32fc24f42eb6bf:1:1832703)
    at ml (https://codesandbox.io/static/js/common.9517b6661.chunk.js?_sw-precache=87f4030e32e358792d32fc24f42eb6bf:1:1818279)
    at hl (https://codesandbox.io/static/js/common.9517b6661.chunk.js?_sw-precache=87f4030e32e358792d32fc24f42eb6bf:1:1818204)
    at il (https://codesandbox.io/static/js/common.9517b6661.chunk.js?_sw-precache=87f4030e32e358792d32fc24f42eb6bf:1:1815532)
    at https://codesandbox.io/static/js/common.9517b6661.chunk.js?_sw-precache=87f4030e32e358792d32fc24f42eb6bf:1:1773715
    at https://codesandbox.io/static/js/common.9517b6661.chunk.js?_sw-precache=87f4030e32e358792d32fc24f42eb6bf:1:1849051
    at qo (https://codesandbox.io/static/js/common.9517b6661.chunk.js?_sw-precache=87f4030e32e358792d32fc24f42eb6bf:1:1773424)
    at Xo (https://codesandbox.io/static/js/common.9517b6661.chunk.js?_sw-precache=87f4030e32e358792d32fc24f42eb6bf:1:1773660)
    at Yo (https://codesandbox.io/static/js/common.9517b6661.chunk.js?_sw-precache=87f4030e32e358792d32fc24f42eb6bf:1:1773595)
    at el (https://codesandbox.io/static/js/common.9517b6661.chunk.js?_sw-precache=87f4030e32e358792d32fc24f42eb6bf:1:1812318)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.9517b6661.chunk.js?_sw-precache=87f4030e32e358792d32fc24f42eb6bf:1:1778419)
    at t.setState (https://codesandbox.io/static/js/common.9517b6661.chunk.js?_sw-precache=87f4030e32e358792d32fc24f42eb6bf:1:2032071)
    at https://codesandbox.io/static/js/common.9517b6661.chunk.js?_sw-precache=87f4030e32e358792d32fc24f42eb6bf:1:1876080
    at r (https://codesandbox.io/static/js/common.9517b6661.chunk.js?_sw-precache=87f4030e32e358792d32fc24f42eb6bf:1:920457)
    at https://codesandbox.io/static/js/common.9517b6661.chunk.js?_sw-precache=87f4030e32e358792d32fc24f42eb6bf:1:920687
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (https://codesandbox.io/static/js/common.9517b6661.chunk.js?_sw-precache=87f4030e32e358792d32fc24f42eb6bf:1:920657)
    at k (https://codesandbox.io/static/js/common.9517b6661.chunk.js?_sw-precache=87f4030e32e358792d32fc24f42eb6bf:1:921879)
    at https://codesandbox.io/static/js/common.9517b6661.chunk.js?_sw-precache=87f4030e32e358792d32fc24f42eb6bf:1:922933
    at Object.confirmTransitionTo (https://codesandbox.io/static/js/common.9517b6661.chunk.js?_sw-precache=87f4030e32e358792d32fc24f42eb6bf:1:920396)
    at Object.push (https://codesandbox.io/static/js/common.9517b6661.chunk.js?_sw-precache=87f4030e32e358792d32fc24f42eb6bf:1:922713)
    at e.value (https://codesandbox.io/static/js/app.4be7dfb72.js?_sw-precache=999090deb8e469821cd87358d819f159:266:483191)
    at https://codesandbox.io/static/js/app.4be7dfb72.js?_sw-precache=999090deb8e469821cd87358d819f159:266:818864
    at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3629)
    at Generator._invoke (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3382)
    at Generator.forEach.t.<computed> [as next] (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3986)
    at r (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:206)
    at u (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:417)
  
    in Sm
    in div
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in Styled(styled.div)
    in section
    in Styled(styled.div)
    in Unknown
    in Files___StyledCollapsible
    in Hm
    in Gm
    in div
    in De
    in Unknown
    in div
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in De
    in TC
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by CompuIves** [comment]
Hey @MurhafSousli, apologies for the late reply. In the meantime I've fixed this issue, but I forgot to circle back to this issue to let you know it has been resolved. If you update now to Angular 12, everything should work as expected, and we made the config validation more robust to not crash the editor.
