### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by crowellp** [codesandbox/codesandbox-client#6006]
# 🐛 bug report

## Preflight Checklist

- [x ] I have read the [Contributing Guidelines][contributing] for this project.
- [x ] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I have discovered this error on my own private sandbox, but also noticed it happening on the Angular Material Template.

```
Error: NoSuchMethodError: method not found: 'write$1' on null
    at https://codesandbox.io/static/js/sandbox.68fd4509e.js:1:182854

    at e.value (https://codesandbox.io/static/js/sandbox.68fd4509e.js:1:182973)

    at e.value (https://codesandbox.io/static/js/sandbox.68fd4509e.js:1:181225)

    at Worker.<anonymous> (https://codesandbox.io/static/js/sandbox.68fd4509e.js:1:181833)

    at ZoneDelegate.invokeTask (https://g0rol.csb.app/node_modules/zone.js/dist/zone.js:431:35)

    at Zone.runTask (https://g0rol.csb.app/node_modules/zone.js/dist/zone.js:198:51)

    at ZoneTask.invokeTask [as invoke] (https://g0rol.csb.app/node_modules/zone.js/dist/zone.js:513:38)

    at invokeTask (https://g0rol.csb.app/node_modules/zone.js/dist/zone.js:1671:18)

    at Worker.globalZoneAwareCallback (https://g0rol.csb.app/node_modules/zone.js/dist/zone.js:1708:25)
```

## How has this issue affected you? What are you trying to accomplish?
Browser will not render. Trying to use our SASS Framework.

### To Reproduce

See https://codesandbox.io/s/angular-material-template-g0rol

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by John30013** [comment]
I am seeing the same issue today. One of my sandboxes consistently gives this error, while another one works fine. My stack trace is different, and it's a React project, not Angular. Here's my stack trace:
```
Error
NoSuchMethodError: method not found: 'write$1' on null
▼ 4 stack frames were expanded.
(anonymous function)
https://codesandbox.io/static/js/sandbox.68fd4509e.js:1:182854
e.value
https://codesandbox.io/static/js/sandbox.68fd4509e.js:1:182973
e.value
https://codesandbox.io/static/js/sandbox.68fd4509e.js:1:181225
Worker.<anonymous>
https://codesandbox.io/static/js/sandbox.68fd4509e.js:1:181833
▲ 4 stack frames were expanded.
```
