### ISSUE TITLE
Codesandbox CI package urls cannot be consumed by yarn 2/3

### ISSUE THREAD

**Issue by phryneas** [codesandbox/codesandbox-client#6055]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

The build instructions ([for example here](https://ci.codesandbox.io/status/reduxjs/redux-toolkit/pr/1277/builds/161299)) tell me the "local install instructions":

> `yarn add https://pkg.csb.dev/reduxjs/redux-toolkit/commit/7491320d/@reduxjs/toolkit https://pkg.csb.dev/reduxjs/redux-toolkit/commit/7491320d/@rtk-query/graphql-request-base-query`

This does not work with yarn 2/3

There are two problems with this:

* missing package name
  it would have to be `yarn add packageName@url`

* missing file extension
  yarn will not try to download an url without an extension, since it could also be a git repository.
  According to [the documentation](https://yarnpkg.com/api/modules/plugin_http.html) the download link has to fulfill the TARBALL_REGEXP: `RegExp = /^[^?]*\.(?:tar\.gz|tgz)(?:\?.*)?$/`

So I cannot install the package at all, unless CSB also offers a version of the url ending in `.tar.gz` or `.tgz`

### To Reproduce

```log
yarn init -y
yarn set version berry
yarn add @reduxjs/toolkit@https://pkg.csb.dev/reduxjs/redux-toolkit/commit/7491320d/reduxjs/toolkit 
```
> Internal Error: Invalid descriptor (https://pkg.csb.dev/reduxjs/redux-toolkit/commit/7491320d/@reduxjs/toolkit)
>     at Object.Jo (/home/weber/tmp/ssr-experiments/suspense-data-fetching/.yarn/releases/yarn-3.0.1.cjs:242:11997)
>     at /home/weber/tmp/ssr-experiments/suspense-data-fetching/.yarn/releases/yarn-3.0.1.cjs:310:21378
>     at Array.map (<anonymous>)
>     at fp.execute (/home/weber/tmp/ssr-experiments/suspense-data-fetching/.yarn/releases/yarn-3.0.1.cjs:310:21287)
>     at async fp.validateAndExecute (/home/weber/tmp/ssr-experiments/suspense-data-fetching/.yarn/releases/yarn-3.0.1.cjs:197:620)
>     at async ts.run (/home/weber/tmp/ssr-experiments/suspense-data-fetching/.yarn/releases/yarn-3.0.1.cjs:211:1846)
>     at async ts.runExit (/home/weber/tmp/ssr-experiments/suspense-data-fetching/.yarn/releases/yarn-3.0.1.cjs:211:2013)
>     at async i (/home/weber/tmp/ssr-experiments/suspense-data-fetching/.yarn/releases/yarn-3.0.1.cjs:310:12327)
>     at async r (/home/weber/tmp/ssr-experiments/suspense-data-fetching/.yarn/releases/yarn-3.0.1.cjs:310:10567)

```log
yarn init -y
yarn set version berry
yarn add @reduxjs/toolkit@https://pkg.csb.dev/reduxjs/redux-toolkit/commit/7491320d/reduxjs/toolkit                                                                                           
```
 
> ➤ YN0000: ┌ Resolution step
> ➤ YN0001: │ Error: @reduxjs/toolkit@https://pkg.csb.dev/reduxjs/redux-toolkit/commit/7491320d/reduxjs/toolkit isn't supported by any available resolver
>     at Xc.getResolverByDescriptor (/home/weber/tmp/ssr-experiments/suspense-data-fetching/.yarn/releases/yarn-3.0.1.cjs:294:5330)
>     at Xc.bindDescriptor (/home/weber/tmp/ssr-experiments/suspense-data-fetching/.yarn/releases/yarn-3.0.1.cjs:294:4719)
>     at p (/home/weber/tmp/ssr-experiments/suspense-data-fetching/.yarn/releases/yarn-3.0.1.cjs:303:6959)
>     at async Promise.all (index 0)
>     at async Fe.resolveEverything (/home/weber/tmp/ssr-experiments/suspense-data-fetching/.yarn/releases/yarn-3.0.1.cjs:303:8166)
>     at async /home/weber/tmp/ssr-experiments/suspense-data-fetching/.yarn/releases/yarn-3.0.1.cjs:306:2135
>     at async Se.startTimerPromise (/home/weber/tmp/ssr-experiments/suspense-data-fetching/.yarn/releases/yarn-3.0.1.cjs:275:3730)
>     at async Fe.install (/home/weber/tmp/ssr-experiments/suspense-data-fetching/.yarn/releases/yarn-3.0.1.cjs:306:2074)
>     at async /home/weber/tmp/ssr-experiments/suspense-data-fetching/.yarn/releases/yarn-3.0.1.cjs:311:122
>     at async Function.start (/home/weber/tmp/ssr-experiments/suspense-data-fetching/.yarn/releases/yarn-3.0.1.cjs:275:2287)
> ➤ YN0000: └ Completed
> ➤ YN0000: Failed with errors in 0s 8ms

This is also tracked over at yarn, in https://github.com/yarnpkg/berry/issues/3327

**Comment by lbogdan** [comment]
Hey @phryneas ,

Thanks for your report!

As a workaround, for now, you can use the URL `https://pkg.csb.dev/reduxjs/redux-toolkit/commit/7491320d/@reduxjs/toolkit/_pkg.tgz`, which the original package URL redirects to.

So this works:
```sh
$ yarn add @reduxjs/toolkit@https://pkg.csb.dev/reduxjs/redux-toolkit/commit/7491320d/@reduxjs/toolkit/_pkg.tgz
➤ YN0000: ┌ Resolution step
➤ YN0013: │ @reduxjs/toolkit@https://pkg.csb.dev/reduxjs/redux-toolkit/commit/7491320d/@reduxjs/toolkit/_pkg.tgz can't be found in the cache and will be fetched from the remote server
➤ YN0000: └ Completed in 2s 319ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ immer@npm:9.0.6 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ redux-thunk@npm:2.3.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ redux@npm:4.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ regenerator-runtime@npm:0.13.9 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ reselect@npm:4.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done in 2s 540ms
$ cat package.json 
{
  "name": "ci-yarn2-test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@reduxjs/toolkit": "https://pkg.csb.dev/reduxjs/redux-toolkit/commit/7491320d/@reduxjs/toolkit/_pkg.tgz"
  }
}
```

We should indeed add a yarn 2/3 command to locally install the built packages to the build details page.

**Comment by lbogdan** [comment]
@phryneas Would this be enough?

![image](https://user-images.githubusercontent.com/2083930/132228298-a3b28bc2-8d48-4d53-be5f-9494b0b1c894.png)

**Comment by lbogdan** [comment]
Update:

![image](https://user-images.githubusercontent.com/2083930/132229381-9e5a4799-233f-4c10-a2a1-a82bd0827cb1.png)

**Comment by merceyz** [comment]
I left a comment in https://github.com/codesandbox/codesandbox-ci-ui/issues/17#issuecomment-912740151 but ideally it would be the same pattern for all of them

**Comment by lbogdan** [comment]
@merceyz The name `_pkg.tgz` and the redirect to it is more like an implementation detail, so I'd prefer to use it only if absolutely necessarily.
