### ISSUE TITLE
crypto-js fails: Cannot read properties of undefined (reading 'lib')

### ISSUE THREAD

**Issue by mischnic** [codesandbox/codesandbox-client#6140]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Importing `crypto-js` currently throws
```
Cannot read properties of undefined (reading 'lib')
```

## How has this issue affected you? What are you trying to accomplish?

`@react-pdf/renderer` uses `crypto-js` and therefore also errors at the moment.

### To Reproduce

```js
import crypto from "crypto-js";

console.log(crypto);
```

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |        🤷       |
| Browser          |     Chrome 93.0.4577.82         |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by liudonghua123** [comment]
I have the similar problem when I try to use binary key of AES.encrypt instead of plain string password.

```js
import crypto from 'crypto-js'

// write a simple ase encryption function test
const encrypt = (text, key) => {
    return crypto.AES.encrypt(text, key).toString() // key is a string, and it works without iv cfg
}

const encryptViaByte = (text, key) => {
    // return crypto.AES.encrypt(text, crypto.enc.Hex.parse(key), { iv: crypto.enc.Hex.parse('') }).toString() // key is a non string, and it works only you set iv cfg
    return crypto.AES.encrypt(text, crypto.enc.Hex.parse(key)).toString() // without iv cfg, TypeError: Cannot read properties of undefined (reading '0') will be thrown and from the final stack frame, it is iv is undefined, why not default iv to empty string?
}

encrypt('hello world', '1234')
encryptViaByte('hello world', '010203')
```

```shell
Liu.D.H  crypto-js-demo   221ms  00:27 > node index.js
D:\code\node\playground\crypto-js-demo\node_modules\crypto-js\cipher-core.js:371
                        words[offset + i] ^= block[i];
                                                  ^

TypeError: Cannot read properties of undefined (reading '0')
    at Object.xorBlock (D:\code\node\playground\crypto-js-demo\node_modules\crypto-js\cipher-core.js:371:44)
    at Object.processBlock (D:\code\node\playground\crypto-js-demo\node_modules\crypto-js\cipher-core.js:314:27)
    at Object._doProcessBlock (D:\code\node\playground\crypto-js-demo\node_modules\crypto-js\cipher-core.js:486:25)
    at Object._process (D:\code\node\playground\crypto-js-demo\node_modules\crypto-js\core.js:632:27)
    at Object._doFinalize (D:\code\node\playground\crypto-js-demo\node_modules\crypto-js\cipher-core.js:501:46)
    at Object.finalize (D:\code\node\playground\crypto-js-demo\node_modules\crypto-js\cipher-core.js:163:44)
    at Object.encrypt (D:\code\node\playground\crypto-js-demo\node_modules\crypto-js\cipher-core.js:685:41)
    at Object.encrypt (D:\code\node\playground\crypto-js-demo\node_modules\crypto-js\cipher-core.js:201:59)
    at encryptViaByte (file:///D:/code/node/playground/crypto-js-demo/index.js:10:23)
    at file:///D:/code/node/playground/crypto-js-demo/index.js:14:1

Node.js v20.11.1

Liu.D.H  crypto-js-demo   164ms  00:34 >
```

Here is the related code of final stack frame, `iv` is undefined and the go to else branch and `block` is undefined too.

```js
	            // Choose mixing block
	            if (iv) {
	                block = iv;

	                // Remove IV for subsequent blocks
	                this._iv = undefined;
	            } else {
	                block = this._prevBlock;
	            }

	            // XOR blocks
	            for (var i = 0; i < blockSize; i++) {
	                words[offset + i] ^= block[i];
	            }
```

The simple workaround is update the line to `block = this._prevBlock || [0];`.

**Comment by liudonghua123** [comment]
I updated the comments on https://github.com/brix/crypto-js/issues/439#issuecomment-2172055554.
