### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by wuyuehui** [codesandbox/codesandbox-client#6321]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 96.0.4664 | Windows 10           | bc0eafb18          |

  **Route:**
  https://codesandbox.io/dashboard/drafts?workspace=f79ed719-a0fd-4df7-a103-15bca7afb25a

  **Error Code:**
c5bccb1d12954d53a2734d7f93943006

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of undefined (reading 'type')
  TypeError: Cannot read properties of undefined (reading 'type')
    at Fm (https://codesandbox.io/static/js/app.02cfb9f2b.js:266:307380)
    at ua (https://codesandbox.io/static/js/common.f54fc30db.chunk.js:1:1789537)
    at Ka (https://codesandbox.io/static/js/common.f54fc30db.chunk.js:1:1797802)
    at xs (https://codesandbox.io/static/js/common.f54fc30db.chunk.js:1:1835990)
    at ml (https://codesandbox.io/static/js/common.f54fc30db.chunk.js:1:1820376)
    at hl (https://codesandbox.io/static/js/common.f54fc30db.chunk.js:1:1820301)
    at il (https://codesandbox.io/static/js/common.f54fc30db.chunk.js:1:1817629)
    at https://codesandbox.io/static/js/common.f54fc30db.chunk.js:1:1775812
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.f54fc30db.chunk.js:1:1851148)
    at qo (https://codesandbox.io/static/js/common.f54fc30db.chunk.js:1:1775521)
    at Xo (https://codesandbox.io/static/js/common.f54fc30db.chunk.js:1:1775757)
    at Yo (https://codesandbox.io/static/js/common.f54fc30db.chunk.js:1:1775692)
    at el (https://codesandbox.io/static/js/common.f54fc30db.chunk.js:1:1814415)
    at Sa (https://codesandbox.io/static/js/common.f54fc30db.chunk.js:1:1793210)
    at https://codesandbox.io/static/js/vendors~app.cd182632a.chunk.js:1:1018251
    at e.callback (https://codesandbox.io/static/js/vendors~app.cd182632a.chunk.js:1:1153100)
    at m.flush (https://codesandbox.io/static/js/vendors~app.cd182632a.chunk.js:1:1155987)
    at p.flush (https://codesandbox.io/static/js/vendors~app.cd182632a.chunk.js:1:1152154)
    at Object.cb (https://codesandbox.io/static/js/vendors~app.cd182632a.chunk.js:1:1025214)
    at e.emit (https://codesandbox.io/static/js/vendors~app.cd182632a.chunk.js:1:426117)
    at https://codesandbox.io/static/js/vendors~app.cd182632a.chunk.js:1:1029136
    at Proxy.<anonymous> (https://codesandbox.io/static/js/vendors~app.cd182632a.chunk.js:1:1027650)
    at https://codesandbox.io/static/js/app.02cfb9f2b.js:266:786373
    at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3629)
    at Generator._invoke (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3382)
    at Generator.forEach.t.<computed> [as next] (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3986)
    at r (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:206)
    at u (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:417)
    at https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:476
    at new Promise (<anonymous>)
    at https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:357
    at https://codesandbox.io/static/js/app.02cfb9f2b.js:266:786992
    at Object.addSandboxesToFolder (https://codesandbox.io/static/js/vendors~app.cd182632a.chunk.js:1:1029086)
    at https://codesandbox.io/static/js/app.02cfb9f2b.js:266:310954
    at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3629)
    at Generator._invoke (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3382)
    at Generator.forEach.t.<computed> [as next] (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3986)
    at r (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:206)
    at u (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:417)
    at https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:476
    at new Promise (<anonymous>)
    at https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:357
    at https://codesandbox.io/static/js/app.02cfb9f2b.js:266:311499
    at end (https://codesandbox.io/static/js/app.02cfb9f2b.js:266:317198)
    at Object.endDrag (https://codesandbox.io/static/js/common.f54fc30db.chunk.js:1:1708485)
    at e.<anonymous> (https://codesandbox.io/static/js/common.f54fc30db.chunk.js:1:1679062)
    at Object.keys.reduce.r.<computed> [as endDrag] (https://codesandbox.io/static/js/common.f54fc30db.chunk.js:1:1693672)
    at handleTopDragEndCapture (https://codesandbox.io/static/js/vendors~app.cd182632a.chunk.js:1:1213940)
    at r (https://codesandbox.io/static/js/common.f54fc30db.chunk.js:1:201319)
  
    in Fm
    in qm
    in Fb
    in t
    in t
    in div
    in Content___StyledElement
    in Unknown
    in withRouter()
    in main
    in Dashboard___StyledElement2
    in div
    in Dashboard___StyledStack2
    in div
    in Dashboard___StyledStack
    in Unknown
    in De
    in Unknown
    in JC
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by JamesACS** [comment]
Hey @wuyuehui - Please could you give us some more information about what happened here and what you were doing at the time?
