### ISSUE TITLE
Cannot import repository

### ISSUE THREAD

**Issue by louisguitton** [codesandbox/codesandbox-client#6380]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

 I was trying to import a repository in codesandbox as I usually do.

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 96.0.4664 | OS X 10.15.7           | 314bdeffe          |

  **Route:**
  https://codesandbox.io/dashboard/repositories

  **Error Code:**
09352f4d0ede45cbb5f593d56bcc3256

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot destructure property 'alias' of 'object null' as it is null.
  TypeError: Cannot destructure property 'alias' of 'object null' as it is null.
    at https://codesandbox.io/static/js/default~app~embed.524944515.chunk.js?_sw-precache=ebf3143f5b8d67947a07588beef8eeca:378:343
    at https://codesandbox.io/static/js/app.e78453717.js?_sw-precache=e9bbd2f9cd97fb3d732686954a99ea74:79:376983
    at Array.map (<anonymous>)
    at https://codesandbox.io/static/js/app.e78453717.js?_sw-precache=e9bbd2f9cd97fb3d732686954a99ea74:79:376634
    at Array.map (<anonymous>)
    at $e (https://codesandbox.io/static/js/app.e78453717.js?_sw-precache=e9bbd2f9cd97fb3d732686954a99ea74:79:376370)
    at ua (https://codesandbox.io/static/js/common.eff6be823.chunk.js?_sw-precache=57f0ded86104a9d38228a0994ae26b95:1:1789558)
    at xs (https://codesandbox.io/static/js/common.eff6be823.chunk.js?_sw-precache=57f0ded86104a9d38228a0994ae26b95:1:1834821)
    at ml (https://codesandbox.io/static/js/common.eff6be823.chunk.js?_sw-precache=57f0ded86104a9d38228a0994ae26b95:1:1820397)
    at hl (https://codesandbox.io/static/js/common.eff6be823.chunk.js?_sw-precache=57f0ded86104a9d38228a0994ae26b95:1:1820322)
    at il (https://codesandbox.io/static/js/common.eff6be823.chunk.js?_sw-precache=57f0ded86104a9d38228a0994ae26b95:1:1817650)
    at https://codesandbox.io/static/js/common.eff6be823.chunk.js?_sw-precache=57f0ded86104a9d38228a0994ae26b95:1:1775833
    at https://codesandbox.io/static/js/common.eff6be823.chunk.js?_sw-precache=57f0ded86104a9d38228a0994ae26b95:1:1851169
    at qo (https://codesandbox.io/static/js/common.eff6be823.chunk.js?_sw-precache=57f0ded86104a9d38228a0994ae26b95:1:1775542)
    at Xo (https://codesandbox.io/static/js/common.eff6be823.chunk.js?_sw-precache=57f0ded86104a9d38228a0994ae26b95:1:1775778)
    at Yo (https://codesandbox.io/static/js/common.eff6be823.chunk.js?_sw-precache=57f0ded86104a9d38228a0994ae26b95:1:1775713)
    at se (https://codesandbox.io/static/js/common.eff6be823.chunk.js?_sw-precache=57f0ded86104a9d38228a0994ae26b95:1:1844921)
    at Sn (https://codesandbox.io/static/js/common.eff6be823.chunk.js?_sw-precache=57f0ded86104a9d38228a0994ae26b95:1:1759339)
  
    in $e
    in t
    in Ye
    in Je
    in div
    in span
    in styled.span
    in span
    in styled.span
    in div
    in n
    in Styled(n)
    in Unknown
    in st
    in div
    in ForwardRef(p)
    in ForwardRef(p)
    in elements__TabContent
    in div
    in elements__Container
    in De
    in Unknown
    in Vn
    in div
    in div
    in div
    in div
    in t
    in t
    in Modal___StyledModal
    in n
    in De
    in Unknown
    in Y
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by JamesACS** [comment]
Hey @louisguitton Thanks for the report - Is this a recurring behaviour or has it only happened once?

**Comment by louisguitton** [comment]
> Hey @louisguitton Thanks for the report - Is this a recurring behaviour or has it only happened once?

it's recurring. I started noticing it 3 days ago and it's still happening

**Comment by JamesACS** [comment]
Thanks @louisguitton - Are you only using the one device/browser, or have you tried multiple? 

Additionally, have you tried severing and then re-linking your Github account in CodeSandbox preferences?

**Comment by louisguitton** [comment]
> Thanks @louisguitton - Are you only using the one device/browser, or have you tried multiple?

I've tried with the Brave browser - same issue (but it's chromium I guess, but I don't use any other browsers)

> Additionally, have you tried severing and then re-linking your Github account in CodeSandbox preferences?

just tried that and I'm seeing the same issue.

I mean I didn't get the feeling it was an issue with my account. I'm seeing this
![image](https://user-images.githubusercontent.com/7823843/148804836-1cc2b75e-b467-4cae-8025-c2deb4607cfb.png)

**Comment by JamesACS** [comment]
Would you be able to try it on Firefox, or on another device entirely? 

We're just trying to narrow down the cause :)

**Comment by louisguitton** [comment]
> Would you be able to try it on Firefox, or on another device entirely?


I used Safari and was able to successfully get this screen 
![image](https://user-images.githubusercontent.com/7823843/148808165-47159d46-7cf8-4cdf-af81-4114250ece07.png)

after that, I went back to chrome and saw what the issue was.
My adblocker is blocking the sentry call you're doing
```
Request URL: https://sentry.io/api/2071895/store/?sentry_key=f595bc90ce3646c4a9d76a8d3b84b403&sentry_version=7
Referrer Policy: origin
```
this is the call that comes just before the call to https://codesandbox.io/api/graphql

If I remove my ad blocker, the sentry request goes through and I see the same screen than on Safari.
My ad blocker is uBlock Origin if you want to reproduce.

Hope this helps.

**Comment by louisguitton** [comment]
Here are the sentry breadcrumbs I could get from the chrome dev tools

```json
{
    "exception": {
        "values": [
            {
                "type": "TypeError",
                "value": "Cannot destructure property 'alias' of 'object null' as it is null.",
                "stacktrace": {
                    "frames": [
                        {
                            "colno": 1759339,
                            "filename": "https://codesandbox.io/static/js/common.eff6be823.chunk.js",
                            "function": "Sn",
                            "in_app": true,
                            "lineno": 1
                        },
                        {
                            "colno": 1844921,
                            "filename": "https://codesandbox.io/static/js/common.eff6be823.chunk.js",
                            "function": "se",
                            "in_app": true,
                            "lineno": 1
                        },
                        {
                            "colno": 1775713,
                            "filename": "https://codesandbox.io/static/js/common.eff6be823.chunk.js",
                            "function": "Yo",
                            "in_app": true,
                            "lineno": 1
                        },
                        {
                            "colno": 1775778,
                            "filename": "https://codesandbox.io/static/js/common.eff6be823.chunk.js",
                            "function": "Xo",
                            "in_app": true,
                            "lineno": 1
                        },
                        {
                            "colno": 1775542,
                            "filename": "https://codesandbox.io/static/js/common.eff6be823.chunk.js",
                            "function": "qo",
                            "in_app": true,
                            "lineno": 1
                        },
                        {
                            "colno": 1851169,
                            "filename": "https://codesandbox.io/static/js/common.eff6be823.chunk.js",
                            "function": "t.unstable_runWithPriority",
                            "in_app": true,
                            "lineno": 1
                        },
                        {
                            "colno": 1775833,
                            "filename": "https://codesandbox.io/static/js/common.eff6be823.chunk.js",
                            "function": "?",
                            "in_app": true,
                            "lineno": 1
                        },
                        {
                            "colno": 1817650,
                            "filename": "https://codesandbox.io/static/js/common.eff6be823.chunk.js",
                            "function": "il",
                            "in_app": true,
                            "lineno": 1
                        },
                        {
                            "colno": 1820322,
                            "filename": "https://codesandbox.io/static/js/common.eff6be823.chunk.js",
                            "function": "hl",
                            "in_app": true,
                            "lineno": 1
                        },
                        {
                            "colno": 1820397,
                            "filename": "https://codesandbox.io/static/js/common.eff6be823.chunk.js",
                            "function": "ml",
                            "in_app": true,
                            "lineno": 1
                        },
                        {
                            "colno": 1834821,
                            "filename": "https://codesandbox.io/static/js/common.eff6be823.chunk.js",
                            "function": "xs",
                            "in_app": true,
                            "lineno": 1
                        },
                        {
                            "colno": 1789558,
                            "filename": "https://codesandbox.io/static/js/common.eff6be823.chunk.js",
                            "function": "ua",
                            "in_app": true,
                            "lineno": 1
                        },
                        {
                            "colno": 376370,
                            "filename": "https://codesandbox.io/static/js/app.e78453717.js",
                            "function": "$e",
                            "in_app": true,
                            "lineno": 79
                        },
                        {
                            "filename": "<anonymous>",
                            "function": "Array.map",
                            "in_app": true
                        },
                        {
                            "colno": 376634,
                            "filename": "https://codesandbox.io/static/js/app.e78453717.js",
                            "function": "?",
                            "in_app": true,
                            "lineno": 79
                        },
                        {
                            "filename": "<anonymous>",
                            "function": "Array.map",
                            "in_app": true
                        },
                        {
                            "colno": 376983,
                            "filename": "https://codesandbox.io/static/js/app.e78453717.js",
                            "function": "?",
                            "in_app": true,
                            "lineno": 79
                        },
                        {
                            "colno": 343,
                            "filename": "https://codesandbox.io/static/js/default~app~embed.fdc719b50.chunk.js",
                            "function": "t.getSandboxName",
                            "in_app": true,
                            "lineno": 378
                        }
                    ]
                },
                "mechanism": {
                    "handled": true,
                    "type": "generic"
                }
            }
        ]
    },
    "level": "error",
    "event_id": "7adabe961234408cacfe026a7a56add0",
    "platform": "javascript",
    "sdk": {
        "name": "sentry.javascript.browser",
        "packages": [
            {
                "name": "npm:@sentry/browser",
                "version": "5.19.0"
            }
        ],
        "version": "5.19.0",
        "integrations": [
            "InboundFilters",
            "FunctionToString",
            "Breadcrumbs",
            "GlobalHandlers",
            "LinkedErrors",
            "UserAgent",
            "TryCatch"
        ]
    },
    "timestamp": 1641834732.2877,
    "release": "PROD-1641828197-96066f8b7",
    "extra": {
        "sandboxCount": 5,
        "pro": false,
        "receivedViewCount": 13
    },
    "breadcrumbs": [
        {
            "timestamp": 1641834727.5472,
            "category": "overmind-action",
            "message": "userNotifications.internal.initialize",
            "level": "info",
            "data": {
                "value": "[undefined]"
            }
        },
        {
            "timestamp": 1641834727.5475,
            "category": "overmind-action",
            "message": "internal.setStoredSettings",
            "level": "info",
            "data": {
                "value": "[undefined]"
            }
        },
        {
            "timestamp": 1641834727.5602,
            "category": "xhr",
            "data": {
                "method": "GET",
                "url": "https://raw.githubusercontent.com/codesandbox/codesandbox-client/master/.all-contributorsrc",
                "status_code": 200
            },
            "type": "http"
        },
        {
            "timestamp": 1641834727.7572,
            "category": "xhr",
            "data": {
                "method": "GET",
                "url": "/public/vscode-extensions/v19/bundles/main.min.json",
                "status_code": 200
            },
            "type": "http"
        },
        {
            "timestamp": 1641834732.1253,
            "category": "overmind-action",
            "message": "openCreateSandboxModal",
            "level": "info",
            "data": {
                "value": "{}"
            }
        },
        {
            "timestamp": 1641834732.1304,
            "category": "overmind-action",
            "message": "modals.newSandboxModal.open",
            "level": "info",
            "data": {
                "value": "{}"
            }
        },
        {
            "timestamp": 1641834732.1898,
            "category": "console",
            "data": {
                "arguments": [
                    {
                        "message": "Cannot destructure property 'alias' of 'object null' as it is null.",
                        "name": "TypeError",
                        "stack": "TypeError: Cannot destructure property 'alias' of 'object null' as it is null.\n    at t.getSandboxName (https://codesandbox.io/static/js/default~app~embed.fdc719b50.chunk.js:378:343)\n    at https://codesandbox.io/static/js/app.e78453717.js:79:376983\n    at Array.map (<anonymous>)\n    at https://codesandbox.io/static/js/app.e78453717.js:79:376634\n    at Array.map (<anonymous>)\n    at $e (https://codesandbox.io/static/js/app.e78453717.js:79:376370)\n    at ua (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1789558)\n    at xs (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1834821)\n    at ml (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1820397)\n    at hl (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1820322)\n    at il (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1817650)\n    at https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775833\n    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1851169)\n    at qo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775542)\n    at Xo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775778)\n    at Yo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775713)\n    at se (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1844921)\n    at Sn (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1759339)"
                    }
                ],
                "logger": "console"
            },
            "level": "error",
            "message": "TypeError: Cannot destructure property 'alias' of 'object null' as it is null."
        },
        {
            "timestamp": 1641834732.2861001,
            "category": "overmind-action",
            "message": "codesadboxMounted",
            "level": "info",
            "data": {
                "value": "[undefined]"
            }
        }
    ],
    "request": {
        "url": "https://codesandbox.io/dashboard/repositories?workspace=3890519c-3e7f-4149-99cb-d3007f25a9b6",
        "headers": {
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
        }
    }
}
```

**Comment by JamesACS** [comment]
Thanks @louisguitton - So does the import repository work now that you've disabled the adblocker?

**Comment by louisguitton** [comment]
> Thanks @louisguitton - So does the import repository work now that you've disabled the adblocker?

it did. But I use the ad blocker so I can't use that part of codesandbox's product. A shame it requires me to disable my adblocker. Although I agree this is personal preference, so feel free to close this issue.

**Comment by JamesACS** [comment]
Thanks for confirming Louis, and sorry for the trouble!
