### ISSUE TITLE
sandbox crashed on selecting multile files

### ISSUE THREAD

**Issue by devjs1000** [codesandbox/codesandbox-client#6407]
<h1>💥 Crash Report</h1>

  <h2>I was multiselecting previous projects for deleting them?</h2>

  > I was an unexpected error shows its not possible to delete multiple files at once

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 97.0.4692 | Chrome OS x86_64           | 7b01a4415          |

  **Route:**
  https://codesandbox.io/dashboard/home?workspace=ccf40097-c957-4493-bc2c-f90b1b971e32

  **Error Code:**
0f77ab6211284ce4ae8bba01acc80985

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of undefined (reading 'type')
  TypeError: Cannot read properties of undefined (reading 'type')
    at https://codesandbox.io/static/js/app.274132794.js:266:292703
    at Array.filter (<anonymous>)
    at Im (https://codesandbox.io/static/js/app.274132794.js:266:292664)
    at ua (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1789558)
    at xs (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1834821)
    at ml (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1820397)
    at hl (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1820322)
    at il (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1817650)
    at https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775833
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1851169)
    at qo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775542)
    at Xo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775778)
    at Yo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775713)
    at se (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1844921)
    at Sn (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1759339)
  
    in Im
    in Fm
    in qm
    in Pb
    in t
    in t
    in div
    in Content___StyledElement
    in Unknown
    in withRouter()
    in main
    in Dashboard___StyledElement2
    in div
    in Dashboard___StyledStack2
    in div
    in Dashboard___StyledStack
    in Unknown
    in De
    in Unknown
    in JC
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by JamesACS** [comment]
Hey @devjs1000 - Thanks for flagging this. 

I haven't been able to replicate this - have you encountered it a second time?
