### ISSUE TITLE
CodeSadbox for any actions in Team with new Pro account breaks

### ISSUE THREAD

**Issue by bretonics** [codesandbox/codesandbox-client#6452]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

Doing anything after upgrading to Team Pro and syncing a GH repo (private repo and sandbox).

Now everything fails: creating a new sandbox, importing GH repo...everything results in a CodeSadBox error.

Also tried every nuclear option: log in and out, clearing caches, even updating Chrome...nothing.

Fails everywhere. Now even my own personal space has the same errors. Basically entire account became unusable.

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 98.0.4758 | OS X 10.15.7           | 1ca347c42          |

  **Route:**
  https://codesandbox.io/dashboard/all/?workspace=uuid
  https://codesandbox.io/dashboard/repositories?workspace=uuid

  **Error Code:**
34252cb3c6284373b18b6d3e15430bd2
7fe1d242fe2c45a2af35d8940ca2c348

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot destructure property 'alias' of 'object null' as it is null.
  TypeError: Cannot destructure property 'alias' of 'object null' as it is null.
    at t.getSandboxName (https://codesandbox.io/static/js/default~app~embed.ef8872586.chunk.js:378:343)
    at https://codesandbox.io/static/js/app.9230cadad.js:79:376983
    at Array.map (<anonymous>)
    at https://codesandbox.io/static/js/app.9230cadad.js:79:376634
    at Array.map (<anonymous>)
    at $e (https://codesandbox.io/static/js/app.9230cadad.js:79:376370)
    at ua (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1789558)
    at xs (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1834821)
    at ml (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1820397)
    at hl (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1820322)
    at il (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1817650)
    at https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775833
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1851169)
    at qo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775542)
    at Xo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775778)
    at Yo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775713)
    at se (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1844921)
    at Sn (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1759339)
  
    in $e
    in t
    in Ye
    in Je
    in div
    in span
    in styled.span
    in span
    in styled.span
    in div
    in n
    in Styled(n)
    in Unknown
    in st
    in div
    in ForwardRef(p)
    in ForwardRef(p)
    in elements__TabContent
    in div
    in elements__Container
    in De
    in Unknown
    in Vn
    in div
    in div
    in div
    in div
    in t
    in t
    in Modal___StyledModal
    in n
    in De
    in Unknown
    in Y
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by CompuIves** [comment]
Hey! We just identified the issue and did a temporary fix. Tomorrow we're going to patch it with a long fix!
