### ISSUE TITLE
Crash report: cannot create sandbox

### ISSUE THREAD

**Issue by ConorHKnowde** [codesandbox/codesandbox-client#6471]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

 1. Login with github
 2. Click "create sandbox" in top right
 3. Page error/crash

  <h3>Link to sandbox: N/A (cannot create sandbox)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 97.0.4692 | Linux x86_64           | 7c63c7ac1          |

  **Route:**
  https://codesandbox.io/dashboard/home?workspace=f3c40a7c-467a-4f5f-bd6e-3b1102d4e048

  **Error Code:**
ec2038d7275b4f9ab86892c14f53741a

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot destructure property 'alias' of 'object null' as it is null.
  TypeError: Cannot destructure property 'alias' of 'object null' as it is null.
    at https://codesandbox.io/static/js/default~app~embed.ef8872586.chunk.js?_sw-precache=342bdd63ccbfccaa4c5710d4c14eb3be:378:343
    at https://codesandbox.io/static/js/app.9230cadad.js?_sw-precache=a4de2657a3c03a80812d33baa03c1338:79:376983
    at Array.map (<anonymous>)
    at https://codesandbox.io/static/js/app.9230cadad.js?_sw-precache=a4de2657a3c03a80812d33baa03c1338:79:376634
    at Array.map (<anonymous>)
    at $e (https://codesandbox.io/static/js/app.9230cadad.js?_sw-precache=a4de2657a3c03a80812d33baa03c1338:79:376370)
    at ua (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1789558)
    at xs (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1834821)
    at ml (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1820397)
    at hl (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1820322)
    at il (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1817650)
    at https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775833
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1851169)
    at qo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775542)
    at Xo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775778)
    at Yo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775713)
    at se (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1844921)
    at Sn (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1759339)
  
    in $e
    in t
    in Ye
    in Je
    in div
    in span
    in styled.span
    in span
    in styled.span
    in div
    in n
    in Styled(n)
    in Unknown
    in st
    in div
    in ForwardRef(p)
    in ForwardRef(p)
    in elements__TabContent
    in div
    in elements__Container
    in De
    in Unknown
    in Vn
    in div
    in div
    in div
    in div
    in t
    in t
    in Modal___StyledModal
    in n
    in De
    in Unknown
    in Y
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by ConorHKnowde** [comment]
Hi @JamesACS. It is happening every time, and my coworker is able to reproduce. We both have 'editor' permissions for our "pro" team. We can fork sandboxes, but cannot create them. This affects creating sandboxes as my github user and creating sandboxes for our "pro" team.

**Comment by sannek** [comment]
Hi @ConorHKnowde apologies for this - i am working on a fix and I _hope_ to have it all sorted out in the next hour or two!

**Comment by sannek** [comment]
I've just deployed a fix, so it should not happen anymore! Thanks for reporting and please let me know if anything's still broken!
