### ISSUE TITLE
CRASH:  Folder UI: SelectedItems Array not Cleaned Properly - Total Crash

### ISSUE THREAD

**Issue by DennisSmolek** [codesandbox/codesandbox-client#6480]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>
Organize my Sandboxes

  <h3>Crash Details</h3>
When organizing sandboxes in the "drafts" section once you move sandboxes the remaining list of items becomes a minefield. 
Clicking or right clicking will cause  the page to crash
[VIdeo of steps to reproduce](https://www.loom.com/share/0d21e30e82f0452da6a62fa8a74a0f38)

The issue is because the items that were previously moved become `undefined` in the `selectedItems`array that is passed to `MultiMenu`

[Video to issue cause isolation](https://www.loom.com/share/3615cfb76e6c46a6aa2fc5f1d0a0d024)

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 98.0.4758 | OS X 10.15.7           | b32accec8          |

  **Route:**
  https://codesandbox.io/dashboard/drafts?workspace=b6a471b0-d79b-437d-8c15-c21444ad91f7

  **Error Code:**
ac08f25831a247e598e57fc7fa2cbe3b

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of undefined (reading 'type')
  TypeError: Cannot read properties of undefined (reading 'type')
    at https://codesandbox.io/static/js/app.2a9deefbf.js:266:292716
    at Array.filter (<anonymous>)
    at Im (https://codesandbox.io/static/js/app.2a9deefbf.js:266:292677)
    at ua (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1789558)
    at xs (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1834821)
    at ml (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1820397)
    at hl (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1820322)
    at il (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1817650)
    at https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775833
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1851169)
    at qo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775542)
    at Xo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775778)
    at Yo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775713)
    at se (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1844921)
    at Sn (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1759339)
  
    in Im
    in Fm
    in qm
    in Fb
    in t
    in t
    in div
    in Content___StyledElement
    in Unknown
    in withRouter()
    in main
    in Dashboard___StyledElement2
    in div
    in Dashboard___StyledStack2
    in div
    in Dashboard___StyledStack
    in Unknown
    in De
    in Unknown
    in JC
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by JamesACS** [comment]
Thank you for raising this @DennisSmolek - I've raised it as a bug on our end
