### ISSUE TITLE
React production build fails while development works

### ISSUE THREAD

**Issue by Sharaddition** [codesandbox/codesandbox-client#6489]
# 🐛 bug report

## Description of the problem
My same piece of code works with codesandbox environment, but the production build on Netlify is throwing errors.
## How has this issue affected you? What are you trying to accomplish?
I'm trying to create a production build with codesandbox.

### To Reproduce

You can change the dependencies version in package.json to get more errors like duplicate bitcore lib, etc. 

### Link to sandbox: 
https://codesandbox.io/s/working-o1hfrh?file=/package.json

### Link to build:
https://csb-o1hfrh.netlify.app/
>Check console for error log.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | c93f76ef3              |
| Browser          |     Chrome Version 98      |
| Operating System |    Windows 10     |

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hey @Sharaddition, 

Please could you give us some more specifics about the errors you're encountering? I'm able to load up the Sandbox both on Netlify and CodeSandbox without any issues

**Comment by Sharaddition** [comment]
Hey @JamesACS , my bad.

When you click on the **Strat** button after the app loads. Then you can check the console, that _dev build_ performs all action, but the _production build_ fails at the end.

I think codesandbox changes some env or dependencies for final build.

### Error Log-
```
Uncaught (in promise) Error: Assertion failed
    at n (bn.js:6:21)
    at o.toBuffer (bn.js:529:5)
    at e.u.toBuffer.u.toDER (signature.js:169:22)
    at Object.getSignature (transaction.js:447:37)
    at Object.signTx (transaction.js:413:30)
    at Object.prepareData (transaction.js:767:26)
    at r.value (sendTransaction.js:239:43)
    at r.<anonymous> (sendTransaction.js:462:12)
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
```

**Comment by JamesACS** [comment]
Hey @Sharaddition - Apologies for the delay. 

Even after pressing start it's still working on this end - did you resolve the issue?

**Comment by Sharaddition** [comment]
Thanks @JamesACS for looking back into the issue, just deployed on **[Netlify](https://csb-o1hfrh.netlify.app/)** once again, and I'm still facing the same issue.

**Error log in production build-**
> ![error log](https://user-images.githubusercontent.com/90986869/156891108-edfd32ec-4ecc-435d-9320-9e85aac1279c.png)

**Succesfull execution in CDS env-**
> ![cds env](https://user-images.githubusercontent.com/90986869/156891156-ca136cfc-cdb4-4798-a65c-73d87d0a4da3.png)

**Comment by JamesACS** [comment]
Thanks @Sharaddition - Looking at the Netlify link it does seem to be deploying, just throwing some errors which don't effect functionality?

**Comment by Sharaddition** [comment]
Thanks @JamesACS for your time, I think this is something related to the bundling process of react as mentioned in this [issue](https://github.com/moneybutton/bsv/issues/160#issuecomment-907556404).

**Comment by JamesACS** [comment]
That would make sense @Sharaddition 😅 - have you tried the fix offered there?
