### ISSUE TITLE
clone to local not work

### ISSUE THREAD

**Issue by heyimariel** [codesandbox/codesandbox-client#6529]
I clone codesandbox-client to local

I use yarn install and running yarn start, but it seems not work
What could I do?

```
yarn run v1.22.17
$ yarn build:deps && cross-env NODE_ENV=development lerna run start --scope @codesandbox/common --scope @codesandbox/components --scope app --parallel
$ lerna run build:dev
lerna notice cli v3.16.4
lerna info versioning independent
lerna info Executing command in 16 packages: "npm run build:dev"
lerna info run Ran npm script 'build:dev' in 'browser-dart-sass' in 3.8s:

> browser-dart-sass@1.36.0 build:dev D:\codesandbox\codesandbox-client\packages\browser-dart-sass
> yarn build

$ node index.js
lerna ERR! npm run build:dev exited 1 in 'browser-eslint-rules'
lerna ERR! npm run build:dev stdout:

> browser-eslint-rules@1.0.0 build:dev D:\codesandbox\codesandbox-client\packages\browser-eslint-rules
> yarn build

$ rollup -c
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! npm run build:dev stderr:
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'D:\codesandbox\codesandbox-client\node_modules\rollup\dist\bin\rollup'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
error Command failed with exit code 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! browser-eslint-rules@1.0.0 build:dev: `yarn build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the browser-eslint-rules@1.0.0 build:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ariel\AppData\Roaming\npm-cache\_logs\2022-03-10T07_49_56_238Z-debug.log

lerna ERR! npm run build:dev exited 1 in 'browser-eslint-rules'
lerna WARN complete Waiting for 6 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |   latest           |
| Browser          |     chrome         |
| Node |     v10.22.1         |
| Yarn |    1.22.17         |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by JamesACS** [comment]
Hey @heyimariel - The CodeSandbox client relies on a number of third party libraries and wouldn't work without those installed. 

We do have some instructions here but they haven't been updated in some time: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md#setting-up-the-project-locally

**Comment by naivenaive** [comment]
I tried to build codesandbox accoring to the guideline(https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md#setting-up-the-project-locally), but I still get a lot of error. Is it possible to renew the instruction for building codesanbox locally? Many thanks
