### ISSUE TITLE
Integration with vercel does not work

### ISSUE THREAD

**Issue by anhquande** [codesandbox/codesandbox-client#6582]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 99.0.4844 | Linux x86_64           | 0aa5beeaf          |

  **Route:**
  https://codesandbox.io/signin/eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJDb2RlU2FuZGJveCIsImV4cCI6MTY1MDk1NzI1OCwiaWF0IjoxNjQ4MzY1MjU4LCJpc3MiOiJDb2RlU2FuZGJveCIsImp0aSI6ImNiY2MzOWNlLTM0MjktNGVkYy05MTg2LWNhOWE0Mjc4ZTNmYiIsIm5iZiI6MTY0ODM2NTI1Nywic3ViIjoiVXNlcjozNDQ4Mjk5Mi1hODMzLTQzNmYtOTdiNS01ZTZjNDU1YmI0YTYiLCJ0eXAiOiJhY2Nlc3MifQ.6JwIDE-1QxkKQEsb75UFcESj1cCgJDX2bDdvpfVjvBS2WKJCX7UklgBRfUWuaOk4Wno-O97lcMljCEDycz4Czg

  **Error Code:**
e3ed3c5da02648608ccaa65aa92e245e

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  SecurityError: Blocked a frame with origin "https://codesandbox.io" from accessing a cross-origin frame.
  Error: Blocked a frame with origin "https://codesandbox.io" from accessing a cross-origin frame.
    at new n (https://codesandbox.io/static/js/page-sign-in.ff806d259.chunk.js?_sw-precache=40e205143134d6a3095caf5c52beec79:1:8097)
    at ki (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1781255)
    at Ya (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1798138)
    at xs (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1836093)
    at ml (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1820397)
    at hl (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1820322)
    at il (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1817650)
    at https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775833
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1851169)
    at qo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775542)
    at Xo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775778)
    at Yo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775713)
    at el (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1814436)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1780537)
    at o._.setState (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:2034189)
    at https://codesandbox.io/static/js/default~app~embed.27f22cef3.chunk.js?_sw-precache=4ca1825b803dca75c55b25ba20f62065:477:144893
  
    in n
    in o
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by JamesACS** [comment]
Hey @abeyang - Have you tried to link Vercel through your CodeSandbox preferences? Make sure you're logged into Vercel through their site as well!

**Comment by JamesACS** [comment]
Sorry @abeyang - I've just been informed we're aware of an issue with the Vercel integration - I'll let you know when we have a fix!
