### ISSUE TITLE
Repeated Crash for the last month or more...

### ISSUE THREAD

**Issue by GitToDaChoppa** [codesandbox/codesandbox-client#6664]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 100.0.4896 | OS X 10.15.7           | 998a8d96f          |

  **Route:**
  https://codesandbox.io/dashboard/templates?workspace=f2fc0153-fd02-4c6d-9007-9e0e5391ffc6

  **Error Code:**
4e72bb3f1ef944fda78550a7db4bafc7

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot destructure property 'alias' of 'object null' as it is null.
  TypeError: Cannot destructure property 'alias' of 'object null' as it is null.
    at t.getSandboxName (https://codesandbox.io/static/js/default~app~embed.b3fcd3f15.chunk.js:378:343)
    at https://codesandbox.io/static/js/app.06ca35855.js?_sw-precache=7f6b5262e237b9dcf9bb455b4863e16d:79:379203
    at Array.map (<anonymous>)
    at https://codesandbox.io/static/js/app.06ca35855.js?_sw-precache=7f6b5262e237b9dcf9bb455b4863e16d:79:378854
    at Array.map (<anonymous>)
    at $e (https://codesandbox.io/static/js/app.06ca35855.js?_sw-precache=7f6b5262e237b9dcf9bb455b4863e16d:79:378590)
    at ua (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1789558)
    at xs (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1834821)
    at ml (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1820397)
    at hl (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1820322)
    at il (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1817650)
    at https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775833
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1851169)
    at qo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775542)
    at Xo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775778)
    at Yo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775713)
    at se (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1844921)
    at Sn (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1759339)
  
    in $e
    in t
    in Ye
    in Je
    in div
    in span
    in styled.span
    in span
    in styled.span
    in div
    in n
    in Styled(n)
    in Unknown
    in st
    in div
    in ForwardRef(p)
    in ForwardRef(p)
    in elements__TabContent
    in div
    in elements__Container
    in De
    in Unknown
    in $n
    in div
    in div
    in div
    in div
    in t
    in t
    in Modal___StyledModal
    in n
    in De
    in Unknown
    in Y
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by thorsteinsson** [comment]
I think this happens to me because I have a bookmarked template where the sandbox property is null. I guess the template I bookmarked has been deleted.

<img width="206" alt="image" src="https://user-images.githubusercontent.com/39039/168426294-6c847c4c-7d59-4e78-bebd-ec2ff0474393.png">
