### ISSUE TITLE
Cannot create new template

### ISSUE THREAD

**Issue by natalan** [codesandbox/codesandbox-client#6688]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Create a new Template. I had no previous templates and clicked on Start with a template link.

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 101.0.4951 | OS X 10.15.7           | 68dcbf0a1          |

  **Route:**
  https://codesandbox.io/dashboard/templates

  **Error Code:**
5c6eb41c24b045c7a5248ba95770c933

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot destructure property 'alias' of 'object null' as it is null.
  TypeError: Cannot destructure property 'alias' of 'object null' as it is null.
    at https://codesandbox.io/static/js/default~app~embed.1bfb5d822.chunk.js?_sw-precache=fe47cfe4cb89e987fcde0cfbd98eb885:378:343
    at https://codesandbox.io/static/js/app.758ddc682.js?_sw-precache=dc769125394a4256f3ede57f58b83d75:66:377569
    at Array.map (<anonymous>)
    at https://codesandbox.io/static/js/app.758ddc682.js?_sw-precache=dc769125394a4256f3ede57f58b83d75:66:377220
    at Array.map (<anonymous>)
    at $e (https://codesandbox.io/static/js/app.758ddc682.js?_sw-precache=dc769125394a4256f3ede57f58b83d75:66:376956)
    at ua (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1789558)
    at xs (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1834821)
    at ml (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1820397)
    at hl (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1820322)
    at il (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1817650)
    at https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775833
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1851169)
    at qo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775542)
    at Xo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775778)
    at Yo (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1775713)
    at se (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1844921)
    at Sn (https://codesandbox.io/static/js/common.eff6be823.chunk.js:1:1759339)
  
    in $e
    in t
    in Ye
    in Je
    in div
    in span
    in styled.span
    in span
    in styled.span
    in div
    in n
    in Styled(n)
    in Unknown
    in st
    in div
    in ForwardRef(p)
    in ForwardRef(p)
    in elements__TabContent
    in div
    in elements__Container
    in De
    in Unknown
    in $n
    in div
    in div
    in div
    in div
    in t
    in t
    in Modal___StyledModal
    in n
    in De
    in Unknown
    in Y
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by JamesACS** [comment]
Hey @natalan Please could you try clearing your cookies and browser cache, as well as disabling any ad blockers?
