### ISSUE TITLE
local  api proxy error

### ISSUE THREAD

**Issue by bazingaedward** [codesandbox/codesandbox-client#6769]
# 🐛 bug report

## Preflight Checklist

- [ ] I have read the [Contributing Guidelines][contributing] for this project.
- [ ] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [ ] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |      master branch        |
| Browser          |       Chrome 102.0.5005.115       |
| Operating System |  Mac OS Big sur            |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

After following the [CONTRIBUTION](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)，i run local server [yarn start]. preview iframe not show, and console got error:

> Got an error { Error: socket hang up
    at createHangUpError (_http_client.js:332:15)
    at Socket.socketCloseListener (_http_client.js:373:25)
    at Socket.emit (events.js:203:15)
    at TCP._handle.close (net.js:607:12) code: 'ECONNRESET' }
[HPM] Error occurred while proxying request localhost:3000/api/v1/sandboxes/5d6d3q?teamId=xxxx to https://codesandbox.io/ [ECONNRESET] (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by JamesACS** [comment]
Hey @bazingaedward - Please could you give us a few more details? If you're working locally we'll need to see the code, or if you're working through CodeSandbox, a link to the Sandbox!
