### ISSUE TITLE
CodeSandbox has crashed @12:07 5th July 2022

### ISSUE THREAD

**Issue by loricallum** [codesandbox/codesandbox-client#6778]
<h1>💥 Crash Report</h1>

  <h2>I was using the Angular template to create an app when codesandbox crashed</h2>

  > When i select any templates to start a new codesandbox, it goes back to the same "its broken"

  <h3>[Link to sandbox: [link]() (optional)](https://codesandbox.io/s/angular-angular)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 96.0.4664 | Windows 10           | 8e182084f          |

  **Route:**
  https://codesandbox.io/s/angry-bush-gklstm

  **Error Code:**
9d9cb5e5f29d40ff968dfa5e10d2c49f

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of undefined (reading 'parsed')
  TypeError: Cannot read properties of undefined (reading 'parsed')
    at l.getEntries (https://codesandbox.io/static/js/default~app~embed~sandbox.4b724d5b5.chunk.js:1:15597)
    at je (https://codesandbox.io/static/js/app.189ad2e55.js:253:615916)
    at a.cb (https://codesandbox.io/static/js/app.189ad2e55.js:253:856002)
    at a.runScope (https://codesandbox.io/static/js/vendors~app.3d33f8737.chunk.js:1:1034736)
    at a.evaluate (https://codesandbox.io/static/js/vendors~app.3d33f8737.chunk.js:1:1035176)
    at Object.onGetFunction (https://codesandbox.io/static/js/vendors~app.3d33f8737.chunk.js:1:1024731)
    at Object.get (https://codesandbox.io/static/js/vendors~app.3d33f8737.chunk.js:1:1148525)
    at hm (https://codesandbox.io/static/js/app.189ad2e55.js:253:1349407)
    at ua (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1789558)
    at xs (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1834821)
    at ml (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1820397)
    at hl (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1820322)
    at il (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1817650)
    at https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1775833
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1851169)
    at qo (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1775542)
    at Xo (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1775778)
    at Yo (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1775713)
    at el (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1814436)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1780537)
    at t._.setState (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:2034189)
    at https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1878198
    at r (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:921324)
    at https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:921554
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:921524)
    at k (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:922746)
    at https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:923800
    at Object.confirmTransitionTo (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:921263)
    at Object.push (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:923580)
    at e.value (https://codesandbox.io/static/js/app.189ad2e55.js:253:680265)
    at https://codesandbox.io/static/js/app.189ad2e55.js:253:831996
    at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3629)
    at Generator._invoke (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3382)
    at Generator.forEach.t.<computed> [as next] (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3986)
    at r (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:206)
    at u (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:417)
  
    in hm
    in div
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in Styled(styled.div)
    in section
    in Styled(styled.div)
    in Unknown
    in Files___StyledCollapsible
    in Am
    in Bm
    in div
    in De
    in Unknown
    in div
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in De
    in gy
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by CodeSandboxTeam** [comment]
Please could you try clearing your cookies and browser cache and disabling any adblockers that you may have active? 


This should resolve any issues. 



--- original message ---
On July 5, 2022 at 12:11 PM GMT+1 ***@***.*** wrote:



💥 Crash Report

I was using the Angular template to create an app when codesandbox crashed

> When i select any templates to start a new codesandbox, it goes back to the same "its broken"


[Link to sandbox: [link]() (optional)](https://codesandbox.io/s/angular-angular)

Crash Details
EnvironmentBrowser Version Operating System CodeSandbox Version 
chrome 96.0.4664 Windows 10 8e18208 


Route:

https://codesandbox.io/s/angry-bush-gklstm

Error Code:

9d9cb5e5f29d40ff968dfa5e10d2c49f
Error Message
TypeError: Cannot read properties of undefined (reading 'parsed')
TypeError: Cannot read properties of undefined (reading 'parsed')
at l.getEntries (https://codesandbox.io/static/js/default~app~embed~sandbox.4b724d5b5.chunk.js:1:15597)
at je (https://codesandbox.io/static/js/app.189ad2e55.js:253:615916)
at a.cb (https://codesandbox.io/static/js/app.189ad2e55.js:253:856002)
at a.runScope (https://codesandbox.io/static/js/vendors~app.3d33f8737.chunk.js:1:1034736)
at a.evaluate (https://codesandbox.io/static/js/vendors~app.3d33f8737.chunk.js:1:1035176)
at Object.onGetFunction (https://codesandbox.io/static/js/vendors~app.3d33f8737.chunk.js:1:1024731)
at Object.get (https://codesandbox.io/static/js/vendors~app.3d33f8737.chunk.js:1:1148525)
at hm (https://codesandbox.io/static/js/app.189ad2e55.js:253:1349407)
at ua (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1789558)
at xs (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1834821)
at ml (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1820397)
at hl (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1820322)
at il (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1817650)
at https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1775833
at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1851169)
at qo (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1775542)
at Xo (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1775778)
at Yo (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1775713)
at el (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1814436)
at Object.enqueueSetState (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1780537)
at t._.setState (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:2034189)
at https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1878198
at r (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:921324)
at https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:921554
at Array.forEach (<anonymous>)
at Object.notifyListeners (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:921524)
at k (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:922746)
at https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:923800
at Object.confirmTransitionTo (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:921263)
at Object.push (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:923580)
at e.value (https://codesandbox.io/static/js/app.189ad2e55.js:253:680265)
at https://codesandbox.io/static/js/app.189ad2e55.js:253:831996
at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3629)
at Generator._invoke (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3382)
at Generator.forEach.t.<computed> [as next] (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3986)
at r (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:206)
at u (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:417)

in hm
in div
in elements__Opener
in div
in Unknown
in DropTarget(Component)
in div
in Styled(styled.div)
in section
in Styled(styled.div)
in Unknown
in Files___StyledCollapsible
in Am
in Bm
in div
in De
in Unknown
in div
in elements__Container
in Unknown
in WithTheme(Component)
in div
in t
in div
in t
in div
in div
in styled.div
in div
in elements__Container
in De
in gy
in Unknown
in Unknown
in t
in t
in div
in elements__Content
in n
in withRouter(n)
in div
in elements__Container
in Unknown
in withRouter()
in t
in Unknown
in De
in c
in t


—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
--- end of original message ---
