### ISSUE TITLE
Crash when Attempting to Create Sandbox

### ISSUE THREAD

**Issue by jeremyw-dobeu** [codesandbox/codesandbox-client#6869]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

Creating a sandbox

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | Brave   | 104.0.0 | Windows 11           | 331dcb77e          |

  **Route:**
  https://codesandbox.io/dashboard/home?workspace=7f61c2de-b1ff-4d20-8f97-4105d193ac19

  **Error Code:**
8e86a5c9f9204230b2e2d74097021243

  </details>
When I attempt to create a new sandbox this comes up as the error.
  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot destructure property 'alias' of 'object null' as it is null.
  TypeError: Cannot destructure property 'alias' of 'object null' as it is null.
    at t.getSandboxName (https://codesandbox.io/static/js/default~app~embed.aa916a976.chunk.js:378:343)
    at https://codesandbox.io/static/js/app.b0f405f16.js:66:377691
    at Array.map (<anonymous>)
    at https://codesandbox.io/static/js/app.b0f405f16.js:66:377342
    at Array.map (<anonymous>)
    at $e (https://codesandbox.io/static/js/app.b0f405f16.js:66:377078)
    at ua (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1789558)
    at xs (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1834821)
    at ml (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1820397)
    at hl (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1820322)
    at il (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1817650)
    at https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1775833
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1851169)
    at qo (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1775542)
    at Xo (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1775778)
    at Yo (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1775713)
    at se (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1844921)
    at Sn (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1759339)
  
    in $e
    in t
    in Ye
    in Je
    in div
    in span
    in styled.span
    in span
    in styled.span
    in div
    in n
    in Styled(n)
    in Unknown
    in st
    in div
    in ForwardRef(p)
    in ForwardRef(p)
    in elements__TabContent
    in div
    in elements__Container
    in De
    in Unknown
    in Yn
    in div
    in div
    in div
    in div
    in t
    in t
    in Modal___StyledModal
    in n
    in De
    in Unknown
    in Y
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by sannek** [comment]
I also replied via email, but copying it here for completion:

> That is strange and I have investigated. It looks like one of your bookmarked templates got in a weird state, which caused the crash. I have removed that template from your bookmarks, and I expect that the create sandbox button will now work.
