### ISSUE TITLE
Error when switching to the Home tab of the dashboard

### ISSUE THREAD

**Issue by OyewoleOyedeji** [codesandbox/codesandbox-client#6875]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 105.0.0 | Linux x86_64           | 0752669f1          |

  **Route:**
  https://codesandbox.io/dashboard/home?workspace=68bf36e6-8ae0-4543-9c6a-8a09df694a6b

  **Error Code:**
b2768153b69e4407aa7b2b7b207fc11d

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of undefined (reading 'type')
  TypeError: Cannot read properties of undefined (reading 'type')
    at Hm (https://codesandbox.io/static/js/app.f04b6be5a.js:253:301514)
    at ua (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1789558)
    at Ka (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1797823)
    at xs (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1836011)
    at ml (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1820397)
    at hl (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1820322)
    at il (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1817650)
    at https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1775833
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1851169)
    at qo (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1775542)
    at Xo (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1775778)
    at Yo (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1775713)
    at el (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1814436)
    at Sa (https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1793231)
    at https://codesandbox.io/static/js/vendors~app.3d33f8737.chunk.js:1:1016633
    at e.callback (https://codesandbox.io/static/js/vendors~app.3d33f8737.chunk.js:1:1151482)
    at m.flush (https://codesandbox.io/static/js/vendors~app.3d33f8737.chunk.js:1:1154369)
    at p.flush (https://codesandbox.io/static/js/vendors~app.3d33f8737.chunk.js:1:1150536)
    at t (https://codesandbox.io/static/js/vendors~app.3d33f8737.chunk.js:1:1023639)
  
    in Hm
    in Km
    in _b
    in t
    in t
    in div
    in Content___StyledElement
    in Unknown
    in withRouter()
    in main
    in Dashboard___StyledElement2
    in div
    in Dashboard___StyledStack2
    in div
    in Dashboard___StyledStack
    in Unknown
    in De
    in Unknown
    in ax
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by alexnm** [comment]
Was probably fixed since open, please reopen it again it if persist with some additional details on the steps that lead to the crash
