### ISSUE TITLE
Crashes when creating new sandbox

### ISSUE THREAD

**Issue by stopyransky** [codesandbox/codesandbox-client#6883]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > I cleared cache and removed all cookies, deleted all possible session/local storage, re-loggedin and i receive crash when trying to create new sandbox (via + button on the dashboard or via "Create sandbox" button in top right). 

<img width="705" alt="image" src="https://user-images.githubusercontent.com/9521041/189959088-21aedb6d-d8da-48c3-869a-369948bc4eb2.png">

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 105.0.0 | OS X 10.15.7           | c0b9a7fc5          |

  **Route:**
  https://codesandbox.io/dashboard/home?workspace=0749a3f4-3076-4b72-b011-73e24a984d45

  **Error Code:**
e136d621200c484aadfe52c3c2547a50

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot destructure property 'alias' of 'object null' as it is null.
  TypeError: Cannot destructure property 'alias' of 'object null' as it is null.
    at t.getSandboxName (https://codesandbox.io/static/js/default~app~embed.a4eb7f2a6.chunk.js:378:343)
    at https://codesandbox.io/static/js/app.01bcb007b.js:66:375109
    at Array.map (<anonymous>)
    at https://codesandbox.io/static/js/app.01bcb007b.js:66:374760
    at Array.map (<anonymous>)
    at $e (https://codesandbox.io/static/js/app.01bcb007b.js:66:374496)
    at ua (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1788854)
    at xs (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1834117)
    at ml (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1819693)
    at hl (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1819618)
    at il (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1816946)
    at https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775129
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1850465)
    at qo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1774838)
    at Xo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775074)
    at Yo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775009)
    at se (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1844217)
    at Sn (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1758635)
  
    in $e
    in t
    in Ye
    in Je
    in div
    in span
    in styled.span
    in span
    in styled.span
    in div
    in n
    in Styled(n)
    in Unknown
    in st
    in div
    in ForwardRef(p)
    in ForwardRef(p)
    in elements__TabContent
    in div
    in elements__Container
    in De
    in Unknown
    in Yn
    in div
    in div
    in div
    in div
    in t
    in t
    in Modal___StyledModal
    in n
    in De
    in Unknown
    in Y
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by sannek** [comment]
I just deployed a fix for this -- Could you try again and re-open the issue if it still happens? Thanks!
