### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by securitybeautystar** [codesandbox/codesandbox-client#6895]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 105.0.0 | Windows 10           | ae862fcbe          |

  **Route:**
  https://codesandbox.io/search?refinementList%5Btemplate%5D=&refinementList%5Bnpm_dependencies.dependency%5D%5B0%5D=three.js&page=1&configure%5BhitsPerPage%5D=12&query=

  **Error Code:**
5914fa4858af462aa38ab422207dffdb

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ys (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1809949)
    at yl (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1828933)
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1850465)
    at qo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1774838)
    at bl (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1826818)
    at il (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1817145)
    at https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775129
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1850465)
    at qo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1774838)
    at Xo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775074)
    at Yo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775009)
    at el (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1813732)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1779833)
    at _.setState (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:2033485)
    at https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1877494
    at r (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:921324)
    at https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:921554
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:921524)
    at k (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:922746)
    at https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:923800
    at Object.confirmTransitionTo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:921263)
    at Object.push (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:923580)
    at https://codesandbox.io/static/js/page-search.8b30a6c23.chunk.js:238:18736
  
    in hitComponent
    in li
    in ul
    in div
    in ln
    in AlgoliaHits(ln)
    in div
    in styled.div
    in div
    in elements__Container
    in he
    in div
    in div
    in elements__Main
    in div
    in t
    in n
    in div
    in elements__Content
    in div
    in styled.div
    in div
    in styled.div
    in div
    in styled.div
    in Unknown
    in div
    in elements__Container
    in we
    in o
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by alexnm** [comment]
Worked on a fix for this, but we couldn't reproduce it 100%. Please reopen it if it happens again
