### ISSUE TITLE
💥 Crash Report

### ISSUE THREAD

**Issue by milkshakegum** [codesandbox/codesandbox-client#6908]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!\

I was just trying to import this github repo to codesandbox: https://github.com/googlecreativelab/chrome-music-lab/tree/master/harmonics%20%26%20strings

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 105.0.0 | Windows 10           | ae862fcbe          |

  **Route:**
  https://codesandbox.io/s/jolly-keldysh-kvgd3c

  

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of undefined (reading 'id')
  TypeError: Cannot read properties of undefined (reading 'id')
    at https://codesandbox.io/static/js/app.131f7c579.js:253:1356002
    at ua (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1788854)
    at Ka (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1797119)
    at qa (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1796938)
    at xs (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1837592)
    at ml (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1819693)
    at hl (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1819618)
    at il (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1816946)
    at https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775129
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1850465)
  
    in Unknown
    in div
    in hm
    in div
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in Styled(styled.div)
    in section
    in Styled(styled.div)
    in Unknown
    in Files___StyledCollapsible
    in Am
    in Bm
    in div
    in De
    in Unknown
    in div
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in De
    in gy
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by alexnm** [comment]
I tried importing the repo and it seems there's a problem with the container, but not sure why you got that runtime error, as it didn't happen to me. Can you please try again and see if you still get the crash?
