### ISSUE TITLE
Sndbox crash

### ISSUE THREAD

**Issue by deenjohn** [codesandbox/codesandbox-client#6933]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 105.0.0 | OS X 10.15.7           | ae862fcbe          |

  **Route:**
  https://codesandbox.io/s/autosearchdropdown-9tg6p1?file=/src/AutoSearch.js

  **Error Code:**
076ad07690084c4aa8adb9bd4c766d5b

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  RangeError: Maximum call stack size exceeded
  RangeError: Maximum call stack size exceeded
    at https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:959163
    at P (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:2035555)
    at e (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:2034869)
    at I (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:2035334)
    at Object.forEach (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:2036212)
    at e (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:959092)
    at t.render (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:959431)
    at Xa (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1800295)
    at Ya (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1800088)
    at xs (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1835389)
    at ml (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1819693)
    at hl (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1819618)
    at il (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1816946)
    at https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775129
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1850465)
    at qo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1774838)
    at Xo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775074)
    at Yo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775009)
    at se (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1844217)
    at Sn (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1758635)
  
    in t
    in div
    in Styled(div)
    in t
    in WithTheme(t)
    in div
    in Styled(div)
    in div
    in Styled(div)
    in v
    in t
    in div
    in Styled(div)
    in v
    in t
    in div
    in elements__Messages
    in div
    in elements__Container
    in n
    in WithTheme(n)
    in div
    in elements__ContentContainer
    in div
    in elements__Container
    in n
    in div
    in div
    in t
    in div
    in t
    in div
    in De
    in $t
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in De
    in gy
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by alexnm** [comment]
I see this works in the meantime, was it a sandbox error in your code? Like a `useEffect` without a depedency parameter. Please re-open this if it happens again.
