### ISSUE TITLE
Import from Github 

### ISSUE THREAD

**Issue by ChadricOG** [codesandbox/codesandbox-client#7003]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 105.0.0 | Windows 10           | f419862e5          |

  **Route:**
  https://codesandbox.io/s/

  

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of null (reading 'name')
  TypeError: Cannot read properties of null (reading 'name')
    at kn (https://codesandbox.io/static/js/app.04f370e3b.js:9:404351)
    at ua (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1788854)
    at Ka (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1797119)
    at xs (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1835307)
    at ml (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1819693)
    at hl (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1819618)
    at il (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1816946)
    at https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775129
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1850465)
    at qo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1774838)
  
    in kn
    in div
    in Editor___StyledElement3
    in div
    in Styled(styled.div)
    in div
    in styled.div
    in div
    in styled.div
    in div
    in Editor___StyledElement
    in De
    in Unknown
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in De
    in gy
    in Unknown
    in Unknown
    in component
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by tristandubbeld** [comment]
Hi @ChadricOG, thanks for the report. This seems to be the same issue as the one I potentially fixed in #7008. Please let me know if this still occurs to you when it has been merged and released!
