### ISSUE TITLE
Crash on projects shift select

### ISSUE THREAD

**Issue by leonardoprimieri** [codesandbox/codesandbox-client#7004]
<h1>💥 Crash Report</h1>

  <h2>Crash on shift select</h2>

  > When you select lot of projects with shift, exclude them, and click on a project options with shift, the crash screen opens

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 105.0.0 | Linux x86_64           | f419862e5          |

  **Route:**
  https://codesandbox.io/dashboard/drafts?workspace=dece934f-2b32-45b5-9925-ac1e074d17b7

  **Error Code:**
2bbd46cbcce94b308176b06e65e7f851

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of undefined (reading 'type')
  TypeError: Cannot read properties of undefined (reading 'type')
    at jf (https://codesandbox.io/static/js/app.04f370e3b.js:9:732746)
    at ua (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1788854)
    at Ka (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1797119)
    at xs (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1835307)
    at ml (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1819693)
    at hl (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1819618)
    at il (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1816946)
    at https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775129
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1850465)
    at qo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1774838)
    at Xo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775074)
    at Yo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775009)
    at se (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1844217)
    at Sn (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1758635)
  
    in jf
    in Bf
    in Mv
    in t
    in t
    in div
    in Content___StyledElement
    in Unknown
    in withRouter()
    in main
    in Dashboard___StyledElement2
    in div
    in Dashboard___StyledStack2
    in div
    in Dashboard___StyledStack
    in Unknown
    in De
    in Unknown
    in PS
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by tristandubbeld** [comment]
Hey @leonardoprimieri, thanks for reporting the issue! I think I've found what the issue was and I've created #7007 to fix this. When it's merged and deployed, please let know if you encounter this issue again. Thanks for helping out!
