### ISSUE TITLE
something broken

### ISSUE THREAD

**Issue by shosan16** [codesandbox/codesandbox-client#7005]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 105.0.0 | OS X 10.15.7           | f419862e5          |

  **Route:**
  https://codesandbox.io/dashboard/repositories?workspace=e794ac3a-3024-47ca-8731-7e09e799e526

  **Error Code:**
5edaced6e64a473994c3c551994315da

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of null (reading 'name')
  TypeError: Cannot read properties of null (reading 'name')
    at kn (https://codesandbox.io/static/js/app.04f370e3b.js:9:404351)
    at ua (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1788854)
    at xs (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1834117)
    at ml (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1819693)
    at hl (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1819618)
    at il (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1816946)
    at https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775129
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1850465)
    at qo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1774838)
    at Xo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775074)
    at Yo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775009)
    at se (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1844217)
    at Sn (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1758635)
    at HTMLDocument.r (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:201319)
  
    in kn
    in div
    in div
    in div
    in div
    in t
    in t
    in Modal___StyledModal
    in n
    in De
    in Unknown
    in Y
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by tristandubbeld** [comment]
Hi @shosan16, thanks for the report! I've created #7008 in an attempt to fix this. Please let us know if the issue still occurs after it has been merged and released.
