### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by levi5540** [codesandbox/codesandbox-client#7085]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 107.0.0 | Windows 10           | 8c64077d1          |

  **Route:**
  https://codesandbox.io/dashboard/repositories?workspace=a27e4098-49c1-407b-a055-b0d3c6e3530a

  **Error Code:**
d784d3a90ac74ec184f4547a915941a8

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ys (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1809949)
    at yl (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1828933)
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1850465)
    at qo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1774838)
    at bl (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1826818)
    at il (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1817145)
    at https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775129
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1850465)
    at qo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1774838)
    at Xo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775074)
    at Yo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775009)
    at el (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1813732)
    at Sa (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1792527)
    at https://codesandbox.io/static/js/vendors~app.81e90e3c2.chunk.js:1:1007219
    at e.callback (https://codesandbox.io/static/js/vendors~app.81e90e3c2.chunk.js:1:1142068)
    at m.flush (https://codesandbox.io/static/js/vendors~app.81e90e3c2.chunk.js:1:1144955)
    at p.flush (https://codesandbox.io/static/js/vendors~app.81e90e3c2.chunk.js:1:1141122)
    at t (https://codesandbox.io/static/js/vendors~app.81e90e3c2.chunk.js:1:1014225)
  
    in span
    in Styled(styled.div)
    in span
    in Notification___StyledText
    in div
    in Styled(styled.div)
    in div
    in Notification___StyledElement
    in sy
    in div
    in Selection___StyledElement
    in np
    in gk
    in t
    in t
    in div
    in Content___StyledElement
    in Unknown
    in withRouter()
    in main
    in Dashboard___StyledElement2
    in div
    in Dashboard___StyledStack2
    in div
    in Dashboard___StyledStack
    in Unknown
    in De
    in Unknown
    in Wk
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by alexnm** [comment]
Hey! Thanks for reporting this. Can you please let us know what you were doing when the crash occurred? Are you still able to see it if you refresh?
