### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Patiflower** [codesandbox/codesandbox-client#7104]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 106.0.0 | Windows 10           | 41273ed0b          |

  **Route:**
  https://codesandbox.io/dashboard/repositories?workspace=6a54b956-667e-4b88-be76-b6748c22c432

  **Error Code:**
9b9d18f2e49a49c7975e5e67cd588453

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ys (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1809949)
    at yl (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1828933)
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1850465)
    at qo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1774838)
    at bl (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1826818)
    at il (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1817145)
    at https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775129
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1850465)
    at qo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1774838)
    at Xo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775074)
    at Yo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775009)
    at el (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1813732)
    at Sa (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1792527)
    at https://codesandbox.io/static/js/vendors~app.bfacb1130.chunk.js:1:1007086
    at e.callback (https://codesandbox.io/static/js/vendors~app.bfacb1130.chunk.js:1:1141935)
    at m.flush (https://codesandbox.io/static/js/vendors~app.bfacb1130.chunk.js:1:1144822)
    at p.flush (https://codesandbox.io/static/js/vendors~app.bfacb1130.chunk.js:1:1140989)
    at t (https://codesandbox.io/static/js/vendors~app.bfacb1130.chunk.js:1:1014092)
  
    in span
    in Styled(styled.div)
    in span
    in Notification___StyledText
    in div
    in Styled(styled.div)
    in div
    in Notification___StyledElement
    in py
    in div
    in Selection___StyledElement
    in pp
    in yk
    in t
    in t
    in div
    in Content___StyledElement
    in Unknown
    in withRouter()
    in main
    in Dashboard___StyledElement2
    in div
    in Dashboard___StyledStack2
    in div
    in Dashboard___StyledStack
    in Unknown
    in De
    in Unknown
    in Zk
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by alexnm** [comment]
Hey! Thanks for reporting this. Can you please let us know what you were doing when the crash occurred? Are you still able to see it if you refresh?
