### ISSUE TITLE
erreur

### ISSUE THREAD

**Issue by poupoug** [codesandbox/codesandbox-client#7192]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 107.0.0 | Linux x86_64           | 9baec3137          |

  **Route:**
  https://codesandbox.io/s/techchallenge-web-dev-starter-forked-6zz7w8?file=/index.html

  **Error Code:**
f97be58279bc43d083c6a7567be27616

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ys (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1820035)
    at ms (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1818036)
    at ys (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1819772)
    at yl (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1839037)
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1860569)
    at qo (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1784942)
    at bl (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1836922)
    at il (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1827249)
    at https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1785233
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1860569)
    at qo (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1784942)
    at Xo (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1785178)
    at Yo (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1785113)
    at se (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1854321)
    at Sn (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1768739)
  
    in elements__Container
    in n
    in div
    in elements__ContentContainer
    in div
    in elements__Container
    in n
    in div
    in div
    in t
    in div
    in t
    in div
    in De
    in $t
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in De
    in ly
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by tristandubbeld** [comment]
Hi @poupoug! Could you please describe what you were doing when this error occurred? That way it's easier for us to debug this error.
