### ISSUE TITLE
An error occured when I tried to navigate "https://codesandbox.io/search?refinementList%5Bnpm_dependencies.dependency%5D%5B0%5D=googleapis&page=1&configure%5BhitsPerPage%5D=12".

### ISSUE THREAD

**Issue by goldnite** [codesandbox/codesandbox-client#7319]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > I tried to find out sandboxes which uses googleapis module.

  <h3>Link to sandbox: [https://codesandbox.io/search?refinementList%5Bnpm_dependencies.dependency%5D%5B0%5D=googleapis&page=1&configure%5BhitsPerPage%5D=12]</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 108.0.0 | Windows 10           | ab522c2a5          |

  **Route:**
  https://codesandbox.io/search?refinementList%5Bnpm_dependencies.dependency%5D%5B0%5D=googleapis&page=1&configure%5BhitsPerPage%5D=12

  **Error Code:**
5e5adeaf541d41b7ae9eea9a18643807

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ys (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1820053)
    at yl (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1839037)
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1860569)
    at qo (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1784942)
    at bl (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1836922)
    at il (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1827249)
    at https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1785233
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1860569)
    at qo (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1784942)
    at Xo (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1785178)
    at Yo (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1785113)
    at el (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1823836)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1789937)
    at _.setState (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:2043589)
    at https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1887598
    at r (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:921324)
    at https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:921554
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:921524)
    at k (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:922746)
    at https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:923800
    at Object.confirmTransitionTo (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:921263)
    at Object.push (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:923580)
    at https://codesandbox.io/static/js/page-search.eac609a53.chunk.js:238:18731
  
    in hitComponent
    in li
    in ul
    in div
    in ln
    in AlgoliaHits(ln)
    in div
    in styled.div
    in div
    in elements__Container
    in he
    in div
    in div
    in elements__Main
    in div
    in t
    in n
    in div
    in elements__Content
    in div
    in styled.div
    in div
    in styled.div
    in div
    in styled.div
    in Unknown
    in div
    in elements__Container
    in we
    in o
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by DeMoorJasper** [comment]
Can't reproduce this issue, I've had this issue in the past being caused by chrome extensions, not sure if that's the case here.

Is there a way I can easily reproduce this?
