### ISSUE TITLE
Crash on team page settings

### ISSUE THREAD

**Issue by pixelass** [codesandbox/codesandbox-client#7334]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 109.0.0 | OS X 10.15.7           | 41cc76503          |

  **Route:**
  https://codesandbox.io/dashboard/settings?workspace=2ad16d97-42cf-49d7-aa8d-e3587729c609

  **Error Code:**
3e227e4394254f5fb880335ad294339d

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of null (reading 'origin')
  TypeError: Cannot read properties of null (reading 'origin')
    at ex (https://codesandbox.io/static/js/app.4d20f3abc.js?_sw-precache=a670e43d502e84a88b900499d3d84ac4:9:545809)
    at ua (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1798958)
    at xs (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1844221)
    at ml (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1829797)
    at hl (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1829722)
    at il (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1827050)
    at https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1785233
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1860569)
    at qo (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1784942)
    at Xo (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1785178)
    at Yo (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1785113)
    at se (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1854321)
    at Sn (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1768739)
  
    in ex
    in t
    in t
    in t
    in t
    in div
    in TeamSettings___StyledStack
    in div
    in TeamSettings___StyledElement
    in fx
    in div
    in Settings___StyledElement2
    in BS
    in t
    in t
    in div
    in Content___StyledElement
    in Unknown
    in withRouter()
    in main
    in Dashboard___StyledElement4
    in div
    in Dashboard___StyledStack2
    in div
    in Dashboard___StyledStack
    in Unknown
    in De
    in Unknown
    in Tw
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by tristandubbeld** [comment]
Thanks for the report @pixelass! I've just created a PR that should fix this. Let us know if something else is up or this issue persists for you, we really appreciate your help!
