### ISSUE TITLE
Upon clicking on new template and then "official templates" crashes

### ISSUE THREAD

**Issue by kirso** [codesandbox/codesandbox-client#7337]
<h1>💥 Crash Report</h1>

  <h2>Trying to create a new template</h2>

  > Clicked on + new template top left corner. Then select "Official templates" from the left side menu of the modal. Then it crashes as per message below

  <h3>Link to sandbox: https://codesandbox.io/dashboard/recent?workspace=3113fff1-3093-4409-91a3-2d3cc178e98d</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 109.0.0 | OS X 10.15.7           | 41cc76503          |

  **Route:**
  https://codesandbox.io/dashboard/recent?workspace=3113fff1-3093-4409-91a3-2d3cc178e98d

  

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
  Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Bl (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1849743)
    at f (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1794028)
    at m (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1795304)
    at https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1797322
    at Ua (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1806257)
    at xs (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1846179)
    at ml (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1829797)
    at hl (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1829722)
    at il (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1827050)
    at https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1785233
  
    in div
    in TemplateCard___StyledStack2
    in div
    in TemplateCard___StyledStack
    in button
    in TemplateCard___StyledTemplateButton
    in h
    in div
    in elements__TemplateGrid
    in div
    in TemplateCategoryList___StyledStack
    in he
    in div
    in ForwardRef(p)
    in ForwardRef(p)
    in elements__TabContent
    in Rt
    in div
    in elements__ModalContent
    in div
    in elements__ModalBody
    in div
    in elements__Container
    in De
    in Unknown
    in Zt
    in div
    in div
    in div
    in div
    in t
    in t
    in Modal___StyledModal
    in n
    in De
    in Unknown
    in te
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by tristandubbeld** [comment]
Thanks for the report @kirso! We've just merged a PR that fixes this issue and it will be deployed to production soon.
