### ISSUE TITLE
Tried to change Change billing interval and app crashed

### ISSUE THREAD

**Issue by sdkdeepa** [codesandbox/codesandbox-client#7339]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 109.0.0 | OS X 10.15.7           | 19008a7a4          |

  **Route:**
  https://codesandbox.io/pro

  **Error Code:**
ef5244632ffe4e18aed3d44470a7d8b4

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of null (reading 'plan')
  TypeError: Cannot read properties of null (reading 'plan')
    at re (https://codesandbox.io/static/js/page-pro.ec37d5fb6.chunk.js?_sw-precache=53db6671e9eca4286697c733395f5cd9:1:10267)
    at ua (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1798958)
    at Ka (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1807223)
    at xs (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1845411)
    at ml (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1829797)
    at hl (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1829722)
    at il (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1827050)
    at https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1785233
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1860569)
    at qo (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1784942)
    at Xo (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1785178)
    at Yo (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1785113)
    at el (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1823836)
    at Sa (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1802631)
    at https://codesandbox.io/static/js/vendors~app.ac35cfdb6.chunk.js?_sw-precache=d79ca66277a7e3fb57822585e588a671:1:996145
    at https://codesandbox.io/static/js/vendors~app.ac35cfdb6.chunk.js?_sw-precache=d79ca66277a7e3fb57822585e588a671:1:1130907
    at m.flush (https://codesandbox.io/static/js/vendors~app.ac35cfdb6.chunk.js?_sw-precache=d79ca66277a7e3fb57822585e588a671:1:1133794)
    at p.flush (https://codesandbox.io/static/js/vendors~app.ac35cfdb6.chunk.js?_sw-precache=d79ca66277a7e3fb57822585e588a671:1:1129961)
    at t (https://codesandbox.io/static/js/vendors~app.ac35cfdb6.chunk.js?_sw-precache=d79ca66277a7e3fb57822585e588a671:1:1003151)
  
    in re
    in Ee
    in t
    in t
    in div
    in Legacy___StyledElement
    in De
    in Unknown
    in be
    in Oe
    in o
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by tristandubbeld** [comment]
Hey @sdkdeepa, thanks for your report. I've created a PR with a fix, but I'll make sure to look into what caused this crash exactly. If you encounter more problems feel free to [contact our support](https://codesandbox.io/support)!
