### ISSUE TITLE
Trying to add a repository from GitHub...

### ISSUE THREAD

**Issue by GwynethLlewelyn** [codesandbox/codesandbox-client#7457]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  Import an existing GitHub repository (from an URL) to CodeSandbox.

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 110.0.0 | OS X 10.15.7           | 00bf42d8d          |

  **Route:**
  https://codesandbox.io/dashboard/repositories?workspace=bc1894b4-3414-4a06-a496-fd76f41637e7

  **Error Code:**
520c6ec38fe34b42be6567d6ccc3e56b

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of undefined (reading 'replace')
  TypeError: Cannot read properties of undefined (reading 'replace')
    at n (https://codesandbox.io/static/js/vendors~app.972b87076.chunk.js:1:1577549)
    at findBestMatch (https://codesandbox.io/static/js/vendors~app.972b87076.chunk.js:1:1578227)
    at Z (https://codesandbox.io/static/js/app.5b590aab1.js:9:359211)
    at https://codesandbox.io/static/js/app.5b590aab1.js:9:368149
    at ps (https://codesandbox.io/static/js/common.7a596f839.chunk.js:1:1817646)
    at Cl (https://codesandbox.io/static/js/common.7a596f839.chunk.js:1:1842459)
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.7a596f839.chunk.js:1:1860717)
    at qo (https://codesandbox.io/static/js/common.7a596f839.chunk.js:1:1785090)
    at wl (https://codesandbox.io/static/js/common.7a596f839.chunk.js:1:1842220)
    at il (https://codesandbox.io/static/js/common.7a596f839.chunk.js:1:1827121)
    at https://codesandbox.io/static/js/common.7a596f839.chunk.js:1:1785381
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.7a596f839.chunk.js:1:1860717)
    at qo (https://codesandbox.io/static/js/common.7a596f839.chunk.js:1:1785090)
    at Xo (https://codesandbox.io/static/js/common.7a596f839.chunk.js:1:1785326)
    at Yo (https://codesandbox.io/static/js/common.7a596f839.chunk.js:1:1785261)
    at se (https://codesandbox.io/static/js/common.7a596f839.chunk.js:1:1854469)
    at Sn (https://codesandbox.io/static/js/common.7a596f839.chunk.js:1:1768887)
    at HTMLDocument.patchedCallback (<anonymous>:132:45)
  
    in Pe
    in div
    in Styled(styled.div)
    in Ke
    in div
    in ForwardRef(p)
    in ForwardRef(p)
    in elements__TabContent
    in Tn
    in div
    in elements__ModalContent
    in div
    in elements__ModalBody
    in div
    in elements__Container
    in De
    in Unknown
    in Un
    in div
    in div
    in div
    in div
    in t
    in t
    in Modal___StyledModal
    in n
    in De
    in Unknown
    in te
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by CompuIves** [comment]
Found the issue, and it should be resolved now! Apologies for the inconvenience.
