### ISSUE TITLE
Cannot create Github repo from a Sandbox

### ISSUE THREAD

**Issue by guillempuche** [codesandbox/codesandbox-client#7488]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Signin via Github.

I create a project in CodeSandbox then try to create a repo on Github on my personal account.

The UI shows this error "Not able to push sandbox to a remote repository"

I debug the error on the browser console and get the following error.

```
ConvertToRepositoryForm.tsx:140 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'owner')
    at ConvertToRepositoryForm.tsx:140:28
    at s (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)
(anonymous) @ ConvertToRepositoryForm.tsx:140
s @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ ConvertToRepositoryForm.tsx:126
We @ react-dom.production.min.js:52
Ke @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
Er @ react-dom.production.min.js:100
Pr @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
je @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Mr @ react-dom.production.min.js:105
Jt @ react-dom.production.min.js:75
Zt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ie @ react-dom.production.min.js:292
Xt @ react-dom.production.min.js:73
```

## How has this issue affected you? What are you trying to accomplish?

Create a repo in Github from a project in CodeDandbox

### To Reproduce

I try setting public, private, different repo names, but not luck.

I think is related to the system doesn't select the default Github organization or CodeSandbox workspace. 

![Captura de pantalla 2023-03-06 a les 19 08 11](https://user-images.githubusercontent.com/3519924/223194298-c049f553-3724-4889-bb06-c6600ab1b782.png)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |       c64c763       |
| Browser          |      Chrome        |
| Operating System |        Macos      |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by h5gq3** [comment]
I'm having this too

**Comment by ogheneovo12** [comment]
same here

**Comment by guillempuche** [comment]
Have you solve it?

**Comment by Sharan1617** [comment]
Has anyone solved it ?

**Comment by samuelpath** [comment]
Same here today

**Comment by matt-scott** [comment]
Got the exact same screen as samuelpath above

**Comment by matt-scott** [comment]
Thanks for the suggestion, James.

I removed and re-added my GitHub credentials but this did not resolve the issue. I still get the "Not able to push sandbox to remote repository" error. And an empty repository of the name I typed in is created in my GitHub account.

**Comment by JamesACS** [comment]
Thanks @matt-scott -

Please could you contact us at support@codesandbox.io from the email associated with your account? 

If you could also let us know whether you're trying to import a private or public repository in that email. That would be fantastic!

**Comment by JamesACS** [comment]
Thank you everyone for your patience regarding this issue, 

I've now been able to reproduce and find a work around on our end while we work on a longer term solution. 

This only seems to happen when trying to link a Sandbox directly to a repository, if you use the 'Convert to Devbox' prompt in the top right and then connect the project to a repository, it will connect as expected. 

Because our repositories run in the same type of environment as Devboxes, there is no change in the final result. This is just an extra step for the moment.

**Comment by matt-scott** [comment]
This ressolves the issue. Thanks James!

**Comment by ndhola** [comment]
> Convert to Devbox

where is this option?

**Comment by Lakshyaultimate** [comment]
i tried doing this, the repository is created but nothing is visible on browser

**Comment by JamesACS** [comment]
@Lakshyaultimate Please contact us at support@codesandbox.io with a link to the environment in question
