### ISSUE TITLE
Not sure what happen. 

### ISSUE THREAD

**Issue by lrjbrual** [codesandbox/codesandbox-client#7530]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 111.0.0 | OS X 10.15.7           | 752f1e108          |

  **Route:**
  https://codesandbox.io/dashboard/repositories?workspace=c5c7656f-79cc-4a4f-a1e3-3d9095910765

  **Error Code:**
6506623d4eb04b33820e1ccd78e71d7f

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of undefined (reading 'map')
  TypeError: Cannot read properties of undefined (reading 'map')
    at S (https://codesandbox.io/static/js/app.f170b0c5f.js:9:408329)
    at ua (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1791262)
    at xs (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1836344)
    at ml (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1821948)
    at hl (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1821873)
    at il (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1819221)
    at https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1777663
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1852645)
    at qo (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1777372)
    at Xo (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1777608)
    at Yo (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1777543)
    at el (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1816010)
    at Sa (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1794919)
    at Object.error (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:39030)
    at g (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:1848199)
    at y (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:1848656)
    at e.value (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:1849273)
    at https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:381762
    at Array.forEach (<anonymous>)
    at y (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:381730)
    at Object.i [as error] (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:380813)
    at o (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:394989)
    at https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:395501
    at https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:401556
    at Set.forEach (<anonymous>)
    at https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:401532
    at Map.forEach (<anonymous>)
    at e.broadcastQueries (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:401482)
    at https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:403408
    at Object.next (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:1850339)
    at g (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:1848150)
    at y (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:1848656)
    at e.value (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:1849209)
    at https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:389196
    at Set.forEach (<anonymous>)
    at Object.next (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:389158)
    at g (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:1848150)
    at y (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:1848656)
    at e.value (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:1849209)
    at g (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:1848150)
    at y (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:1848656)
    at e.value (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:1849209)
    at Object.next (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:419277)
    at g (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:1848150)
    at y (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:1848656)
    at e.value (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:1849209)
    at Object.next (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:1850373)
    at g (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:1848150)
    at y (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:1848656)
    at e.value (https://codesandbox.io/static/js/vendors~app.0a5165019.chunk.js:1:1849209)
  
    in S
    in div
    in Styled(styled.div)
    in Jk
    in div
    in EmptyRepositories___StyledEmptyPageStyledWrapper
    in Yk
    in div
    in Selection___StyledStack
    in hb
    in tw
    in t
    in t
    in div
    in Content___StyledElement
    in Unknown
    in withRouter()
    in main
    in Dashboard___StyledElement3
    in div
    in Dashboard___StyledStack
    in Unknown
    in De
    in Unknown
    in vw
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by tristandubbeld** [comment]
Hey @lrjbrual, thanks for reporting this! I've created a PR to fix the issue. Let me know if this still happens to you once the PR has been merged and deployed to production!
