### ISSUE TITLE
tried to fork a sandbox and got crashed

### ISSUE THREAD

**Issue by Vishnu-hexr** [codesandbox/codesandbox-client#7561]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 112.0.0 | Windows 10           | 35619b613          |

  **Route:**
  https://codesandbox.io/s/horizon-ui-chakra-gt02dr?file=/src/components/calendar/MiniCalendar.js

  **Error Code:**
449f59c0bddf4610ae8bedb366b6ee60

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Method Date.prototype.toString called on incompatible receiver [object Object]
  TypeError: Method Date.prototype.toString called on incompatible receiver [object Object]
    at Date.toString (<anonymous>)
    at ne (https://codesandbox.io/static/js/common.f8acf6ef0.chunk.js?_sw-precache=c054b731cf61a060a899714d81835b51:1:677018)
    at ua (https://codesandbox.io/static/js/common.f8acf6ef0.chunk.js?_sw-precache=c054b731cf61a060a899714d81835b51:1:1798028)
    at xs (https://codesandbox.io/static/js/common.f8acf6ef0.chunk.js?_sw-precache=c054b731cf61a060a899714d81835b51:1:1843110)
    at ml (https://codesandbox.io/static/js/common.f8acf6ef0.chunk.js?_sw-precache=c054b731cf61a060a899714d81835b51:1:1828714)
    at hl (https://codesandbox.io/static/js/common.f8acf6ef0.chunk.js?_sw-precache=c054b731cf61a060a899714d81835b51:1:1828639)
    at il (https://codesandbox.io/static/js/common.f8acf6ef0.chunk.js?_sw-precache=c054b731cf61a060a899714d81835b51:1:1825987)
    at https://codesandbox.io/static/js/common.f8acf6ef0.chunk.js?_sw-precache=c054b731cf61a060a899714d81835b51:1:1784429
    at https://codesandbox.io/static/js/common.f8acf6ef0.chunk.js?_sw-precache=c054b731cf61a060a899714d81835b51:1:1859411
    at qo (https://codesandbox.io/static/js/common.f8acf6ef0.chunk.js?_sw-precache=c054b731cf61a060a899714d81835b51:1:1784138)
    at Xo (https://codesandbox.io/static/js/common.f8acf6ef0.chunk.js?_sw-precache=c054b731cf61a060a899714d81835b51:1:1784374)
    at Yo (https://codesandbox.io/static/js/common.f8acf6ef0.chunk.js?_sw-precache=c054b731cf61a060a899714d81835b51:1:1784309)
    at el (https://codesandbox.io/static/js/common.f8acf6ef0.chunk.js?_sw-precache=c054b731cf61a060a899714d81835b51:1:1822776)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.f8acf6ef0.chunk.js?_sw-precache=c054b731cf61a060a899714d81835b51:1:1789090)
    at n.setState (https://codesandbox.io/static/js/common.f8acf6ef0.chunk.js?_sw-precache=c054b731cf61a060a899714d81835b51:1:2042096)
    at n.value (https://codesandbox.io/static/js/default~app~embed.7a5ef2253.chunk.js:605:33192)
    at Object.<anonymous> (https://codesandbox.io/static/js/default~app~embed.7a5ef2253.chunk.js:605:31612)
    at https://codesandbox.io/static/js/default~app~embed~sandbox~sandbox-startup.9bc169785.chunk.js:1:6731
    at Array.forEach (<anonymous>)
    at A (https://codesandbox.io/static/js/default~app~embed~sandbox~sandbox-startup.9bc169785.chunk.js:1:6694)
    at P (https://codesandbox.io/static/js/default~app~embed~sandbox~sandbox-startup.9bc169785.chunk.js:1:6903)
  
    in ne
    in se
    in g
    in bound 
    in div
    in li
    in Unknown
    in Unknown
    in ol
    in Unknown
    in he
    in t
    in Ie
    in div
    in Styled(div)
    in t
    in WithTheme(t)
    in t
    in WithTheme(t)
    in div
    in Styled(div)
    in div
    in Styled(div)
    in v
    in t
    in div
    in Styled(div)
    in v
    in t
    in div
    in elements__Messages
    in div
    in elements__Container
    in n
    in WithTheme(n)
    in div
    in elements__ContentContainer
    in div
    in elements__Container
    in n
    in div
    in div
    in t
    in div
    in t
    in div
    in De
    in on
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in De
    in Ay
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by CompuIves** [comment]
Weird... I cannot reproduce this 🤔
