### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by mahdiahmadi313** [codesandbox/codesandbox-client#7585]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 112.0.0 | OS X 10.15.7           | 90b9a9aa1          |

  **Route:**
  https://codesandbox.io/signin?utm_source=landingpage

  **Error Code:**
6aa620024e16450c837f0eb65b239d6c

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of null (reading 'split')
  TypeError: Cannot read properties of null (reading 'split')
    at R (https://codesandbox.io/static/js/app.695036636.js:9:2092741)
    at ua (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1791262)
    at xs (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1836344)
    at ml (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1821948)
    at hl (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1821873)
    at il (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1819221)
    at https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1777663
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1852645)
    at qo (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1777372)
    at Xo (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1777608)
    at Yo (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1777543)
    at el (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1816010)
    at Sa (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1794919)
    at https://codesandbox.io/static/js/vendors~app.cc097fe24.chunk.js:1:1237945
    at e.callback (https://codesandbox.io/static/js/vendors~app.cc097fe24.chunk.js:1:1364861)
    at m.flush (https://codesandbox.io/static/js/vendors~app.cc097fe24.chunk.js:1:1367736)
    at p.flush (https://codesandbox.io/static/js/vendors~app.cc097fe24.chunk.js:1:1363915)
    at t (https://codesandbox.io/static/js/vendors~app.cc097fe24.chunk.js:1:1244921)
  
    in R
    in re
    in div
    in SignIn___StyledStack
    in div
    in SignIn___StyledElement
    in De
    in Unknown
    in j
    in o
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by CompuIves** [comment]
We found the issue and this one should be fixed now! Apologies for the inconvenience.
