### ISSUE TITLE
Importing from Codesandbox.

### ISSUE THREAD

**Issue by TestingUser1000** [codesandbox/codesandbox-client#7610]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 112.0.0 | Chrome OS x86_64           | a73a37f58          |

  **Route:**
  https://codesandbox.io/dashboard/recent?workspace=a7c1f978-fa2e-428d-8d09-a37936887658&utm_source=landingpage

  **Error Code:**
6ef08bd806be4a509770c1f2318c5da5

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of null (reading 'name')
  TypeError: Cannot read properties of null (reading 'name')
    at https://codesandbox.io/static/js/app.a93d3e146.js?_sw-precache=20a8dab73f5bd475dc4ab7bcc9973883:9:395960
    at ps (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1809711)
    at Cl (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1834437)
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1852645)
    at qo (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1777372)
    at wl (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1834200)
    at il (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1819144)
    at https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1777663
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1852645)
    at qo (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1777372)
    at Xo (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1777608)
    at Yo (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1777543)
    at Cl (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1834547)
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1852645)
    at qo (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1777372)
    at wl (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1834200)
    at https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1834111
    at z (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1852027)
    at A.port1.onmessage (https://codesandbox.io/static/js/common.bf7d829fe.chunk.js:1:1850771)
  
    in Kt
    in div
    in elements__ModalContent
    in div
    in elements__ModalBody
    in div
    in elements__Container
    in De
    in Unknown
    in dn
    in div
    in div
    in div
    in div
    in t
    in t
    in Modal___StyledModal
    in n
    in De
    in Unknown
    in te
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by CompuIves** [comment]
We found the issue and this one should be fixed now! Apologies for the inconvenience.
