### ISSUE TITLE
check pls!

### ISSUE THREAD

**Issue by anhoop89** [codesandbox/codesandbox-client#7622]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 113.0.0 | Windows 10           | 8cfa602ca          |

  **Route:**
  https://codesandbox.io/s/react-new?file=/src/App.js

  **Error Code:**
0abbfaef2d8343a79e2e3f7a98a173a2

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of null (reading 'split')
  TypeError: Cannot read properties of null (reading 'split')
    at B (https://codesandbox.io/static/js/app.baa43d48b.js:9:2066372)
    at ua (https://codesandbox.io/static/js/common.ab3c7e841.chunk.js:1:1789726)
    at xs (https://codesandbox.io/static/js/common.ab3c7e841.chunk.js:1:1834808)
    at ml (https://codesandbox.io/static/js/common.ab3c7e841.chunk.js:1:1820412)
    at hl (https://codesandbox.io/static/js/common.ab3c7e841.chunk.js:1:1820337)
    at il (https://codesandbox.io/static/js/common.ab3c7e841.chunk.js:1:1817685)
    at https://codesandbox.io/static/js/common.ab3c7e841.chunk.js:1:1776127
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.ab3c7e841.chunk.js:1:1851109)
    at qo (https://codesandbox.io/static/js/common.ab3c7e841.chunk.js:1:1775836)
    at Xo (https://codesandbox.io/static/js/common.ab3c7e841.chunk.js:1:1776072)
  
    in B
    in re
    in div
    in Styled(styled.div)
    in div
    in SignInModal___StyledElement
    in div
    in t
    in div
    in SignInModal___StyledStack
    in div
    in ForwardRef
    in di
    in pi
    in De
    in Unknown
    in K
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by CompuIves** [comment]
We found the issue and this one should be fixed now! Apologies for the inconvenience.
