### ISSUE TITLE
broke

### ISSUE THREAD

**Issue by Lokeshkhati** [codesandbox/codesandbox-client#7707]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 114.0.0 | Windows 10           | 97a4a5c88          |

  **Route:**
  https://codesandbox.io/s/create-a-digital-clock-gdmpjj?file=/src/index.js:0-104

  **Error Code:**
93e016510e554e8db2d24b485da6a512

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Method Date.prototype.toString called on incompatible receiver [object Object]
  TypeError: Method Date.prototype.toString called on incompatible receiver [object Object]
    at Date.toString (<anonymous>)
    at ne (https://codesandbox.io/static/js/common.595f6d4f8.chunk.js:1:685176)
    at ua (https://codesandbox.io/static/js/common.595f6d4f8.chunk.js:1:1798186)
    at xs (https://codesandbox.io/static/js/common.595f6d4f8.chunk.js:1:1843268)
    at ml (https://codesandbox.io/static/js/common.595f6d4f8.chunk.js:1:1828872)
    at hl (https://codesandbox.io/static/js/common.595f6d4f8.chunk.js:1:1828797)
    at il (https://codesandbox.io/static/js/common.595f6d4f8.chunk.js:1:1826145)
    at https://codesandbox.io/static/js/common.595f6d4f8.chunk.js:1:1784587
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.595f6d4f8.chunk.js:1:1859569)
    at qo (https://codesandbox.io/static/js/common.595f6d4f8.chunk.js:1:1784296)
  
    in ne
    in se
    in g
    in bound 
    in div
    in li
    in Unknown
    in Unknown
    in ol
    in Unknown
    in he
    in t
    in Ie
    in div
    in Styled(div)
    in t
    in WithTheme(t)
    in t
    in WithTheme(t)
    in div
    in Styled(div)
    in div
    in Styled(div)
    in v
    in t
    in div
    in Styled(div)
    in v
    in t
    in div
    in elements__Messages
    in div
    in elements__Container
    in n
    in WithTheme(n)
    in div
    in elements__ContentContainer
    in div
    in elements__Container
    in n
    in div
    in div
    in t
    in div
    in t
    in div
    in De
    in on
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in De
    in Ry
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by Lokeshkhati** [comment]
broke

**Comment by Lokeshkhati** [comment]
broke

**Comment by CompuIves** [comment]
Hey! There was a bad deploy of our browser console integration, making it crash on Date rendering. We rolled back now, and it should work as expected again. Apologies for the inconvenience!
