### ISSUE TITLE
tty

### ISSUE THREAD

**Issue by OK66688** [codesandbox/codesandbox-client#7710]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | safari | 4.0.0 | Android 5.1           | 97a4a5c88          |

  **Route:**
  https://codesandbox.io/dashboard/recent?workspace=2b08ddaf-fd7e-4221-ada1-8caa77eb8735

  **Error Code:**
9772b664d5064b2dbfabf891860b43f9

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Internal error. Icu error.
  TypeError: Internal error. Icu error.
    at DateTimeFormat.formatToParts (<anonymous>)
    at https://codesandbox.io/static/js/vendors~app.cc097fe24.chunk.js:1:571270
    at r (https://codesandbox.io/static/js/vendors~app.cc097fe24.chunk.js:1:571377)
    at a (https://codesandbox.io/static/js/vendors~app.cc097fe24.chunk.js:1:572118)
    at a (https://codesandbox.io/static/js/vendors~app.cc097fe24.chunk.js:1:573945)
    at s (https://codesandbox.io/static/js/vendors~app.cc097fe24.chunk.js:1:577401)
    at Tb (https://codesandbox.io/static/js/app.448dd64bd.js:9:842943)
    at ua (https://codesandbox.io/static/js/common.595f6d4f8.chunk.js:1:1798186)
    at xs (https://codesandbox.io/static/js/common.595f6d4f8.chunk.js:1:1843268)
    at ml (https://codesandbox.io/static/js/common.595f6d4f8.chunk.js:1:1828872)
    at hl (https://codesandbox.io/static/js/common.595f6d4f8.chunk.js:1:1828797)
    at il (https://codesandbox.io/static/js/common.595f6d4f8.chunk.js:1:1826145)
    at https://codesandbox.io/static/js/common.595f6d4f8.chunk.js:1:1784587
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.595f6d4f8.chunk.js:1:1859569)
    at qo (https://codesandbox.io/static/js/common.595f6d4f8.chunk.js:1:1784296)
    at Xo (https://codesandbox.io/static/js/common.595f6d4f8.chunk.js:1:1784532)
    at Yo (https://codesandbox.io/static/js/common.595f6d4f8.chunk.js:1:1784467)
    at el (https://codesandbox.io/static/js/common.595f6d4f8.chunk.js:1:1822934)
    at Sa (https://codesandbox.io/static/js/common.595f6d4f8.chunk.js:1:1801843)
    at https://codesandbox.io/static/js/vendors~app.cc097fe24.chunk.js:1:1237945
    at e.callback (https://codesandbox.io/static/js/vendors~app.cc097fe24.chunk.js:1:1364861)
    at m.flush (https://codesandbox.io/static/js/vendors~app.cc097fe24.chunk.js:1:1367736)
    at p.flush (https://codesandbox.io/static/js/vendors~app.cc097fe24.chunk.js:1:1363915)
    at t (https://codesandbox.io/static/js/vendors~app.cc097fe24.chunk.js:1:1244921)
  
    in Tb
    in li
    in RecentContent___StyledStack
    in ul
    in RecentContent___StyledStyledItemsWrapper
    in div
    in Selection___StyledStack
    in vb
    in div
    in Styled(styled.div)
    in div
    in RecentContent__StyledWrapper
    in jy
    in Iy
    in t
    in t
    in div
    in Content___StyledElement
    in Unknown
    in withRouter()
    in main
    in Dashboard___StyledElement3
    in div
    in Dashboard___StyledStack
    in Unknown
    in De
    in Unknown
    in jw
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by OK66688** [comment]
bhhjj

**Comment by OK66688** [comment]
ggh

**Comment by OK66688** [comment]
666

**Comment by OK66688** [comment]
666888
