### ISSUE TITLE
Crashing after sometime

### ISSUE THREAD

**Issue by IAMAFIVESTARMAN** [codesandbox/codesandbox-client#7720]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 114.0.0 | Windows 10           | 62a3c50a7          |

  **Route:**
  https://codesandbox.io/s/unruffled-goldwasser-ein1q4?file=/src/index.js

  

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of undefined (reading 'indexOf')
  TypeError: Cannot read properties of undefined (reading 'indexOf')
    at t.default (https://codesandbox.io/static/js/common.9637ade4f.chunk.js:1:640448)
    at ua (https://codesandbox.io/static/js/common.9637ade4f.chunk.js:1:1791394)
    at xs (https://codesandbox.io/static/js/common.9637ade4f.chunk.js:1:1836476)
    at ml (https://codesandbox.io/static/js/common.9637ade4f.chunk.js:1:1822080)
    at hl (https://codesandbox.io/static/js/common.9637ade4f.chunk.js:1:1822005)
    at il (https://codesandbox.io/static/js/common.9637ade4f.chunk.js:1:1819353)
    at https://codesandbox.io/static/js/common.9637ade4f.chunk.js:1:1777795
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.9637ade4f.chunk.js:1:1852777)
    at qo (https://codesandbox.io/static/js/common.9637ade4f.chunk.js:1:1777504)
    at Xo (https://codesandbox.io/static/js/common.9637ade4f.chunk.js:1:1777740)
  
    in Unknown
    in bound 
    in div
    in li
    in Unknown
    in Unknown
    in ol
    in Unknown
    in he
    in t
    in Ie
    in div
    in Styled(div)
    in t
    in WithTheme(t)
    in t
    in WithTheme(t)
    in div
    in Styled(div)
    in div
    in Styled(div)
    in v
    in t
    in div
    in Styled(div)
    in v
    in t
    in div
    in elements__Messages
    in div
    in elements__Container
    in n
    in WithTheme(n)
    in div
    in elements__ContentContainer
    in div
    in elements__Container
    in n
    in div
    in div
    in t
    in div
    in t
    in div
    in De
    in on
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in De
    in Ry
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by IAMAFIVESTARMAN** [comment]
Closed
