### ISSUE TITLE
Error While Requesting Access to Github Public Repositories and After Approving it

### ISSUE THREAD

**Issue by AbbbasAlhashimi** [codesandbox/codesandbox-client#8303]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 120.0.0 | OS X 10.15.7           | 580f5fec9          |

  **Route:**
  https://codesandbox.io/dashboard/repositories?workspace=f554a937-f211-455b-bb42-ea02d1bce5b4

  **Error Code:**
cdd24a9a034048dc8f88557affc763c0

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of undefined (reading 'authorization')
  TypeError: Cannot read properties of undefined (reading 'authorization')
    at a.cb (https://codesandbox.io/static/js/app.e5ac3e9a1.js?_sw-precache=28a8ae3fdb9b845053d9623584d1a8a1:9:1413314)
    at a.runScope (https://codesandbox.io/static/js/vendors~app.76f57511a.chunk.js?_sw-precache=f4a228a7283c0e6b77c670db1e0b2d1b:1:1339426)
    at a.evaluate (https://codesandbox.io/static/js/vendors~app.76f57511a.chunk.js?_sw-precache=f4a228a7283c0e6b77c670db1e0b2d1b:1:1339865)
    at Object.onGetFunction (https://codesandbox.io/static/js/vendors~app.76f57511a.chunk.js?_sw-precache=f4a228a7283c0e6b77c670db1e0b2d1b:1:1329422)
    at Object.get (https://codesandbox.io/static/js/vendors~app.76f57511a.chunk.js?_sw-precache=f4a228a7283c0e6b77c670db1e0b2d1b:1:1439970)
    at https://codesandbox.io/static/js/app.e5ac3e9a1.js?_sw-precache=28a8ae3fdb9b845053d9623584d1a8a1:9:754628
    at us (https://codesandbox.io/static/js/common.f414db27e.chunk.js:1:1967593)
    at Ks (https://codesandbox.io/static/js/common.f414db27e.chunk.js:1:1975815)
    at qs (https://codesandbox.io/static/js/common.f414db27e.chunk.js:1:1975634)
    at xa (https://codesandbox.io/static/js/common.f414db27e.chunk.js:1:2016131)
    at ml (https://codesandbox.io/static/js/common.f414db27e.chunk.js:1:1998279)
    at hl (https://codesandbox.io/static/js/common.f414db27e.chunk.js:1:1998204)
    at il (https://codesandbox.io/static/js/common.f414db27e.chunk.js:1:1995552)
    at https://codesandbox.io/static/js/common.f414db27e.chunk.js:1:1953994
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.f414db27e.chunk.js:1:2028976)
    at qo (https://codesandbox.io/static/js/common.f414db27e.chunk.js:1:1953703)
    at $o (https://codesandbox.io/static/js/common.f414db27e.chunk.js:1:1953939)
    at Yo (https://codesandbox.io/static/js/common.f414db27e.chunk.js:1:1953874)
    at el (https://codesandbox.io/static/js/common.f414db27e.chunk.js:1:1992341)
    at ks (https://codesandbox.io/static/js/common.f414db27e.chunk.js:1:1971250)
    at https://codesandbox.io/static/js/vendors~app.76f57511a.chunk.js?_sw-precache=f4a228a7283c0e6b77c670db1e0b2d1b:1:1321612
    at https://codesandbox.io/static/js/vendors~app.76f57511a.chunk.js?_sw-precache=f4a228a7283c0e6b77c670db1e0b2d1b:1:1442926
    at m.flush (https://codesandbox.io/static/js/vendors~app.76f57511a.chunk.js?_sw-precache=f4a228a7283c0e6b77c670db1e0b2d1b:1:1445597)
    at h.flush (https://codesandbox.io/static/js/vendors~app.76f57511a.chunk.js?_sw-precache=f4a228a7283c0e6b77c670db1e0b2d1b:1:1441980)
    at Object.cb (https://codesandbox.io/static/js/vendors~app.76f57511a.chunk.js?_sw-precache=f4a228a7283c0e6b77c670db1e0b2d1b:1:1328287)
    at e.emit (https://codesandbox.io/static/js/vendors~app.76f57511a.chunk.js?_sw-precache=f4a228a7283c0e6b77c670db1e0b2d1b:1:484436)
    at https://codesandbox.io/static/js/vendors~app.76f57511a.chunk.js?_sw-precache=f4a228a7283c0e6b77c670db1e0b2d1b:1:1332209
    at Proxy.<anonymous> (https://codesandbox.io/static/js/vendors~app.76f57511a.chunk.js?_sw-precache=f4a228a7283c0e6b77c670db1e0b2d1b:1:1330723)
    at https://codesandbox.io/static/js/app.e5ac3e9a1.js?_sw-precache=28a8ae3fdb9b845053d9623584d1a8a1:9:1043652
    at Generator.next (<anonymous>)
    at r (https://codesandbox.io/static/js/common-sandbox.09f563264.chunk.js:1:606)
    at a (https://codesandbox.io/static/js/common-sandbox.09f563264.chunk.js:1:817)
    at https://codesandbox.io/static/js/common-sandbox.09f563264.chunk.js:1:876
    at new Promise (<anonymous>)
    at https://codesandbox.io/static/js/common-sandbox.09f563264.chunk.js:1:757
    at https://codesandbox.io/static/js/app.e5ac3e9a1.js?_sw-precache=28a8ae3fdb9b845053d9623584d1a8a1:9:1044172
    at https://codesandbox.io/static/js/vendors~app.76f57511a.chunk.js?_sw-precache=f4a228a7283c0e6b77c670db1e0b2d1b:1:1332159
    at Proxy.<anonymous> (https://codesandbox.io/static/js/vendors~app.76f57511a.chunk.js?_sw-precache=f4a228a7283c0e6b77c670db1e0b2d1b:1:1330723)
    at https://codesandbox.io/static/js/app.e5ac3e9a1.js?_sw-precache=28a8ae3fdb9b845053d9623584d1a8a1:9:1044496
    at Generator.next (<anonymous>)
    at r (https://codesandbox.io/static/js/common-sandbox.09f563264.chunk.js:1:606)
    at a (https://codesandbox.io/static/js/common-sandbox.09f563264.chunk.js:1:817)
  
    in Unknown
    in div
    in Dashboard___StyledStack
    in Unknown
    in Ie
    in Unknown
    in Ik
    in t
    in t
    in div
    in elements__Content
    in Ie
    in withRouter(Ie)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in Ie
    in c
    in t
  ```

  </details>

**Comment by JamesACS** [comment]
Hello @AbbbasAlhashimi 

Unfortunately there isn't enough here to help us diagnose the issue.

Please contact support@codesandbox.io from the email address linked to your account, with a link to the effected environment and we'll do our best to help.
