### ISSUE TITLE
Crazh

### ISSUE THREAD

**Issue by Harry088** [codesandbox/codesandbox-client#8483]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 126.0.0 | Windows 10           | 98f11fbf5          |

  **Route:**
  https://codesandbox.io/s/framer-motion-animate-on-state-update-ns67ib?from-embed

  **Error Code:**
10ee2a85fb314a1bbdcca55c00d141dc

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of null (reading 'split')
  TypeError: Cannot read properties of null (reading 'split')
    at R (https://codesandbox.io/static/js/app.b9b8063f3.js:9:2092108)
    at ua (https://codesandbox.io/static/js/common.f8acf6ef0.chunk.js:1:1798028)
    at xs (https://codesandbox.io/static/js/common.f8acf6ef0.chunk.js:1:1843110)
    at ml (https://codesandbox.io/static/js/common.f8acf6ef0.chunk.js:1:1828714)
    at hl (https://codesandbox.io/static/js/common.f8acf6ef0.chunk.js:1:1828639)
    at il (https://codesandbox.io/static/js/common.f8acf6ef0.chunk.js:1:1825987)
    at https://codesandbox.io/static/js/common.f8acf6ef0.chunk.js:1:1784429
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.f8acf6ef0.chunk.js:1:1859411)
    at qo (https://codesandbox.io/static/js/common.f8acf6ef0.chunk.js:1:1784138)
    at Xo (https://codesandbox.io/static/js/common.f8acf6ef0.chunk.js:1:1784374)
  
    in R
    in re
    in div
    in Styled(styled.div)
    in div
    in SignInModal___StyledElement
    in div
    in t
    in div
    in SignInModal___StyledStack
    in div
    in ForwardRef
    in di
    in pi
    in De
    in Unknown
    in K
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by filipelima18** [comment]
Hi @Harry088. Are you still experiencing this issue? The Sandbox and its preview are opening as expected on my end.
