### ISSUE TITLE
why is the issue everytime when i open this app 

### ISSUE THREAD

**Issue by Vikaskumain** [codesandbox/codesandbox-client#8508]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 126.0.0 | Windows 10           | 2baf4a8b7          |

  **Route:**
  https://codesandbox.io/dashboard

  **Error Code:**
5933b58349d24d77836e4d435e41f304

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of null (reading 'limits')
  TypeError: Cannot read properties of null (reading 'limits')
    at De (https://codesandbox.io/static/js/app.35159a55c.js:9:1332649)
    at us (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:1965556)
    at xa (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:2010638)
    at ml (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:1996242)
    at hl (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:1996167)
    at il (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:1993515)
    at el (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:1990283)
    at Hl (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:2018199)
    at https://codesandbox.io/static/js/common.67289e494.chunk.js:1:2019432
    at al (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:1993863)
    at Yl (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:2019417)
    at render (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:2021340)
    at https://codesandbox.io/static/js/app.35159a55c.js:9:865588
  
    in De
    in div
    in Dashboard___StyledElement2
    in t
    in div
    in Dashboard___StyledStack
    in Unknown
    in Ie
    in Unknown
    in tC
    in t
    in t
    in div
    in elements__Content
    in De
    in withRouter(De)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in Ie
    in c
    in t
  ```

  </details>

**Comment by filipelima18** [comment]
Hi! Sorry about this poor experience. Shortly after you submitted this report, we merged [#8512](https://github.com/codesandbox/codesandbox-client/pull/8512) with a fix. Everything should be working as expected now.
