### ISSUE TITLE
Unable to setup dicedb repo with code sandbox

### ISSUE THREAD

**Issue by protyay** [codesandbox/codesandbox-client#8539]
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Cannot setup the diceDB repo with code sandbox
## How has this issue affected you? What are you trying to accomplish?
I'm trying to work on the project , dicedb
### To Reproduce
Following error occurs
```
Dockerfile-with-features:11
--------------------
   9 |     COPY . .
  10 |     
  11 | >>> RUN CGO_ENABLED=0 GOOS=linux go build -o /dicedb/dice-server
  12 |     EXPOSE 7379
  13 |     CMD ["/dicedb/dice-server"]
--------------------
ERROR: failed to solve: process "/bin/sh -c CGO_ENABLED=0 GOOS=linux go build -o /dicedb/dice-server" did not complete successfully: exit code: 2
Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-pitcher-host/container-features/0.50.2-1723387177954/Dockerfile-with-features -t vsc-dice-549272b079e140288873d022f64f5046a7f639b77120d26e938c604f7932b907 --target dev_containers_target_stage --build-context dev_containers_feature_content_source=/tmp/devcontainercli-pitcher-host/container-features/0.50.2-1723387177954 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /project/dice
    at IAA (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:463:1698)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async qw (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:462:1691)
    at async mK (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:462:610)
    at async mAA (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:479:3660)
    at async LC (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:479:4775)
    at async jeA (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:611:12219)
    at async _eA (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:611:11960)
{"outcome":"error","message":"Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-pitcher-host/container-features/0.50.2-1723387177954/Dockerfile-with-features -t vsc-dice-549272b079e140288873d022f64f5046a7f639b77120d26e938c604f7932b907 --target dev_containers_target_stage --build-context dev_containers_feature_content_source=/tmp/devcontainercli-pitcher-host/container-features/0.50.2-1723387177954 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /project/dice","description":"An error occurred building the image."}
Failed to run containers Command failed with exit code 1: devcontainer up --workspace-folder=/project/dice --override-config=/tmp/pitcher-containers/pitcher-host/workdir/.devcontainer.json --remove-existing-container --skip-post-attach --skip-post-create --additional-features="{\"ghcr.io/codesandbox/devcontainer-features/codesandbox:0.1.4\":{}}" --mount=type=bind,source=/project/dice,target=/project/dice --mount=type=bind,source=/project/home/pitcher-host/.persisted,target=/persisted --mount=type=bind,source=/project/home/pitcher-host/.cache,target=/root/.cache --mount=type=bind,source=/project/home/pitcher-host/.docker/run/docker.sock,target=/var/run/docker.sock --mount=type=bind,source=/usr/local/bin/lsp/,target=/usr/local/bin/lsp/ --mount=type=bind,source=/vscode,target=/vscode --mount=type=bind,source=/run/user/1001,target=/var/run --mount=type=bind,source=/pitcher/pitcher/out/pitcher-fs-server/fs-server,target=/usr/local/bin/fs-server --mount=type=bind,source=/opt/git,target=/opt/git --mount=type=bind,source=/opt/git/bin/git,target=/usr/bin/git --mount=type=bind,source=/opt/git/bin/git,target=/usr/local/bin/git
```

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |         Safari     |
| Operating System |      MacOS        |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by CompuIves** [comment]
It looks like `go build` failed in the Docker build. I wonder if `go` is installed at that point, what does the whole Dockerfile look like?
