### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RockyBalboa21** [codesandbox/codesandbox-client#8595]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 128.0.0 | Windows 10           | 94e799408          |

  **Route:**
  https://codesandbox.io/create-workspace?workspace=3fe4eee7-9aad-4e7c-adbc-aadfd8d4cebd

  **Error Code:**
ea6099ce787f4c4691f8485bad5e3047

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
  Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at yu (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:389552)
    at bs (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:409187)
    at https://codesandbox.io/static/js/common.85d204171.chunk.js:1:430880
    at qo (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:355607)
    at ys (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:407293)
    at is (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:397655)
    at https://codesandbox.io/static/js/common.85d204171.chunk.js:1:355898
    at https://codesandbox.io/static/js/common.85d204171.chunk.js:1:430880
    at qo (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:355607)
    at Go (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:355843)
    at Yo (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:355778)
    at es (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:394245)
    at xa (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:373154)
    at e (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:99478)
    at https://codesandbox.io/static/js/common.85d204171.chunk.js:1:102622
    at Array.forEach (<anonymous>)
    at Y (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:102594)
    at https://codesandbox.io/static/js/common.85d204171.chunk.js:1:98085
  
    in f
    in Unknown
    in span
    in Styled(styled.div)
    in $s
    in li
    in Styled(styled.div)
    in ul
    in Plans___StyledStack4
    in div
    in Plans___StyledStack3
    in Zs
    in div
    in Plans___StyledStyledCard
    in div
    in Styled(styled.div)
    in div
    in Plans___StyledHorizontalScroller
    in div
    in Styled(styled.div)
    in div
    in Plans___StyledStack
    in div
    in Plans___StyledAnimatedStep
    in plans
    in div
    in Layout___StyledStack3
    in div
    in Layout___StyledStack2
    in div
    in Layout___StyledStack
    in De
    in Unknown
    in Pc
    in Ad
    in Bd
    in t
    in t
    in div
    in elements__Content
    in Ne
    in withRouter(Ne)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by filipelima18** [comment]
Hi @RockyBalboa21. I wasn't able to reproduce the issue. Are you still getting errors when attempting to create a workspace?
