### ISSUE TITLE
Unable to create

### ISSUE THREAD

**Issue by aravind9643** [codesandbox/codesandbox-client#8644]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 130.0.0 | Windows 10           | 22963882e          |

  **Route:**
  https://codesandbox.io/dashboard/recent

  **Error Code:**
20c3003b199542c2b2a54a410914e870

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of null (reading 'status')
  TypeError: Cannot read properties of null (reading 'status')
    at Bo (https://codesandbox.io/static/js/app.423f35820.js:1:502553)
    at la (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:369497)
    at ku (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:414579)
    at vs (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:400183)
    at ps (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:400108)
    at is (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:397456)
    at https://codesandbox.io/static/js/common.85d204171.chunk.js:1:355898
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:430880)
    at qo (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:355607)
    at Go (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:355843)
    at Yo (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:355778)
    at ue (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:424655)
    at xn (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:339451)
    at HTMLDocument.r (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:159071)
  
    in Bo
    in div
    in elements__ModalContent
    in div
    in elements__ModalBody
    in div
    in elements__Container
    in De
    in Unknown
    in yr
    in br
    in div
    in div
    in Modal___StyledElement
    in div
    in div
    in t
    in t
    in Modal___StyledModal
    in w
    in De
    in Unknown
    in Wl
    in Ne
    in withRouter(Ne)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by filipelima18** [comment]
Hi @aravind9643. Is this problem still occurring? I was unable to reproduce it on my end.

**Comment by aravind9643** [comment]
Yes I am getting issue in my account when creating, please find
attachments, may be these will help.

[image: image.png]

[image: image.png]

**Comment by filipelima18** [comment]
Hi @aravind9643 - could you send the images again? It seems that GitHub failed to upload the images you tried to attach.
