### ISSUE TITLE
cant login

### ISSUE THREAD

**Issue by Ragas30** [codesandbox/codesandbox-client#8674]
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 131.0.0 | Windows 10           | 0dd52a73f          |

  **Route:**
  https://codesandbox.io/signup/_IxZCNC9iBJYIG77qXRHR54O70inGg4XOUoRfM3f7XM

  **Error Code:**
962909d731814c79924411c57c0947a5

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  SecurityError: Failed to read a named property 'origin' from 'Location': Blocked a frame with origin "https://codesandbox.io" from accessing a cross-origin frame.
  SecurityError: Failed to read a named property 'origin' from 'Location': Blocked a frame with origin "https://codesandbox.io" from accessing a cross-origin frame.
    at hu (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:387946)
    at Os (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:412672)
    at https://codesandbox.io/static/js/common.85d204171.chunk.js:1:430880
    at qo (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:355607)
    at ws (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:412435)
    at https://codesandbox.io/static/js/common.85d204171.chunk.js:1:412346
    at F (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:430262)
    at MessagePort.<anonymous> (https://codesandbox.io/static/js/common.85d204171.chunk.js:1:429006)
  
    in u
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in Ne
    in withRouter(Ne)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by filipelima18** [comment]
Hi @Ragas30 - Are you still experiencing this issue?
